---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2026-01-28T09:31:04Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:rules: {}
    manager: cluster-olm-operator
    operation: Update
    time: "2026-01-28T09:31:04Z"
  name: catalogd-manager-role
  resourceVersion: "7898"
  uid: 9c91af57-2712-4b6f-9a6a-e6244a3ec499
rules:
- apiGroups:
  - olm.operatorframework.io
  resources:
  - clustercatalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - clustercatalogs/finalizers
  verbs:
  - update
- apiGroups:
  - olm.operatorframework.io
  resources:
  - clustercatalogs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
