---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2026-01-28T09:29:19Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"7763cebb-f1d7-4359-81b8-b55ef9916383"}: {}
      f:rules: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2026-01-28T09:29:19Z"
  name: openshift-ovn-kubernetes-node-limited
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 7763cebb-f1d7-4359-81b8-b55ef9916383
  resourceVersion: "4366"
  uid: d694b29e-8b12-47df-8e46-0d544b603fcf
rules:
- apiGroups:
  - ""
  resources:
  - pods/status
  - nodes/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - k8s.ovn.org
  resources:
  - adminpolicybasedexternalroutes
  - egressfirewalls
  - egressips
  - egressqoses
  - egressservices
  - userdefinednetworks
  - clusteruserdefinednetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.ovn.org
  resources:
  - adminpolicybasedexternalroutes/status
  - egressfirewalls/status
  - egressqoses/status
  verbs:
  - patch
- apiGroups:
  - policy.networking.k8s.io
  resources:
  - adminnetworkpolicies
  - baselineadminnetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.networking.k8s.io
  resources:
  - adminnetworkpolicies/status
  - baselineadminnetworkpolicies/status
  verbs:
  - patch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  - multi-networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
