---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2026-01-28T09:31:03Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:rules: {}
    manager: cluster-olm-operator
    operation: Update
    time: "2026-01-28T09:31:03Z"
  name: operator-controller-proxy-role
  resourceVersion: "7851"
  uid: 552aaf2e-53f3-4933-a4cc-4a534d1f2c78
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
