---
apiVersion: operator.openshift.io/v1
kind: CloudCredential
metadata:
  creationTimestamp: "2026-01-28T09:25:08Z"
  generation: 1
  managedFields:
  - apiVersion: operator.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:credentialsMode: {}
        f:logLevel: {}
        f:operatorLogLevel: {}
    manager: cluster-bootstrap
    operation: Update
    time: "2026-01-28T09:25:08Z"
  name: cluster
  resourceVersion: "541"
  uid: 0274e673-19b4-410a-9139-a717f2053c3f
spec:
  credentialsMode: ""
  logLevel: Normal
  operatorLogLevel: Normal
