---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVDekNDQXZPZ0F3SUJBZ0lJTjdaeFYzYjJaVEF3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TlRWYUZ3MHlPREF4TWpnd09UTXdOVFphTURReE1qQXdCZ05WQkFNVEtXMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMWE5sY25acFkyVXRZMkV0YjNCbGNtRjBiM0l1YzNaak1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVYVjhPN01nSXk2ak9XRTIxNjF3TXFPSFhxS0FZSDMwSVhSdgp0TWM1NG53T0xkRlRQVGlMNm5vZVM1UmtwbUNvclF1MmdDMm85Umo3Tkd3WXhRWC9zSGlmTG42ZzQwQVlmcmRsCi9TMHN2VVlZUFlyVEs1Y0s1MWVuWDNJa2ptbno5cTYrTm1SRGhRZkZ6N3pGZXZtRklkNjZ4N0JQNE9ncERxS2gKNzIyYUc3UEZ6bFhnMlo3eWhGY1Y5UFB2QlpleHRCWFgrSE5lZy9MdTNrdTFJdGpFSFRhNWtyT3lHbHFXMHAyRwpudHZHR0NvK3BMVEUwaDVMZy8xYThJckdYaXJlNUVKcmN4TC95R0ZyeXJoSkQvWWZ5QnNxbUxmT05uVHlkalVpCndQZ2tiSGJ4Q3ZiK1did3J4OVU5Y0ZiQjd4UnhkaWx3b0xDYVQzSHh0RU1lNllHT3d3SURBUUFCbzRJQkhUQ0MKQVJrd0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQgovd1FDTUFBd0hRWURWUjBPQkJZRUZMZHFlMFdHdGh2ZXl0MVJOWklXWGxGZGN4QkdNQjhHQTFVZEl3UVlNQmFBCkZKakJmbGhWVytLaEgzejZPajNhcGNDdFBQWHJNRzBHQTFVZEVRUm1NR1NDS1cxbGRISnBZM011YjNCbGJuTm8KYVdaMExYTmxjblpwWTJVdFkyRXRiM0JsY21GMGIzSXVjM1pqZ2pkdFpYUnlhV056TG05d1pXNXphR2xtZEMxegpaWEoyYVdObExXTmhMVzl3WlhKaGRHOXlMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNRFVHQ3lzR0FRUUJrZ2dSClpBSUJCQ1lUSkRWa1pXUXpNbVV3TFRZMFkyRXRORGswTkMwNU5HTmlMVEJsTW1VMVlqRmlaREJtTURBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFOdnZwanBZdU5EZ09JZ2RLWGJJU1dUSXR4MXhFV3FkeGR1THNhbzNWMFZzbgpnV09MTE83NmJ4ZmVmTGdXajNUV0N6UmVOU1c5V0M4aUVFTVRMT0ptbW9qNUVNWW1HK3hXQlhWTG5sMFNLbEF3CjRKOXRWRFBIT0ZRcUlZVGwwRlhRbEg4MTVwZjRGMHZ3bDZsei9zU3hiL0hIZ1NFRGUxQ1hPa1ZaWVd4a3QxMzgKSGFDNGpySWhCanNJcllLMEEza09sVExkeXNZWlArdSs2YSs0TXhHbHRVeExDSi9qbDRGVzJiYUJ0NC9veTlZdAo2ellhZlprdExlazI5N0RlVDNSR2p4THFjUzRTWG9xQWQyQmtpTWxydG1aSnJQcUpvNE1xZUc3Z0o0dlQ4UEo4CktIbkt4c3luNFlpbWdlbWZPWFhieHFiODdVQ2w1V3J2OFNlRFlmTkF3Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-service-ca-operator.svc and is annotated to the service
        with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:56Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:30:56Z"
      service.beta.openshift.io/originating-service-name: metrics
      service.beta.openshift.io/originating-service-uid: 5ded32e0-64ca-4944-94cb-0e2e5b1bd0f0
    creationTimestamp: "2026-01-28T09:30:57Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5ded32e0-64ca-4944-94cb-0e2e5b1bd0f0"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:57Z"
    name: serving-cert
    namespace: openshift-service-ca-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: 5ded32e0-64ca-4944-94cb-0e2e5b1bd0f0
    resourceVersion: "7516"
    uid: 31967c3c-bab9-4efa-adea-b0cdae48fffa
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35168"
