---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVzRENDQTVpZ0F3SUJBZ0lJTW9Ha1VzUWJkZ293RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRSYUZ3MHlPREF4TWpnd09UTXdORFZhTUVFeFB6QTlCZ05WQkFNTU5pb3VhVzFoCloyVXRjbVZuYVhOMGNua3RiM0JsY21GMGIzSXViM0JsYm5Ob2FXWjBMV2x0WVdkbExYSmxaMmx6ZEhKNUxuTjIKWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXBwYm02SWVqU2VtK1g3cjRzWgpxVjVmWnVDa3k0ektaQnl2Yld2ZkV5bU5UYmErL0NwRmdONjZMQWc0OHRlNEoweXBFUmkwWjN0RU45anpNYU93Cjh3bDd2SCtDS1Q2ZkR4YStUaG1zRzBoL1JFa085ak5Ta09jY0NBK2YrMmkzNDFJUlhkUlJQSTFuSFhIZnNHdDkKdWdkUmJ2UjdOUkNwbjhhZmhEdjFaeDQ1TXZIaExlZis3UEFOL1hLVWVPbGd6ODhrYm9TMmNaVm03anFOVDUwYwpRbFFuT0VKYXphN1VYeEgzRG91VHB6K1B4ZGhENm9TZzBJa2h5bWRKN280dnZENFVicDIwK3BKMWlJK2l3ci93CmFtaGsrNkxhQUJGL1FKRTNTemxzeUI4bm14bkNlV284eS9mNWF6cEU0a1pMMW5SZG5iVTA3c2ljNUV3VkVHeXUKUVg4Q0F3RUFBYU9DQWJVd2dnR3hNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRgpCUWNEQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJLM0ZBMUtSR3o1Y2FjMzhMYytsbjAvYTMrCkxqQWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxNnpDQ0FRTUdBMVVkRVFTQit6Q0IKK0lJMktpNXBiV0ZuWlMxeVpXZHBjM1J5ZVMxdmNHVnlZWFJ2Y2k1dmNHVnVjMmhwWm5RdGFXMWhaMlV0Y21WbgphWE4wY25rdWMzWmpna1FxTG1sdFlXZGxMWEpsWjJsemRISjVMVzl3WlhKaGRHOXlMbTl3Wlc1emFHbG1kQzFwCmJXRm5aUzF5WldkcGMzUnllUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiSUkwYVcxaFoyVXRjbVZuYVhOMGNua3QKYjNCbGNtRjBiM0l1YjNCbGJuTm9hV1owTFdsdFlXZGxMWEpsWjJsemRISjVMbk4yWTRKQ2FXMWhaMlV0Y21WbgphWE4wY25rdGIzQmxjbUYwYjNJdWIzQmxibk5vYVdaMExXbHRZV2RsTFhKbFoybHpkSEo1TG5OMll5NWpiSFZ6CmRHVnlMbXh2WTJGc01EVUdDeXNHQVFRQmtnZ1JaQUlCQkNZVEpEZ3paamxtWVRkbUxUWmhNMkV0TkRBeE5pMDUKTnpJMkxXVXpNVEkyWldFMlpERTNPREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUStQaGNtU0tzck9TbHlWRwpjRkNIVjdUaWI3L001OGlWc00wR08rV0JTRDRxd1E4OVVqb243WDJrTVpVOXhEa0xJckNZbTZaclQ3YkFGSjExCjE1L3NKV1Z3d0xBTEpXSDFmOWdVTDE3dys1cTd2RzVVQWttWm1ZcTNlWVdNQ01MK3hJSVRnQTJoSG95cnYrZGEKaW5EUWNSUHk5cUNUcnB5TEJUcHhnRmx4VTV5YW9pdnZXWUpWYVpMa29XcWxjUFJ1QXU2ZDdJblRDT09ibmw5Ywo3a3hid1RXU3JFWllSUmxqV21SU2hJc1c2UWlDSFVEa2Mrd0JtYmFhUGVIa0txdGQvUldacVdUekN1SmpFa0RCCjloUHFKeGFpK3pUb2lEa1FQajlGY1NKSk1lVElxRmlSQTRrOWZDdVlrVzBYaE02SU9QeWpPNk01ZjA0WmxKL2EKeTBZVWtRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/image-registry-operator
        with hostname image-registry-operator.openshift-image-registry.svc and is
        annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        image-registry-operator-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:45Z"
      service.alpha.openshift.io/originating-service-name: image-registry-operator
      service.alpha.openshift.io/originating-service-uid: 83f9fa7f-6a3a-4016-9726-e3126ea6d178
      service.beta.openshift.io/expiry: "2028-01-28T09:30:45Z"
    creationTimestamp: "2026-01-28T09:30:46Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"83f9fa7f-6a3a-4016-9726-e3126ea6d178"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:46Z"
    name: image-registry-operator-tls
    namespace: openshift-image-registry
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: image-registry-operator
      uid: 83f9fa7f-6a3a-4016-9726-e3126ea6d178
    resourceVersion: "6931"
    uid: 283732ce-7af2-44aa-b4e3-5cfe6e4e08ec
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    credentials: MTE1IGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    annotations:
      imageregistry.operator.openshift.io/checksum: sha256:ace4df523d76e5b7cfed994c544983734652ee92b4ba7ef13e12b0f428d978c9
    creationTimestamp: "2026-01-28T09:41:56Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:credentials: {}
        f:metadata:
          f:annotations:
            .: {}
            f:imageregistry.operator.openshift.io/checksum: {}
        f:type: {}
      manager: cluster-image-registry-operator
      operation: Update
      time: "2026-01-28T09:41:56Z"
    name: image-registry-private-configuration
    namespace: openshift-image-registry
    resourceVersion: "20095"
    uid: acce7293-b6b7-424b-bdb6-64b035cd1496
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVFVENDQXZtZ0F3SUJBZ0lJYkJ0akJ0UXI1eXd3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVFF4TlRaYUZ3MHlPREF4TWpnd09UUXhOVGRhTURZeE5EQXlCZ05WQkFNVEsybHRZV2RsCkxYSmxaMmx6ZEhKNUxtOXdaVzV6YUdsbWRDMXBiV0ZuWlMxeVpXZHBjM1J5ZVM1emRtTXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2VabGIxcitEczUzWmVyYllPWEk5RjU3dVlKeE1xUmJRRQpHbVdwV0M1a1R5VE9uODUwNmRHM0doS243RGEyTzlNdVI1ZjdmV251eXRDenpxZktPa3Rib2xPZ0N0Z1FBUDM3CnBUdHVmL3pWT1dqSzBDeHpMNzdwREtnejZoNFYyUGpnRXp2MGNuT2RHOUpRV056R0EzUGN4K3RFK1lkTXg3V3EKWTgxbkY1LzlXRmQza2ZEeFpVQkhZWHlVQ3VkZHA1ZTIxZHltN3grYjUxUXl3Z0tsQTNIcjlmNjlidW9vRDFQcwp3ZExyR1d4MmhtTTZWakdRcnlXVFRoVE16RTNleUFrMkFJWFQyZi93WFhxOWZYakJDUitTNWNGOXV0Vm9pd2tHCkhOQVdzZ0l5TlBwS0RPenFqOGRpaURBSnlSTVZoakZXMUNVV1dwazFLa29MbllHMmZ3cHpBZ01CQUFHamdnRWgKTUlJQkhUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEQVlEVlIwVApBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVERGNwR2twc3lZc2V4b2xWd2lLREFibTJXREl3SHdZRFZSMGpCQmd3CkZvQVVtTUYrV0ZWYjRxRWZmUG82UGRxbHdLMDg5ZXN3Y1FZRFZSMFJCR293YUlJcmFXMWhaMlV0Y21WbmFYTjAKY25rdWIzQmxibk5vYVdaMExXbHRZV2RsTFhKbFoybHpkSEo1TG5OMlk0STVhVzFoWjJVdGNtVm5hWE4wY25rdQpiM0JsYm5Ob2FXWjBMV2x0WVdkbExYSmxaMmx6ZEhKNUxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01EVUdDeXNHCkFRUUJrZ2dSWkFJQkJDWVRKRFV3T1dKbE5tTXdMV1poTW1JdE5EQXhOaTFoT0RaakxUQXpNbVprTkRZM1lUQTQKWkRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUVFSTRuWVBlTmNNcUFuV3R6OTlHbHpYeUsram0wSHpnRVZ0eAoweTFnbDR2bWRWWC8xYVRtaExLY005amk5MU9pSzFUOHA1MnV1aWkySXc3MGhLL3dhZFdGb2JIbk5rQVVqQzNBCkIyb2NOQjRZWkZpQ3h3bnpjUjI0YTVyNTZkbk1jU2FnQmJLREc4ZnZkc2s3WmkzK2RGS0hjV2tFQzM2L3BOL20KS053QUxwSG5sL2ZHU0cxbFlEdFNOdFVFN3ZKaXNCZzNSZWdzSitMdnJIdnBLcmU1cjl1SVJEY1JwQXlOK3ZNVwpROWVYTXlmb0g0RTdXai9sSUZaUmV5OEkvQ1NZRCtiYU83M1FVOXQzdXp3RE5uUktzRHYvVXBMUzl3aXovUE9MCitsZFJPYnhBa2lsZDEyd05rbGhuSDNSellZeE9ZMTc2NlltRnpacWhmSXdqK0NQQTF3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/image-registry with hostname
        image-registry.openshift-image-registry.svc and is annotated to the service
        with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        image-registry-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:41:57Z"
      service.alpha.openshift.io/originating-service-name: image-registry
      service.alpha.openshift.io/originating-service-uid: 509be6c0-fa2b-4016-a86c-032fd467a08d
      service.beta.openshift.io/expiry: "2028-01-28T09:41:57Z"
    creationTimestamp: "2026-01-28T09:41:57Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"509be6c0-fa2b-4016-a86c-032fd467a08d"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:41:57Z"
    name: image-registry-tls
    namespace: openshift-image-registry
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: image-registry
      uid: 509be6c0-fa2b-4016-a86c-032fd467a08d
    resourceVersion: "20194"
    uid: 650023af-ed8a-4773-a400-a2f67bdfe9c8
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    .dockerconfigjson: NDU4OCBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      imageregistry.operator.openshift.io/checksum: sha256:c8f23fff6fbd26cb48aab05d780d4d61ca9d7de61865cc557060577995407985
    creationTimestamp: "2026-01-28T09:41:56Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:.dockerconfigjson: {}
        f:metadata:
          f:annotations:
            .: {}
            f:imageregistry.operator.openshift.io/checksum: {}
        f:type: {}
      manager: cluster-image-registry-operator
      operation: Update
      time: "2026-01-28T09:41:56Z"
    name: installation-pull-secrets
    namespace: openshift-image-registry
    resourceVersion: "20092"
    uid: e00684ae-a383-4173-8a37-097bb16dd295
  type: kubernetes.io/dockerconfigjson
- apiVersion: v1
  data:
    aws_access_key_id: MjAgYnl0ZXMgbG9uZw==
    aws_secret_access_key: NDAgYnl0ZXMgbG9uZw==
    credentials: MTE1IGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    annotations:
      cloudcredential.openshift.io/aws-policy-last-applied: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:CreateBucket","s3:DeleteBucket","s3:PutBucketTagging","s3:GetBucketTagging","s3:PutBucketPublicAccessBlock","s3:GetBucketPublicAccessBlock","s3:PutEncryptionConfiguration","s3:GetEncryptionConfiguration","s3:PutLifecycleConfiguration","s3:GetLifecycleConfiguration","s3:GetBucketLocation","s3:ListBucket","s3:GetObject","s3:PutObject","s3:DeleteObject","s3:ListBucketMultipartUploads","s3:AbortMultipartUpload","s3:ListMultipartUploadParts"],"Resource":"*"},{"Effect":"Allow","Action":["iam:GetUser"],"Resource":"arn:aws:iam::387344700001:user/ci-ln-vjb5l1t-76ef8--openshift-image-registry-9mnfh"}]}'
      cloudcredential.openshift.io/credentials-request: openshift-cloud-credential-operator/openshift-image-registry
    creationTimestamp: "2026-01-28T09:27:03Z"
    labels:
      cloudcredential.openshift.io/credentials-request: "true"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:aws_access_key_id: {}
          f:aws_secret_access_key: {}
          f:credentials: {}
        f:metadata:
          f:annotations:
            .: {}
            f:cloudcredential.openshift.io/aws-policy-last-applied: {}
            f:cloudcredential.openshift.io/credentials-request: {}
          f:labels:
            .: {}
            f:cloudcredential.openshift.io/credentials-request: {}
        f:type: {}
      manager: cloud-credential-operator
      operation: Update
      time: "2026-01-28T09:27:03Z"
    name: installer-cloud-credentials
    namespace: openshift-image-registry
    resourceVersion: "2907"
    uid: 72f0cbdd-79b4-4be6-8ec0-3ecb3bf1ed2b
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "35043"
