---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:31:52Z"
    creationTimestamp: "2026-01-28T09:26:00Z"
    labels:
      app: kube-storage-version-migrator-operator
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:31:52Z"
    name: metrics
    namespace: openshift-kube-storage-version-migrator-operator
    resourceVersion: "9716"
    uid: aa764c6c-ca62-4838-949f-3555344546ef
  subsets:
  - addresses:
    - ip: 10.130.0.23
      nodeName: ip-10-0-108-54.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: kube-storage-version-migrator-operator-fd7dc879c-k2xj9
        namespace: openshift-kube-storage-version-migrator-operator
        uid: 39ca98a5-4a5f-49ae-b1cb-d748ba0fe88a
    ports:
    - name: https
      port: 8443
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "35108"
