---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVSekNDQXkrZ0F3SUJBZ0lJYml3YU5Rc250UkV3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRaYUZ3MHlPREF4TWpnd09UTXdORGRhTUVjeFJUQkRCZ05WQkFNVFBHMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMV3QxWW1VdGMzUnZjbUZuWlMxMlpYSnphVzl1TFcxcFozSmhkRzl5TFc5d1pYSmgKZEc5eUxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNWHprblBRSWIxSAo2dUplV0Y0TCtudWRCNXR6ZXVaK1U2TXJOcHozUkNCOEdqT0tZQXpsY0VXMkFyOVNaUGJxRUh3UGxLL2NsUkYwCjNsUmlGZVpBU294UmF2MFk5NGZadHhxdCsybmh4RVBEcU5JMW1DNThXeW5saGJFdDhZb29QK2ZWZWVrY2c3TnIKUzhhKy9SR2daZ3BxSklaSkYwbXRRTVphWXY5enh5dVVqSFE3bmFubHRTTVowS0t4SDRUU0NFaFJseURYdU95SQpZWmRhM1Jzb3NBd0dLblZqcTJ4WmhTZVRaOE43RVdWYXdDZWpIZnpxQTNlTC9sd2lvcGd6Zk1WQ1U4cURPcUgyCkluNVpPY09KN0tZWU5xcTRodnBERnpEdzA3OHJkZHBTOTQwR0V6cmZ5Y201YUtNemFoYVJodm4xY0ZCbW13QkwKRCt0YmNXWmxjUjhDQXdFQUFhT0NBVVl3Z2dGQ01BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBSwpCZ2dyQmdFRkJRY0RBVEFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVERva1NiYndpMHBSMW9pVzBsCkNYa0l4d2R5MVRBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejE2ekNCbFFZRFZSMFIKQklHTk1JR0tnanh0WlhSeWFXTnpMbTl3Wlc1emFHbG1kQzFyZFdKbExYTjBiM0poWjJVdGRtVnljMmx2YmkxdAphV2R5WVhSdmNpMXZjR1Z5WVhSdmNpNXpkbU9DU20xbGRISnBZM011YjNCbGJuTm9hV1owTFd0MVltVXRjM1J2CmNtRm5aUzEyWlhKemFXOXVMVzFwWjNKaGRHOXlMVzl3WlhKaGRHOXlMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnMKTURVR0N5c0dBUVFCa2dnUlpBSUJCQ1lUSkRKbE5qSmlNRFU1TFRBM1lUY3RORFk1TUMxaU16aGhMVEF3TlRaawpNell3WXpZd1lUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFheHFydlE5NzdGRzZoVXNNWTdOT3lIRzVOZzR0CmV3TW9wbjNnYkYxaHdxUHpWN2J6RWl0VU5lYnROMmcxaUY0TCtKRTVIR2NoVDdCL0FKWmNXdjFxMmx1ZDZGc0cKZ2FBWk84bHRYZSt4b2VnNUVwQXN4K092T1RpNTAxOEhYMGRJZzRXcGlUN1dCa2JHaUJyZG8rc0pFWW9RWFJJdgpNbXBDTThVRU0zVlRydWM2NVEvbG9RWnhic2VaZTVabWw2ZzlXZml0ckRCUmtpZS8zb2NyYTZ2emp3V0ZpQ0ZUClVZdzJRRVZrUURHa3l5ZUtJaWdUclU2QkM1U0pTdTJHcVZoZ2pMUDYxb3pNOHB4b0RjZlY5ak1ZOVpCRTZPbnMKbTUzYjFieHE0cEtXVmc5cEY4cWFUOE9mcXY4QkI3QTh3U1dJUFVXdzNlTCs0L29pYlhVTnVjZ2dXUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-kube-storage-version-migrator-operator.svc and is annotated
        to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:47Z"
      service.alpha.openshift.io/originating-service-name: metrics
      service.alpha.openshift.io/originating-service-uid: 2e62b059-07a7-4690-b38a-0056d360c60a
      service.beta.openshift.io/expiry: "2028-01-28T09:30:47Z"
    creationTimestamp: "2026-01-28T09:30:48Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"2e62b059-07a7-4690-b38a-0056d360c60a"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:48Z"
    name: serving-cert
    namespace: openshift-kube-storage-version-migrator-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: 2e62b059-07a7-4690-b38a-0056d360c60a
    resourceVersion: "7074"
    uid: 6c2ca45e-5376-4f1c-acf0-d373491326fc
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35109"
