---
apiVersion: v1
data:
  cloud.conf: |
    [Global]
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-28T09:29:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:cloud.conf: {}
      f:metadata:
        f:ownerReferences:
          k:{"uid":"7763cebb-f1d7-4359-81b8-b55ef9916383"}: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2026-01-28T09:30:50Z"
  name: kube-cloud-config
  namespace: openshift-cloud-network-config-controller
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 7763cebb-f1d7-4359-81b8-b55ef9916383
  resourceVersion: "7273"
  uid: b86548f2-18e1-4939-8551-abc467c82d01
