---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2026-01-28T09:25:59Z"
  generation: 1
  managedFields:
  - apiVersion: monitoring.coreos.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:exclude.release.openshift.io/internal-openshift-hosted: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
      f:spec:
        .: {}
        f:groups:
          .: {}
          k:{"name":"cluster-topology"}:
            .: {}
            f:name: {}
            f:rules: {}
          k:{"name":"cluster-version"}:
            .: {}
            f:name: {}
            f:rules: {}
    manager: cluster-version-operator
    operation: Update
    time: "2026-01-28T09:25:59Z"
  name: kube-apiserver-operator
  namespace: openshift-kube-apiserver-operator
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 0370d296-6904-481d-ab90-157c7e5b835a
  resourceVersion: "1692"
  uid: e032d179-ea35-4ce9-8818-7b651d3642dd
spec:
  groups:
  - name: cluster-version
    rules:
    - alert: TechPreviewNoUpgrade
      annotations:
        description: Cluster has enabled Technology Preview features that cannot be
          undone and will prevent upgrades. The TechPreviewNoUpgrade feature set is
          not recommended on production clusters.
        summary: Cluster has enabled tech preview features that will prevent upgrades.
      expr: |
        cluster_feature_set{name=~"TechPreviewNoUpgrade|CustomNoUpgrade", namespace="openshift-kube-apiserver-operator"} == 0
      for: 10m
      labels:
        severity: warning
  - name: cluster-topology
    rules:
    - expr: sum by(mode) (cluster_controlplane_topology)
      record: cluster:controlplane_topology:info
    - expr: sum by(mode) (cluster_infrastructure_topology)
      record: cluster:infrastructure_topology:info
