---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:35:50Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: kube-scheduler
    operation: Update
    time: "2026-01-28T10:24:12Z"
  name: kube-scheduler
  namespace: openshift-kube-scheduler
  resourceVersion: "34750"
  uid: 4ba53156-53b1-47e3-b18b-183a37f59d48
spec:
  acquireTime: "2026-01-28T09:44:20.009682Z"
  holderIdentity: ip-10-0-102-200_e40d8fa9-e6b7-405e-b188-8ebda888277c
  leaseDurationSeconds: 137
  leaseTransitions: 2
  renewTime: "2026-01-28T10:24:12.705006Z"
