---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVORENDQXh5Z0F3SUJBZ0lJY1NBYWhIL056TkF3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRCYUZ3MHlPREF4TWpnd09UTXdOREZhTUVFeFB6QTlCZ05WQkFNVE5tTnNkWE4wClpYSXRkbVZ5YzJsdmJpMXZjR1Z5WVhSdmNpNXZjR1Z1YzJocFpuUXRZMngxYzNSbGNpMTJaWEp6YVc5dUxuTjIKWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSjgybkppa2Radk93ci81Uy9oRApINlN4RS9rVTdxaTgzdEM2UTdYVHh5VzVPcm5zRnFsRDVnZTFVNDBDOWM4L0VBNEsxQ00zWGVDUG5QVGlNUUtoCjUyOGVNZGpxZThBTDU1UkFya044SXNhOFBCZHNYVDJ5RndjZFhnendUZ01wQlRBTGJhY3JtaTFCbVN3SVpPNSsKK1p1RStKaVU0UnQwRThTSzgwend0WHRxM0tSQnpVMVRGNVFsQ1UrdDNUdURxVkM2NzlPTkJRdjVtdHgxUGpUUwpGd1F5bFRUdHFCeFlMWTlvMys0ZlRsc2h6WGY5aTNPNlF2MGxqY0xsVHFYeEtrQytCZXhya1NEUEIzU3VjTEJDCkJjcXdGMVVjVnNJS2txL28rdmxIR2JOSmtkeGFoWUEzb0dpTlVPK1h2ZFBZL2g2d2NMT0tWRXNyVFBXNWhDUmUKU1k4Q0F3RUFBYU9DQVRrd2dnRTFNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRgpCUWNEQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNPRU9BWXRMVGVIUnN0UnU5ZEcrNThpZzJWCjRqQWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxNnpDQmlBWURWUjBSQklHQU1INkMKTm1Oc2RYTjBaWEl0ZG1WeWMybHZiaTF2Y0dWeVlYUnZjaTV2Y0dWdWMyaHBablF0WTJ4MWMzUmxjaTEyWlhKegphVzl1TG5OMlk0SkVZMngxYzNSbGNpMTJaWEp6YVc5dUxXOXdaWEpoZEc5eUxtOXdaVzV6YUdsbWRDMWpiSFZ6CmRHVnlMWFpsY25OcGIyNHVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dOUVlMS3dZQkJBR1NDQkZrQWdFRUpoTWsKTjJVNU5Ua3pPVGd0WldFeVppMDBZVFZqTFRoaVlUY3RPVFE0TVdOaE9HTTFPRFU1TUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQnIxSitMVmlQbXRqNHIwOTA4UXdBWU1kTURIYWNtTU5BQzZNcXdGMkRTRFlIc0t0RXdyc2lNCmRHVXg1UlBQWFhSTEpqK1pkZ0V2MlFaM0VBSjZQSW9uc3ZsSG5ISXo2UzhwSVpObmxnOHovbjlWSFMwWDZhOTEKZXFtd3FZSjVLVFpyR1dmbVkySG8xYnZ4cHk0MjBLcEtvQll3blJDZldmQzMybjF6b3hrRjF6NmZVVEdNTXRscApVRmNXOTAyNENzTWFZRCtScmJzMThwSHZYVUw5L3FxVHRManhCU0xuVXlzU1lnMkpkY1o4aHRONWtURWtJbUFYCm1LbFg4aStVME9oQWYvV1phaEw1SDR6UStlWjRUNkxtQmlIY1dPWjB0MkZEOTlJd05ScWNiK1M4NHg5eitvNXYKTjc0clBOQUJVbUpIUXhFNzhFc2QvZVpzU0dZL0gvTFEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/cluster-version-operator
        with hostname cluster-version-operator.openshift-cluster-version.svc and is
        annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        cluster-version-operator-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:41Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:30:41Z"
      service.beta.openshift.io/originating-service-name: cluster-version-operator
      service.beta.openshift.io/originating-service-uid: 7e959398-ea2f-4a5c-8ba7-9481ca8c5859
    creationTimestamp: "2026-01-28T09:30:42Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"7e959398-ea2f-4a5c-8ba7-9481ca8c5859"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:42Z"
    name: cluster-version-operator-serving-cert
    namespace: openshift-cluster-version
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: cluster-version-operator
      uid: 7e959398-ea2f-4a5c-8ba7-9481ca8c5859
    resourceVersion: "6657"
    uid: d71694ef-fd3b-4608-baf7-35a778ba3194
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "34858"
