---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2026-01-28T09:24:15Z"
  generation: 1
  managedFields:
  - apiVersion: flowcontrol.apiserver.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:apf.kubernetes.io/autoupdate-spec: {}
      f:spec:
        f:limited:
          .: {}
          f:lendablePercent: {}
          f:limitResponse:
            .: {}
            f:type: {}
          f:nominalConcurrencyShares: {}
        f:type: {}
    manager: api-priority-and-fairness-config-producer-v1
    operation: Update
    time: "2026-01-28T09:24:15Z"
  name: catch-all
  resourceVersion: "71"
  uid: 57144545-14ac-4389-ae22-cfd01cb9537d
spec:
  limited:
    lendablePercent: 0
    limitResponse:
      type: Reject
    nominalConcurrencyShares: 5
  type: Limited
status: {}
