---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2026-01-28T09:24:15Z"
  generation: 1
  managedFields:
  - apiVersion: flowcontrol.apiserver.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:apf.kubernetes.io/autoupdate-spec: {}
      f:spec:
        f:exempt:
          .: {}
          f:lendablePercent: {}
          f:nominalConcurrencyShares: {}
        f:type: {}
    manager: api-priority-and-fairness-config-producer-v1
    operation: Update
    time: "2026-01-28T09:24:15Z"
  name: exempt
  resourceVersion: "73"
  uid: 254479bc-3c95-4f61-b4b0-321f7e61b47e
spec:
  exempt:
    lendablePercent: 0
    nominalConcurrencyShares: 0
  type: Exempt
status: {}
