---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:32:04Z"
    creationTimestamp: "2026-01-28T09:26:12Z"
    labels:
      app: kube-apiserver-operator
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:32:04Z"
    name: metrics
    namespace: openshift-kube-apiserver-operator
    resourceVersion: "11023"
    uid: d16e2c38-a028-415f-90f3-342d91608c9f
  subsets:
  - addresses:
    - ip: 10.130.0.25
      nodeName: ip-10-0-108-54.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: kube-apiserver-operator-766b8bd8b7-6fdbx
        namespace: openshift-kube-apiserver-operator
        uid: 1abb5b69-d96b-4e2b-ab3b-8786c443357b
    ports:
    - name: https
      port: 8443
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "35081"
