---
apiVersion: apps/v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
    creationTimestamp: "2026-01-28T09:25:55Z"
    generation: 1
    labels:
      name: network-operator
    managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
          f:labels:
            .: {}
            f:name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:target.workload.openshift.io/management: {}
              f:labels:
                .: {}
                f:name: {}
            f:spec:
              f:affinity:
                .: {}
                f:podAntiAffinity:
                  .: {}
                  f:preferredDuringSchedulingIgnoredDuringExecution: {}
              f:containers:
                k:{"name":"network-operator"}:
                  .: {}
                  f:command: {}
                  f:env:
                    .: {}
                    k:{"name":"BOND_CNI_PLUGIN_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"CLI_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"CLOUD_NETWORK_CONFIG_CONTROLLER_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"CNI_PLUGINS_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"EGRESS_ROUTER_CNI_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"FRR_K8S_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KUBE_PROXY_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KUBE_RBAC_PROXY_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"MULTUS_ADMISSION_CONTROLLER_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"MULTUS_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"MULTUS_NETWORKPOLICY_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NETWORK_CHECK_SOURCE_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NETWORK_CHECK_TARGET_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NETWORK_METRICS_DAEMON_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NETWORK_OPERATOR_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NETWORKING_CONSOLE_PLUGIN_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OVN_CONTROLLER_INACTIVITY_PROBE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OVN_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OVN_NB_INACTIVITY_PROBE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OVN_NB_RAFT_ELECTION_TIMER"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OVN_NORTHD_PROBE_INTERVAL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OVN_SB_RAFT_ELECTION_TIMER"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POD_NAME"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:fieldRef: {}
                    k:{"name":"RELEASE_VERSION"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"ROUTE_OVERRRIDE_CNI_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"WHEREABOUTS_CNI_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":9104,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:hostPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources:
                    .: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/etc/kubernetes"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                      f:readOnly: {}
                    k:{"mountPath":"/var/run/secrets/serving-cert"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:hostNetwork: {}
              f:nodeSelector: {}
              f:priorityClassName: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext:
                .: {}
                f:runAsNonRoot: {}
                f:runAsUser: {}
              f:serviceAccount: {}
              f:serviceAccountName: {}
              f:terminationGracePeriodSeconds: {}
              f:tolerations: {}
              f:volumes:
                .: {}
                k:{"name":"host-etc-kube"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
                k:{"name":"metrics-tls"}:
                  .: {}
                  f:name: {}
                  f:secret:
                    .: {}
                    f:defaultMode: {}
                    f:optional: {}
                    f:secretName: {}
      manager: cluster-version-operator
      operation: Update
      time: "2026-01-28T09:25:55Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2026-01-28T09:31:41Z"
    name: network-operator
    namespace: openshift-network-operator
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      controller: true
      kind: ClusterVersion
      name: version
      uid: 0370d296-6904-481d-ab90-157c7e5b835a
    resourceVersion: "9454"
    uid: 6c6c4b09-2539-4cd6-9000-e22f0b6fc631
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        name: network-operator
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        annotations:
          target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        creationTimestamp: null
        labels:
          name: network-operator
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    name: network-operator
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - command:
          - /bin/bash
          - -c
          - |
            #!/bin/bash
            set -o allexport
            if [[ -f /etc/kubernetes/apiserver-url.env ]]; then
              source /etc/kubernetes/apiserver-url.env
            else
              echo "Error: /etc/kubernetes/apiserver-url.env is missing"
              exit 1
            fi
            exec /usr/bin/cluster-network-operator start --listen=0.0.0.0:9104
          env:
          - name: RELEASE_VERSION
            value: 4.20.0-0-2026-01-28-090915-test-ci-ln-vjb5l1t-latest
          - name: KUBE_PROXY_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:2740aca26596483ce9333bedeb9805a90efc614a54c671ed7cdf25967c88645d
          - name: KUBE_RBAC_PROXY_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:a0de83cf18d336c19ea214987e67e382cffab05022e12fce60349cc89644374b
          - name: MULTUS_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:0cca4df2e32bbccd8d4fbb9dfa9e5da38cce49566dbfdd95bfb29622cba642cd
          - name: MULTUS_ADMISSION_CONTROLLER_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:c745a7824df72a7a16acc1d384630cb7a5a317b2a4079ae053ecf4abce4785ea
          - name: CNI_PLUGINS_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:7e0645fdd4a85c0bfda5083073b9fb5a0510dae53714eefeee2c6ba91826b831
          - name: BOND_CNI_PLUGIN_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:454733fd181aace8613cae5f7cf9fcd2de5611445eeb0a78140e6ece467d123c
          - name: WHEREABOUTS_CNI_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:b76ef910c8a1cb86aa50b11f659bb7dd777fb2f506ca92861d804f0234bcd832
          - name: ROUTE_OVERRRIDE_CNI_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:5521bde2b6ea859e756b1e38fafd336461e31f852e9d702256343b5813bce97c
          - name: MULTUS_NETWORKPOLICY_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:3d19c464e79f0b99c0779dbfbe07f99a88d011a0b3447b5ffe46d840c4b8a8c7
          - name: OVN_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:d732505bbda1adfc700e58ea8b52de16c3e511aaeedc03c6d1b932057b9b3f49
          - name: OVN_NB_RAFT_ELECTION_TIMER
            value: "10"
          - name: OVN_SB_RAFT_ELECTION_TIMER
            value: "16"
          - name: OVN_NORTHD_PROBE_INTERVAL
            value: "10000"
          - name: OVN_CONTROLLER_INACTIVITY_PROBE
            value: "180000"
          - name: OVN_NB_INACTIVITY_PROBE
            value: "60000"
          - name: EGRESS_ROUTER_CNI_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:a91e3de8081f371c9ff9f2f16619d915621264378f0c861e2ba1366f10053cb1
          - name: NETWORK_METRICS_DAEMON_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:d9bfae1f007c39d04a73292907669a1c0eb274202324001dd9363a0586bef1bc
          - name: NETWORK_CHECK_SOURCE_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:96c9bdd179739c90f9361520b62eb77abd437b660682e9964960d59da029ea33
          - name: NETWORK_CHECK_TARGET_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:96c9bdd179739c90f9361520b62eb77abd437b660682e9964960d59da029ea33
          - name: NETWORK_OPERATOR_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:96c9bdd179739c90f9361520b62eb77abd437b660682e9964960d59da029ea33
          - name: CLOUD_NETWORK_CONFIG_CONTROLLER_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:433e71999e326ef1d70ba325ed777289659ab8f2b1b659a6906aae5f4b511482
          - name: CLI_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:e577dce25a9f06468c866700c8ff6d4122516ddbbd9995e5cf4ea1156d61988a
          - name: FRR_K8S_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:56484d46497186d098432fa3b8ac9727f37f2a86373d8f784aef18dc88cf3cda
          - name: NETWORKING_CONSOLE_PLUGIN_IMAGE
            value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:144be6c7447f775d70368a593faa4a06558619097b5c9162579c7bc0e58af2d4
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:96c9bdd179739c90f9361520b62eb77abd437b660682e9964960d59da029ea33
          imagePullPolicy: IfNotPresent
          name: network-operator
          ports:
          - containerPort: 9104
            hostPort: 9104
            name: cno
            protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
          - mountPath: /etc/kubernetes
            name: host-etc-kube
            readOnly: true
          - mountPath: /var/run/secrets/serving-cert
            name: metrics-tls
        dnsPolicy: ClusterFirst
        hostNetwork: true
        nodeSelector:
          node-role.kubernetes.io/master: ""
        priorityClassName: system-cluster-critical
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
        serviceAccount: cluster-network-operator
        serviceAccountName: cluster-network-operator
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/network-unavailable
          operator: Exists
        volumes:
        - hostPath:
            path: /etc/kubernetes
            type: Directory
          name: host-etc-kube
        - name: metrics-tls
          secret:
            defaultMode: 420
            optional: true
            secretName: metrics-tls
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-28T09:25:55Z"
      lastUpdateTime: "2026-01-28T09:25:55Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2026-01-28T09:25:55Z"
      lastUpdateTime: "2026-01-28T09:28:55Z"
      message: ReplicaSet "network-operator-6596f47f7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: DeploymentList
metadata:
  resourceVersion: "35153"
