---
apiVersion: batch/v1
items:
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    annotations:
      capability.openshift.io/name: OperatorLifecycleManager
      include.release.openshift.io/hypershift: "true"
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
    creationTimestamp: "2026-01-28T09:26:15Z"
    generation: 2
    labels:
      app: olm-collect-profiles
    managedFields:
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:capability.openshift.io/name: {}
            f:include.release.openshift.io/hypershift: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
          f:labels:
            .: {}
            f:app: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
        f:spec:
          f:concurrencyPolicy: {}
          f:failedJobsHistoryLimit: {}
          f:jobTemplate:
            f:spec:
              f:backoffLimit: {}
              f:completionMode: {}
              f:suspend: {}
              f:template:
                f:metadata:
                  f:annotations:
                    .: {}
                    f:openshift.io/required-scc: {}
                    f:target.workload.openshift.io/management: {}
                  f:labels:
                    .: {}
                    f:app: {}
                f:spec:
                  f:containers:
                    k:{"name":"collect-profiles"}:
                      .: {}
                      f:args: {}
                      f:command: {}
                      f:image: {}
                      f:imagePullPolicy: {}
                      f:name: {}
                      f:resources:
                        .: {}
                        f:requests:
                          .: {}
                          f:cpu: {}
                          f:memory: {}
                      f:securityContext:
                        .: {}
                        f:allowPrivilegeEscalation: {}
                        f:capabilities:
                          .: {}
                          f:drop: {}
                      f:terminationMessagePath: {}
                      f:terminationMessagePolicy: {}
                      f:volumeMounts:
                        .: {}
                        k:{"mountPath":"/etc/config"}:
                          .: {}
                          f:mountPath: {}
                          f:name: {}
                        k:{"mountPath":"/var/run/secrets/serving-cert"}:
                          .: {}
                          f:mountPath: {}
                          f:name: {}
                  f:dnsPolicy: {}
                  f:priorityClassName: {}
                  f:restartPolicy: {}
                  f:schedulerName: {}
                  f:securityContext:
                    .: {}
                    f:runAsNonRoot: {}
                    f:seccompProfile:
                      .: {}
                      f:type: {}
                  f:serviceAccount: {}
                  f:serviceAccountName: {}
                  f:terminationGracePeriodSeconds: {}
                  f:volumes:
                    .: {}
                    k:{"name":"config-volume"}:
                      .: {}
                      f:configMap:
                        .: {}
                        f:defaultMode: {}
                        f:name: {}
                      f:name: {}
                    k:{"name":"secret-volume"}:
                      .: {}
                      f:name: {}
                      f:secret:
                        .: {}
                        f:defaultMode: {}
                        f:secretName: {}
          f:schedule: {}
          f:successfulJobsHistoryLimit: {}
          f:suspend: {}
      manager: cluster-version-operator
      operation: Update
      time: "2026-01-28T09:27:11Z"
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:lastScheduleTime: {}
          f:lastSuccessfulTime: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2026-01-28T10:15:03Z"
    name: collect-profiles
    namespace: openshift-operator-lifecycle-manager
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      controller: true
      kind: ClusterVersion
      name: version
      uid: 0370d296-6904-481d-ab90-157c7e5b835a
    resourceVersion: "32740"
    uid: 2c6bbdc0-6214-4f7a-88e9-dde86ddf66d3
  spec:
    concurrencyPolicy: Replace
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        backoffLimit: 6
        completionMode: NonIndexed
        suspend: false
        template:
          metadata:
            annotations:
              openshift.io/required-scc: restricted-v2
              target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
            creationTimestamp: null
            labels:
              app: olm-collect-profiles
          spec:
            containers:
            - args:
              - -n
              - openshift-operator-lifecycle-manager
              - --config-mount-path
              - /etc/config
              - --cert-mount-path
              - /var/run/secrets/serving-cert
              - olm-operator-heap-:https://olm-operator-metrics:8443/debug/pprof/heap
              - catalog-operator-heap-:https://catalog-operator-metrics:8443/debug/pprof/heap
              command:
              - bin/collect-profiles
              image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:941c71daa16180c08c62cb401a0337fdb7931e0bbf363172723eede6439b6439
              imagePullPolicy: IfNotPresent
              name: collect-profiles
              resources:
                requests:
                  cpu: 10m
                  memory: 80Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: FallbackToLogsOnError
              volumeMounts:
              - mountPath: /etc/config
                name: config-volume
              - mountPath: /var/run/secrets/serving-cert
                name: secret-volume
            dnsPolicy: ClusterFirst
            priorityClassName: openshift-user-critical
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext:
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            serviceAccount: collect-profiles
            serviceAccountName: collect-profiles
            terminationGracePeriodSeconds: 30
            volumes:
            - configMap:
                defaultMode: 420
                name: collect-profiles-config
              name: config-volume
            - name: secret-volume
              secret:
                defaultMode: 420
                secretName: pprof-cert
    schedule: '*/15 * * * *'
    successfulJobsHistoryLimit: 3
    suspend: false
  status:
    lastScheduleTime: "2026-01-28T10:15:00Z"
    lastSuccessfulTime: "2026-01-28T10:15:03Z"
kind: CronJobList
metadata:
  resourceVersion: "35167"
