---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVSakNDQXk2Z0F3SUJBZ0lJVmwvRUlUZ3M4Tmt3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE14TkRSYUZ3MHlPREF4TWpnd09UTXhORFZhTUN3eEtqQW9CZ05WQkFNTUlTb3VaWGh3CmIzSjBaWEl1YjNCbGJuTm9hV1owTFdsdWMybG5hSFJ6TG5OMll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFMQ28reDBvaFVoUFZlbEtxU1ZMaldpSjRUNmVja1FvaExBSTN6RVlsTVNibmNYMwpRU0ovQnFUQWQ4a3VvZzVSZTNPdE1JRHhQcG95bkJxM3d3UmdNV3oyME43T0w0OWdGMkJvTFkzOHNnZFB5ZVNQCnpOSUdtdlEwOFdtN2xobHZCcmhXQmh5UWQvaGJRRlJ6aDRuTERnTlYwTUJESmF0L3pseGMvWkRVaWVVUE1nVkcKYzZLcWlpclBNNjFPZTU3a3RucDRqQVh4QWN6MERpNnNwQmkyR3d4eDVNcjdtN2gyUzJBZ0g0TDM0dlYyRlZCQwpkVEVacEo0dlVCamFxamlVVEEwcllQc0tXbHBqVWtCRWF2bGYyQXNtb3d4b3p3dXpDdktSa0VNayswaVg4bzlVCkd2bmpQRW5HNkMvdlQvZUpNYmJzZEZBSEkybEFCVGJKZytWRjVuTUNBd0VBQWFPQ0FXQXdnZ0ZjTUE0R0ExVWQKRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQU1CZ05WSFJNQkFmOEVBakFBTUIwRwpBMVVkRGdRV0JCUXNwTFpCWHU4MmNQMmt3ZVBsU3dubVZHUXlHakFmQmdOVkhTTUVHREFXZ0JTWXdYNVlWVnZpCm9SOTgram85MnFYQXJUejE2ekNCcndZRFZSMFJCSUduTUlHa2dpRXFMbVY0Y0c5eWRHVnlMbTl3Wlc1emFHbG0KZEMxcGJuTnBaMmgwY3k1emRtT0NMeW91Wlhod2IzSjBaWEl1YjNCbGJuTm9hV1owTFdsdWMybG5hSFJ6TG5OMgpZeTVqYkhWemRHVnlMbXh2WTJGc2doOWxlSEJ2Y25SbGNpNXZjR1Z1YzJocFpuUXRhVzV6YVdkb2RITXVjM1pqCmdpMWxlSEJ2Y25SbGNpNXZjR1Z1YzJocFpuUXRhVzV6YVdkb2RITXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3cKTlFZTEt3WUJCQUdTQ0JGa0FnRUVKaE1rTURJNVkyTmxNV0l0WlRVek1DMDBZelV3TFdGa1pHTXROelZtTmpkaApNV0ZoWkRZeU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmY5RG1DSGt0eExkMHRTSGJmeVBUN1l1Mi8zVGNvCit0UERCRUdtTXhHV1FDWnhkbXZJN1p6SFNXL1p0YVBFWmd0ZzdHNDBrMmFLOHFLSVYrbE1BTFNRTUVseGdvbzUKK0syS0R3QjZkM0R2eThRa0UrVlBXOTFaUkptRElzNzloUldxb2hIOTFneXlTcGY4QkdESTNIQ1p3anhwRm1jVApCeVNmbDhMa3B5WDN0bjkrVk4yeGFjOE1GMU93b3ZIenQ0QzBMQkpkZDNsT3hVUDFOTDYrcTB1aHBQcDdkczM3CkVEVzNmWlRsZU1KQkZCZ1lHQnNjeUpwdDRJQm83Q2hLWnhzc3hnbUEva3pyR3VDZjFWQUU0cEo5ZElHT2dsU3IKRHNPKy8xVHJLQUlHWTNrcDg2aFhYZWRTS0s1ZmtrU2hpVVAxN3RSRDE0eHh3SE45dkhrUWcxMzkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/exporter with hostname
        exporter.openshift-insights.svc and is annotated to the service with annotating
        a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        insights-runtime-extractor-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:31:45Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:31:45Z"
      service.beta.openshift.io/originating-service-name: exporter
      service.beta.openshift.io/originating-service-uid: 029cce1b-e530-4c50-addc-75f67a1aad62
    creationTimestamp: "2026-01-28T09:31:45Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"029cce1b-e530-4c50-addc-75f67a1aad62"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:31:45Z"
    name: insights-runtime-extractor-tls
    namespace: openshift-insights
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: exporter
      uid: 029cce1b-e530-4c50-addc-75f67a1aad62
    resourceVersion: "9559"
    uid: 509c2962-f9e8-47d2-90e2-f563035b71a6
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ2akNDQXRLZ0F3SUJBZ0lJUUVpNkMrUmR2YTR3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRSYUZ3MHlPREF4TWpnd09UTXdORFZhTUNreEp6QWxCZ05WQkFNVEhtMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMV2x1YzJsbmFIUnpMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQU1ETlg0RE42Y2pULzhPeHhscFVLc1lJTkVoaXhRUkxHWDh1NXU5QTlHbXFGWnJNZ3pFVwo3bmtNd2JXM3dTcmZTb0FFTnd0aVI1UDRTKzFuYTZxZXBRUjhJTzIrNjg3aExvWmZBcys0c2hnNzBYVjJzWmVCCnJhY1ZkRXN3Zko5cXI5dGtLYkJMbkdBeVFyUUk2NkQwMXJ0cUVwcnlSSFpiWHowUnFaMmNmSzJVb2pZbi9HcXkKN3RCcnZFNUFselpEc21US050RGx5ZlE3UFVKd3hkVTR6K0dSeW8xcWxnRyt5cmdSa1RCTllVMmFabWpocllOYgpDZ1czY3ZjWFdRSzFzQkNaajdTN29sYUU5VG1CYVBZTlcvS2hpc3dCQThadG9iU29TSW1aaW9CNnFCYS9YbVYzCncwL0xYdXBCUkFxY3ZPZTRGOWk5Q24rdDYwcGZGeldLREI4Q0F3RUFBYU9DQVFjd2dnRURNQTRHQTFVZER3RUIKL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJTVkhzd0VsWDl2Rk5CaWx6YjQrQmZkVTEyU2JUQWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4CitqbzkycVhBclR6MTZ6QlhCZ05WSFJFRVVEQk9naDV0WlhSeWFXTnpMbTl3Wlc1emFHbG1kQzFwYm5OcFoyaDAKY3k1emRtT0NMRzFsZEhKcFkzTXViM0JsYm5Ob2FXWjBMV2x1YzJsbmFIUnpMbk4yWXk1amJIVnpkR1Z5TG14dgpZMkZzTURVR0N5c0dBUVFCa2dnUlpBSUJCQ1lUSkRnNVlXUTBOR0ppTFdJMU1qZ3ROR1kyTkMwNU16UmhMVE0zCk0yTTNNbVUzTTJabE9UQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF1Rkp0R01YQTYzSlJFbXZjdWJBWGpid24KVlU2bndZRGtDM0U1Zzcxa2p2UTFTVW92eGpySlpRSFJuSktRWGlaZXZoUlRLUnJkL1R4L3dUNDRRbW1mVFBFQQpSVm5xWm9ud2paOE5NU0NkQjRXV2lmbjJuSGM2eDhzeC9Udk80cjZuV3J1OVRzNVNienJDcHNhMUhtZTNrcC91CnRseFhST1BlVGorc0VaMjZMcG1aN0lWOTA1eXZ6dGU5RCtiWlpIYm84cWFZTTRtSllKTHZOVmdONkpNVjVyS0oKa0lEOGFzUUt4QkphQktHcmdRc3FEZ3hYVE9PTG1tbUxqT0hmTkRBQzlYbFp6NktUdVd6QlI4WnBsdCtXV0JsLwp6UzNrOHpPVU1WOXl2cG5Da1hscXcxck91cUJ5N3VieXlZTFdlTzlzeVBXOGdyeEljeXN6WC9VUmdDR2luZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-insights.svc and is annotated to the service with annotating
        a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        openshift-insights-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:45Z"
      service.alpha.openshift.io/originating-service-name: metrics
      service.alpha.openshift.io/originating-service-uid: 89ad44bb-b528-4f64-934a-373c72e73fe9
      service.beta.openshift.io/expiry: "2028-01-28T09:30:45Z"
    creationTimestamp: "2026-01-28T09:30:46Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"89ad44bb-b528-4f64-934a-373c72e73fe9"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:46Z"
    name: openshift-insights-serving-cert
    namespace: openshift-insights
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: 89ad44bb-b528-4f64-934a-373c72e73fe9
    resourceVersion: "6941"
    uid: 94973972-4b7b-48c8-b148-8e65d04fbcc7
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35068"
