---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVhVENDQTFHZ0F3SUJBZ0lJZFNYbFV1SlplNGN3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TlROYUZ3MHlPREF4TWpnd09UTXdOVFJhTURNeE1UQXZCZ05WQkFNTUtDb3ViV1YwCmNtbGpjeTV2Y0dWdWMyaHBablF0Ym1WMGQyOXlheTF2Y0dWeVlYUnZjaTV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEUGhOVEhKakhYR3Vuc3Ziai9WMDNIMVFrWXhCRnRucjdGN2JjMAo5Mit4YkJ2Y0RvU3QrZm5yZzJGZGphRHMzKzVDcXdDNmxjM21GZmtUQlF6TVdFeFhrRXp1ZVhraFI5VXp4WDJDCm9DdEF5YmY1WW5RV1VvRHZMb0liWXJ1QnlsNXY2L2hLMzc5WWcwMThyakFSS1UxNHJoM21zREJkeGJTeUZYSFMKSHJKWFRsRThHc05pcFpKNU9yZlBRcWFPQ0tYQzIza1dFb1ZlWkYzNHA2YUg5Q0U1ZTdvN2NRNVNPY3kwc2sxUQphU2NJZWtJSVRmclRuaFNWWElFcGR2ZjBscllZb2JpN0FnZS9TOURGcWE2bHBONjgvb1BvOE1JdG9NMzhrbUcxCnluLzc4M29jdHB6UVd3SUI2dUE4am4rTGI4b1p5L2dYN3lyclhML28zVFo2ZDUxMUFnTUJBQUdqZ2dGOE1JSUIKZURBT0JnTlZIUThCQWY4RUJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFILwpCQUl3QURBZEJnTlZIUTRFRmdRVW5RMUI0dFBBaUtGamt0SUt3ektvUTNIWUpTSXdId1lEVlIwakJCZ3dGb0FVCm1NRitXRlZiNHFFZmZQbzZQZHFsd0swODllc3dnY3NHQTFVZEVRU0J3ekNCd0lJb0tpNXRaWFJ5YVdOekxtOXcKWlc1emFHbG1kQzF1WlhSM2IzSnJMVzl3WlhKaGRHOXlMbk4yWTRJMktpNXRaWFJ5YVdOekxtOXdaVzV6YUdsbQpkQzF1WlhSM2IzSnJMVzl3WlhKaGRHOXlMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNnaVp0WlhSeWFXTnpMbTl3ClpXNXphR2xtZEMxdVpYUjNiM0pyTFc5d1pYSmhkRzl5TG5OMlk0STBiV1YwY21samN5NXZjR1Z1YzJocFpuUXQKYm1WMGQyOXlheTF2Y0dWeVlYUnZjaTV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREExQmdzckJnRUVBWklJRVdRQwpBUVFtRXlSaE1qQmhNelppTkMweE56VXlMVFF4WWpJdE9ESXdaUzB5WWpBM05Ua3pZMlF5TXprd0RRWUpLb1pJCmh2Y05BUUVMQlFBRGdnRUJBSTFLRHVmaElSVG51RWZ5OUlZTUdrRlNxRXFKUkh0RUZtUDM2RUlYZ1Y3OHJveXkKNkNCVG80dnBta3BxVHBoNWlDRHBpTFVGWFN4UGY4UXN1NVFNSHc4bEJwMTJGZFhDaEg4dmxrUUZvNFYyWUJUTApMeDhyQjQ5eWQ2cHVoK1BkaHoyWWlxK3NlUEM2ZFowQW9jZXRXZWVybjRRY1J1ek9yaVhhdlBvRldhTkNhS1EzCmp3OGZvZjlDdEk0bHlwK3NWeDNvbmxKekozZXN4S0xBZ2txNlJEWkF2S2tnZGlyMmxTZmpEdlI3VHJPaUlyMUcKLzhxMU1heTNveW9yN3hPR3MyQUhGRTRFTG0wY05sWHVTTGVIRU9KMjhMcW80SndJVGV5TmJCLy9DTlQ5ZXJHbgpkK3ltYzNuK3BNNHFzd2NqY3FFSHhZVERTUmRFaUFmTzREWEdIdkU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-network-operator.svc and is annotated to the service with
        annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        metrics-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:54Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:30:54Z"
      service.beta.openshift.io/originating-service-name: metrics
      service.beta.openshift.io/originating-service-uid: a20a36b4-1752-41b2-820e-2b07593cd239
    creationTimestamp: "2026-01-28T09:30:55Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a20a36b4-1752-41b2-820e-2b07593cd239"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:55Z"
    name: metrics-tls
    namespace: openshift-network-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: a20a36b4-1752-41b2-820e-2b07593cd239
    resourceVersion: "7465"
    uid: 0c919217-491f-4d20-a450-39d1543796b0
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35155"
