---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVDRENDQXZDZ0F3SUJBZ0lJUXl5YWw4RDExY2t3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpsYUZ3MHlPREF4TWpnd09UTXdOREJhTURNeE1UQXZCZ05WQkFNVEtHMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMV0Z3YVhObGNuWmxjaTF2Y0dWeVlYUnZjaTV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEaGdRRm1XS2xrZzViVVoyOEMrR0tyR0RPK2tuRmZyVUxIUGV5Kwo2d2xjSXUxaU9seGFXNXpucjg3N1BtaWQwY2FzT05kYUdBdFB0Mjl1OWpqaXZadEV6VVlqTTZFQlhQYVlmTDljClBCUUx3K3JoVnJiMTRrS2ptVzVFYVk2ZEFJcjU3dkVmTFU1NlhPM0pFM1RLZU1iaGFucGRCSXM3bEpRZnNEeWgKaXJQY0RGMmh3MFVwd0NvTmZ3SWlRcnZ6WUdudGtQNFhMUm4yUzFhYitKQkdrakdLbTdCSUJlalFZcXZ1czh2ZwprRnJjQUU4TTZnRTFzZTEybWxXNmlLVjQwT2hlU1E4ZG5ONk9qZWhpMzVZMVNEb29tamhBano4cFJibm0zV0doCkZXVGhjQ3FLRVg2Zm5Mb2t0eVlJOG5TeDRTd3VWVDVPZzd5ODkvNFFtMkpIbm9WUkFnTUJBQUdqZ2dFYk1JSUIKRnpBT0JnTlZIUThCQWY4RUJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFILwpCQUl3QURBZEJnTlZIUTRFRmdRVTZXek1NWG9UeVZYdkFGT29LcU5OSERFaXVvSXdId1lEVlIwakJCZ3dGb0FVCm1NRitXRlZiNHFFZmZQbzZQZHFsd0swODllc3dhd1lEVlIwUkJHUXdZb0lvYldWMGNtbGpjeTV2Y0dWdWMyaHAKWm5RdFlYQnBjMlZ5ZG1WeUxXOXdaWEpoZEc5eUxuTjJZNEkyYldWMGNtbGpjeTV2Y0dWdWMyaHBablF0WVhCcApjMlZ5ZG1WeUxXOXdaWEpoZEc5eUxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01EVUdDeXNHQVFRQmtnZ1JaQUlCCkJDWVRKR0l3Tm1FeE9HRTVMVEJrTjJZdE5ERTVZeTFoTVRCaUxUbGxNVFprWlRjMFpXUmxZakFOQmdrcWhraUcKOXcwQkFRc0ZBQU9DQVFFQUxZYlNiTk81eTNwWkRpZG5nTXVOSU16elFCaXB4cHZpYlRhb0FJd2xkNHNORUd6SgpPTzNBQjNDM3d2eUFzbUVaczNDaUpXL2tiRXFySXd1Si84WUxrOUtTZzVnTlRRNStXOHhhSDBvcDdESS80cVVECjBFOVJiblFWWHp0SWVqWEgwY1hha3ByUVlkY2lJWjdZajF0VytOVSs2R2FTTGJHRkIvMmNoZjdVVnJibHN3L3EKVzFuT1JFSnhLQlVtSnVzeHEweGthWVk1MkMwYTF1dmJXWktqbFZ6M1ljZVdxNTRSNUkyb0M3NXZxa1EwSzJlWQpKTm1JOEQrR0U2YnNGc2pqdUxUak1SWk42S2NqVlAxYkNFTGorOHZDOGg5RVZINzJjL2J6MzAyRE1Da3ZYTDE3CnM3eUlQYkhReWtTUlBFbENRTGg3anAwNmtYeUZBeTZqSnFUbm1nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-apiserver-operator.svc and is annotated to the service with
        annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        openshift-apiserver-operator-serving-cert''. The certificate is valid for
        2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:40Z"
      service.alpha.openshift.io/originating-service-name: metrics
      service.alpha.openshift.io/originating-service-uid: b06a18a9-0d7f-419c-a10b-9e16de74edeb
      service.beta.openshift.io/expiry: "2028-01-28T09:30:40Z"
    creationTimestamp: "2026-01-28T09:30:41Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"b06a18a9-0d7f-419c-a10b-9e16de74edeb"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:41Z"
    name: openshift-apiserver-operator-serving-cert
    namespace: openshift-apiserver-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: b06a18a9-0d7f-419c-a10b-9e16de74edeb
    resourceVersion: "6599"
    uid: b6c1f5bc-5e63-4f43-b9b8-68e5198af8f1
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35159"
