---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:31:56Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: cluster-image-registry-operator
    operation: Update
    time: "2026-01-28T10:24:22Z"
  name: openshift-master-controllers
  namespace: openshift-image-registry
  resourceVersion: "34788"
  uid: 033229d9-1f7b-4ba4-b2b1-b7cc77ef6c0d
spec:
  acquireTime: "2026-01-28T09:31:56.034158Z"
  holderIdentity: cluster-image-registry-operator-66fd95cf54-qq4b6_19d19e14-89fc-4740-a243-f99d8e3f81b3
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:22.896494Z"
