---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpDZ0F3SUJBZ0lJUnByV0xoZU9FTmd3RFFZSktvWklodmNOQVFFTEJRQXdNREV1TUN3R0ExVUUKQXd3bGIzQmxibk5vYVdaMExXVjBZMlJmWlhSalpDMXphV2R1WlhKQU1UYzJPVFU1TWpFNU5UQWVGdzB5TmpBeApNamd3T1RJek1UVmFGdzB6TVRBeE1qY3dPVEl6TVRWYU1FQXhLREFTQmdOVkJBb1RDMlYwWTJRdFkyeHBaVzUwCk1CSUdBMVVFQ2hNTGMzbHpkR1Z0T21WMFkyUXhGREFTQmdOVkJBTVRDMlYwWTJRdFkyeHBaVzUwTUlJQklqQU4KQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcjBFd1R6a0Q1bUZNTy9yTWlCZXhVUGlDbSsycgp4TEJGVVQ5bHBGazFVNnE1SFZDKzVyMkZDYy9HM0lyVFEvZWZOM0YzWTlZU1dQU2xjVXBzMHFoYm1EN0tWZmJ4Cmd4djRBNXNuRlkxSWdsMWRDZmRPUjR1NS9BckMyb3E5N3FnVHk1ZU5TbzNCd0xRVDlwNmlrUjRsdnkzZkFxY0IKU3FOM1JQNzBKV0txNU1HUWxUUlNrSE5oc08ybWZtblFmSmUyVGhNUnZOSDdpNDI0Tk40R095SnFoU3JhSTY1aAp4b21QeU1KOU9laCtpRTV0Y3QxaWpLcFpUQmYzUC9KK2N2WXBqY2dTL3UwOGxpMk1NWi9jMkh0b1hHaE9vbE9yCkovUDVWemlySlF4Nk5nVGV1bnNDcGhOaXF4WXViSEpWU2loc29jcTFjdGVaZW9pWXVLUHN6ZFVKalFJREFRQUIKbzFZd1ZEQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3SXdEQVlEVlIwVApBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlM5bmEwK3h0QTE2cW5aT2E3cVQ2bk0yNVlzUVRBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFUQ0ozWDBEd2NGNE5aTTAzTnVtWkYzSUpTNSs0bzh5ckpZY0cvMEE5cmFWdXVqWUkKbEFGbnp4ZVh3ZktYQS9mdGtWVXdGWHN4R0NSOTdlZjI4TXRZZEV1Ky9DTTh1OFA4TEp1dzFlUGcwVlJDYkIzcgpZSlVsdEZTbUkvMmRUd1BBTG14bStvOWRmU0NUaUR2WXV4NTZ0Ry82UElLM01YdnJndXEyL0szNlpuc2lVT1FICkxmZXJoMkJMYk8vQVhvZEYrQkZlTHdTY2ZGbStkSlNDSkpvYnhQRDZxRTVCM3RjbkUwaUl0ZVpqVWtiak5ocUoKZGVFeFBhaTd1VThrZm9TMko1OXU4U3psUTNjc2hKR1pOTWloSVMwT0UybjVmWE1JVnVFclNDY3FWaE0reVgwOApmZkhFdDhwVUNEc2hLcFFOQW5adlZHejFhNTl2QVZ2MG93WTVQZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-issuer: openshift-etcd_etcd-signer@1769592195
      auth.openshift.io/certificate-not-after: "2031-01-27T09:23:15Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:23:15Z"
      certificates.openshift.io/refresh-period: 36792h0m0s
      openshift.io/description: Client certificate for apiserver, cluster-etcd-operator
        and etcdctl to reach etcd. Generated by cluster-etcd-operator for etcd. This
        certificate is valid for 1825 days and starts refreshing after 1533 days.
      openshift.io/owning-component: etcd
    creationTimestamp: "2026-01-28T09:30:44Z"
    labels:
      auth.openshift.io/managed-certificate-type: target
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:certificates.openshift.io/refresh-period: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
          f:labels:
            .: {}
            f:auth.openshift.io/managed-certificate-type: {}
        f:type: {}
      manager: cluster-openshift-apiserver-operator
      operation: Update
      time: "2026-01-28T09:30:44Z"
    name: etcd-client
    namespace: openshift-apiserver
    resourceVersion: "6793"
    uid: 60161105-3dc7-4842-9c23-0aea23f34b12
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ0RENDQXNpZ0F3SUJBZ0lJQXVFZksvRzdCUk13RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpsYUZ3MHlPREF4TWpnd09UTXdOREJhTUNZeEpEQWlCZ05WQkFNVEcyRndhUzV2CmNHVnVjMmhwWm5RdFlYQnBjMlZ5ZG1WeUxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBS2QvbUFXNURqeW4yY083cVFxQjloUnN1MGFuVDV1ODhkcFdhUmdzWE1Mc0lOQ2h0VW44U3RiWApqaE42YXJmZmJCcGIxTzRjUktWRjJnY1BvU0N3MklBUllaemQySk1OVktRMjBsRFZGWWNidU5TTjlSOHd6b0VlCm9uRFRNeVNSSEdUS3dJOVFId3cwbGtIR3UwcitXRWg4VWVnQ3gveVFmZUpER2hZajVMYlczR2NNbi9IZC9MUkQKT0sxU1VKYTF3d29BRitPbUVLdlJmNGhhWkRaNWtyTTRoTTBodFZHQ3ZCVjRKQ0lnbFVsV0ZZQUtpQ2pvK1BjcwpLd00vRCsvdmZ5R2dmcEJmQnNpcE5HZ2NGREsvaGNFenM0MFlDSm1vMjVUTkVPRmxNd3U4L0FRdGdMU2hZMWpUCmJBOFdhSHVFbC9lakFlTUlJYVZUVUU0R1lZdlRrZThDQXdFQUFhT0NBUUF3Z2Ywd0RnWURWUjBQQVFIL0JBUUQKQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpGUDljNm1aMW53VWwzZFlQRDdOMEZEMkFIS3JPTUI4R0ExVWRJd1FZTUJhQUZKakJmbGhWVytLaEgzejZPajNhCnBjQ3RQUFhyTUZFR0ExVWRFUVJLTUVpQ0cyRndhUzV2Y0dWdWMyaHBablF0WVhCcGMyVnlkbVZ5TG5OMlk0SXAKWVhCcExtOXdaVzV6YUdsbWRDMWhjR2x6WlhKMlpYSXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dOUVlMS3dZQgpCQUdTQ0JGa0FnRUVKaE1rWkdReE5XWmxOek10T1RCbVppMDBaREJpTFRrMU56RXRaVE0zT1RJMU5UVmlaVFprCk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnF3SGNGWnUwZy9DczNUdWo5VGhVVUE4TlVLNVQ4N0hhM2FtcDkKWkVSNDBsWjI1bXBZc1RpTG5DZktvL0JiVDBhNGp5c21VeFdLaWQ1SlpsakZIRUJocmNIT2JwZFNEaHBoTVlSZQovMFN5K2JBbDRnOGQ2TjF4VG4vZkxpS0FYRjBGUXJGWEVtc01GQVZBa05Va1pUOGFFMmM4bUlWTlhKKzJaK0U2CjV1Y1FNWUNxSFFGNHFNSEdQa2pMVU85cDNERHJpRDBrVWQ2cm5oTVl3K0I2SzBLT21HM0gyaHFualdPYUM0TmYKU1Y2YjRJbnZYenZKdmJNb2VMejJtbStjMDVUNFUxUHZOdERPby9HbkM3bkU1WDRJZ3FxRXNHbzFzS2JrK1NBawpiWUdPbFhzTnMzVEErbTFRUjdBckxkUjFWM0l2dmhIaXFwNW4vSjNhekJ3L0VyMFAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/api with hostname api.openshift-apiserver.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:40Z"
      service.alpha.openshift.io/originating-service-name: api
      service.alpha.openshift.io/originating-service-uid: dd15fe73-90ff-4d0b-9571-e3792555be6d
      service.beta.openshift.io/expiry: "2028-01-28T09:30:40Z"
    creationTimestamp: "2026-01-28T09:30:40Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"dd15fe73-90ff-4d0b-9571-e3792555be6d"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:40Z"
    name: serving-cert
    namespace: openshift-apiserver
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: api
      uid: dd15fe73-90ff-4d0b-9571-e3792555be6d
    resourceVersion: "6498"
    uid: 61b7be55-cb89-4cb6-ab44-168892e7d5aa
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35159"
