---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:32:49Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: machine-healthcheck
    operation: Update
    time: "2026-01-28T10:24:24Z"
  name: cluster-api-provider-healthcheck-leader
  namespace: openshift-machine-api
  resourceVersion: "34799"
  uid: c7966250-5bb6-437c-927d-e355178bd054
spec:
  acquireTime: "2026-01-28T09:32:49.298068Z"
  holderIdentity: machine-api-controllers-67dcb4566c-m4pg8_75b71ca8-5383-49d3-b351-99c37babb0d4
  leaseDurationSeconds: 120
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:24.222932Z"
