---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:32:48Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: machine-controller-manager
    operation: Update
    time: "2026-01-28T10:24:14Z"
  name: cluster-api-provider-aws-leader
  namespace: openshift-machine-api
  resourceVersion: "34763"
  uid: a48d57b0-4043-4a69-8693-a6ee60b4d758
spec:
  acquireTime: "2026-01-28T09:32:48.566742Z"
  holderIdentity: machine-api-controllers-67dcb4566c-m4pg8_2783646c-1118-4d2f-ab94-7f36cce37c73
  leaseDurationSeconds: 120
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:14.704195Z"
