---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:31:55Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: cluster-baremetal-operator
    operation: Update
    time: "2026-01-28T10:24:22Z"
  name: cluster-baremetal-operator
  namespace: openshift-machine-api
  resourceVersion: "34789"
  uid: 3e64f439-f2bc-4014-b8e7-2b7132fc280d
spec:
  acquireTime: "2026-01-28T09:31:55.996510Z"
  holderIdentity: cluster-baremetal-operator-d6d4db7c7-jltnv_25775552-bcac-449a-b181-872163a60b27
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:22.910403Z"
