---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:31:52Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: manager
    operation: Update
    time: "2026-01-28T10:24:24Z"
  name: control-plane-machine-set-leader
  namespace: openshift-machine-api
  resourceVersion: "34803"
  uid: 49c79f77-602b-40eb-beb3-1b4692714c17
spec:
  acquireTime: "2026-01-28T09:31:52.453750Z"
  holderIdentity: control-plane-machine-set-operator-6984f87f6d-bgmkr_f66affab-ad6c-45a0-8506-45758a81657b
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:24.661643Z"
