---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:31:57Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: machine-api-operator
    operation: Update
    time: "2026-01-28T10:24:24Z"
  name: machine-api-operator
  namespace: openshift-machine-api
  resourceVersion: "34800"
  uid: 201e0b25-d84d-4995-bc36-c58369181e2d
spec:
  acquireTime: "2026-01-28T09:31:57.422656Z"
  holderIdentity: machine-api-operator-dbc848f6b-zd76d_1f82aa38-64e9-478f-922e-42beee019487
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:24.301522Z"
