---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:33:01Z"
    creationTimestamp: "2026-01-28T09:31:12Z"
    labels:
      app: aws-ebs-csi-driver-controller-metrics
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:33:01Z"
    name: aws-ebs-csi-driver-controller-metrics
    namespace: openshift-cluster-csi-drivers
    resourceVersion: "12442"
    uid: ffa77cf2-ec3e-4f33-b441-818a649dcbd2
  subsets:
  - addresses:
    - ip: 10.128.0.14
      nodeName: ip-10-0-3-203.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: aws-ebs-csi-driver-controller-5cbc97cfdb-pct52
        namespace: openshift-cluster-csi-drivers
        uid: a42ac734-4359-4bff-9838-cddee313d9bd
    - ip: 10.130.0.49
      nodeName: ip-10-0-108-54.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: aws-ebs-csi-driver-controller-5cbc97cfdb-cf4f6
        namespace: openshift-cluster-csi-drivers
        uid: 46c9914e-ca62-407a-876b-0ad029b0285f
    ports:
    - name: attacher-m
      port: 9203
      protocol: TCP
    - name: snapshotter-m
      port: 9205
      protocol: TCP
    - name: provisioner-m
      port: 9202
      protocol: TCP
    - name: driver-m
      port: 9201
      protocol: TCP
    - name: resizer-m
      port: 9204
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "35173"
