---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVhRENDQTFDZ0F3SUJBZ0lJWEpwRENreXhoeUF3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE14TVRKYUZ3MHlPREF4TWpnd09UTXhNVE5hTUZJeFVEQk9CZ05WQkFNVFIyRjNjeTFsClluTXRZM05wTFdSeWFYWmxjaTFqYjI1MGNtOXNiR1Z5TFcxbGRISnBZM011YjNCbGJuTm9hV1owTFdOc2RYTjAKWlhJdFkzTnBMV1J5YVhabGNuTXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBckwyQitmNnB4a2g4S3NOdHlaYmxlazRiL2tDVTlaZFN6WUJjcHdWVC95SVBoNzF2SHhzUmlKQWZEVjllCjg3YnBIT1pRaVJtS1B5Y0FiTE5mQWd6YWp0NWtQcjg2NXhhN1hPYlJXUnEzY2p3SVJ5cUlUVTlaQXMySnZINHAKRUhKOEVxUjAzRlJhUHBKRmpyMm1kRzVVZHRXMVBDL21CL3lpVHZaUnRraWF0S0NYVnNRZWE3aFZSTm9Oc0hMVgo4aHZGU3ZJazROVTVLcTVZM053SDJBaUs2a2w3VWlmYUZ6cURIVDBpbkdxdVNJcFFtcDQ3WjZaTFU5SkVEeEkrCllCekpFUlM3Q21vTEdnNDJuazYxT3BmLzFUaG4zazYxVTQzemViSzI5VkVBalZ6ZUFmMzQ3bDhEaXVjRENuNXEKbndSdFk4cnRpNmpyZ0NucUJUV3Z0VkwxWndJREFRQUJvNElCWERDQ0FWZ3dEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGR3ZhCmpva0hic25KTDMwOTFaZ2xMYVpOeXU1c01COEdBMVVkSXdRWU1CYUFGSmpCZmxoVlcrS2hIM3o2T2ozYXBjQ3QKUFBYck1JR3JCZ05WSFJFRWdhTXdnYUNDUjJGM2N5MWxZbk10WTNOcExXUnlhWFpsY2kxamIyNTBjbTlzYkdWeQpMVzFsZEhKcFkzTXViM0JsYm5Ob2FXWjBMV05zZFhOMFpYSXRZM05wTFdSeWFYWmxjbk11YzNaamdsVmhkM010ClpXSnpMV056YVMxa2NtbDJaWEl0WTI5dWRISnZiR3hsY2kxdFpYUnlhV056TG05d1pXNXphR2xtZEMxamJIVnoKZEdWeUxXTnphUzFrY21sMlpYSnpMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNRFVHQ3lzR0FRUUJrZ2dSWkFJQgpCQ1lUSkdZeU56VXlaRE01TFRGak5qa3RORFk1WlMxaVlqUXhMVGt4TkRSaFl6ZGxZelJsWlRBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFEdzNwSWcrQ25NcXlYaWRWUFBYQ3VGOGRqNEVqSlJBb0hna2NoTU0wMU5VRURXL3gKT2tRK1pRd2gxR1Qwd3Fja05rdXc4ZE5HY291NmN0VFJHekZRUE1lN0l4UWRLTUwrME15ZnAySzQ2MkhNakJNaQpZemlZU3B5QW1SR3lFNlhGQUhEZG5aMnNzeVpVMEFiWUd3THBnb2ZOMVlSeG9qTnB4STdPV1llUHZHYW0xWkhBCkpZK3ByZWtra0FxWStsRDRCS2xSR1hPRUhiVElydHA0d091a2w3UExhWjVMVGtpNE1XVHMxUlhycVEvaGRYa3IKcE5tOTI3WnBldXkrKzFYTlRCQWZFZndNV0M0SE4vSWgyZzZPNTNtNlp0aHBkZWJ6dWUreE9UQXZJaC9GV3c0ZwpJV240U0JraWczNFdWa3VjaUFlbDFYamRzV2ZVUHVHeUNZeWdZZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/aws-ebs-csi-driver-controller-metrics
        with hostname aws-ebs-csi-driver-controller-metrics.openshift-cluster-csi-drivers.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        aws-ebs-csi-driver-controller-metrics-serving-cert''. The certificate is valid
        for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:31:13Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:31:13Z"
      service.beta.openshift.io/originating-service-name: aws-ebs-csi-driver-controller-metrics
      service.beta.openshift.io/originating-service-uid: f2752d39-1c69-469e-bb41-9144ac7ec4ee
    creationTimestamp: "2026-01-28T09:31:13Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"f2752d39-1c69-469e-bb41-9144ac7ec4ee"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:31:13Z"
    name: aws-ebs-csi-driver-controller-metrics-serving-cert
    namespace: openshift-cluster-csi-drivers
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: aws-ebs-csi-driver-controller-metrics
      uid: f2752d39-1c69-469e-bb41-9144ac7ec4ee
    resourceVersion: "8670"
    uid: bfa67f79-bec2-4f44-ba42-17c51bce2940
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    aws_access_key_id: MjAgYnl0ZXMgbG9uZw==
    aws_secret_access_key: NDAgYnl0ZXMgbG9uZw==
    credentials: MTE1IGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    annotations:
      cloudcredential.openshift.io/aws-policy-last-applied: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["ec2:AttachVolume","ec2:CreateSnapshot","ec2:CreateTags","ec2:CreateVolume","ec2:DeleteSnapshot","ec2:DeleteTags","ec2:DeleteVolume","ec2:DescribeInstances","ec2:DescribeSnapshots","ec2:DescribeTags","ec2:DescribeVolumes","ec2:DescribeVolumesModifications","ec2:DetachVolume","ec2:ModifyVolume","ec2:DescribeAvailabilityZones","ec2:EnableFastSnapshotRestores"],"Resource":"*"},{"Effect":"Allow","Action":["kms:ReEncrypt*","kms:Decrypt","kms:Encrypt","kms:GenerateDataKey","kms:GenerateDataKeyWithoutPlainText","kms:DescribeKey"],"Resource":"*"},{"Effect":"Allow","Action":["kms:RevokeGrant","kms:CreateGrant","kms:ListGrants"],"Resource":"*","Condition":{"Bool":{"kms:GrantIsForAWSResource":true}}},{"Effect":"Allow","Action":["iam:GetUser"],"Resource":"arn:aws:iam::387344700001:user/ci-ln-vjb5l1t-76ef8--aws-ebs-csi-driver-operator-2pj7k"}]}'
      cloudcredential.openshift.io/credentials-request: openshift-cloud-credential-operator/aws-ebs-csi-driver-operator
    creationTimestamp: "2026-01-28T09:27:05Z"
    labels:
      cloudcredential.openshift.io/credentials-request: "true"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:aws_access_key_id: {}
          f:aws_secret_access_key: {}
          f:credentials: {}
        f:metadata:
          f:annotations:
            .: {}
            f:cloudcredential.openshift.io/aws-policy-last-applied: {}
            f:cloudcredential.openshift.io/credentials-request: {}
          f:labels:
            .: {}
            f:cloudcredential.openshift.io/credentials-request: {}
        f:type: {}
      manager: cloud-credential-operator
      operation: Update
      time: "2026-01-28T09:27:05Z"
    name: ebs-cloud-credentials
    namespace: openshift-cluster-csi-drivers
    resourceVersion: "2950"
    uid: 7be94755-b145-4c2a-a3e0-9764dadd0b11
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "35174"
