---
apiVersion: migration.k8s.io/v1alpha1
kind: StorageVersionMigration
metadata:
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  creationTimestamp: "2026-01-28T09:26:58Z"
  generation: 1
  managedFields:
  - apiVersion: migration.k8s.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/hypershift: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
      f:spec:
        .: {}
        f:resource:
          .: {}
          f:group: {}
          f:resource: {}
          f:version: {}
    manager: cluster-version-operator
    operation: Update
    time: "2026-01-28T09:26:58Z"
  - apiVersion: migration.k8s.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
    manager: migrator
    operation: Update
    subresource: status
    time: "2026-01-28T09:30:34Z"
  name: console-plugin-storage-version-migration
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 0370d296-6904-481d-ab90-157c7e5b835a
  resourceVersion: "6059"
  uid: 0f19d567-c171-4c59-b28b-74b88c345eda
spec:
  resource:
    group: console.openshift.io
    resource: consoleplugins
    version: v1
status:
  conditions:
  - lastUpdateTime: "2026-01-28T09:30:34Z"
    status: "True"
    type: Succeeded
