---
apiVersion: migration.k8s.io/v1alpha1
kind: StorageVersionMigration
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2026-01-28T09:26:02Z"
  generation: 1
  managedFields:
  - apiVersion: migration.k8s.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
      f:spec:
        .: {}
        f:resource:
          .: {}
          f:group: {}
          f:resource: {}
          f:version: {}
    manager: cluster-version-operator
    operation: Update
    time: "2026-01-28T09:26:02Z"
  - apiVersion: migration.k8s.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
    manager: migrator
    operation: Update
    subresource: status
    time: "2026-01-28T09:30:35Z"
  name: machineconfiguration-controllerconfig-storage-version-migration
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 0370d296-6904-481d-ab90-157c7e5b835a
  resourceVersion: "6190"
  uid: 18461bc7-2133-4048-b14d-8be56a5dfb3f
spec:
  resource:
    group: machineconfiguration.openshift.io
    resource: controllerconfigs
    version: v1
status:
  conditions:
  - lastUpdateTime: "2026-01-28T09:30:35Z"
    status: "True"
    type: Succeeded
