---
apiVersion: v1
items:
- apiVersion: v1
  data:
    aws_access_key_id: MjAgYnl0ZXMgbG9uZw==
    aws_secret_access_key: NDAgYnl0ZXMgbG9uZw==
    credentials: MTE1IGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    annotations:
      cloudcredential.openshift.io/aws-policy-last-applied: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["elasticloadbalancing:DescribeLoadBalancers","route53:ListHostedZones","route53:ListTagsForResources","route53:ChangeResourceRecordSets","tag:GetResources","sts:AssumeRole"],"Resource":"*"},{"Effect":"Allow","Action":["iam:GetUser"],"Resource":"arn:aws:iam::387344700001:user/ci-ln-vjb5l1t-76ef8--openshift-ingress-2vrd4"}]}'
      cloudcredential.openshift.io/credentials-request: openshift-cloud-credential-operator/openshift-ingress
    creationTimestamp: "2026-01-28T09:27:05Z"
    labels:
      cloudcredential.openshift.io/credentials-request: "true"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:aws_access_key_id: {}
          f:aws_secret_access_key: {}
          f:credentials: {}
        f:metadata:
          f:annotations:
            .: {}
            f:cloudcredential.openshift.io/aws-policy-last-applied: {}
            f:cloudcredential.openshift.io/credentials-request: {}
          f:labels:
            .: {}
            f:cloudcredential.openshift.io/credentials-request: {}
        f:type: {}
      manager: cloud-credential-operator
      operation: Update
      time: "2026-01-28T09:27:05Z"
    name: cloud-credentials
    namespace: openshift-ingress-operator
    resourceVersion: "2938"
    uid: c8076f8f-a335-4ceb-abc0-a123dbf8f93f
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBakNDQXVxZ0F3SUJBZ0lJZXliYlJiMVFmbzB3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRSYUZ3MHlPREF4TWpnd09UTXdORFZhTURFeEx6QXRCZ05WQkFNVEptMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMV2x1WjNKbGMzTXRiM0JsY21GMGIzSXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMkc0a0RUa3RQVFQxWkFtaENUdGllZnNhdDltNFV6UEp3N1V6dmhFVwpMU3FydnhkNjFQZjNaMEFocEw4L0Z4YlM3ekFjRFJPeFZlVjJjSGVITlhxL3lzd0V3Y0syT3JRb3FFcmxQMVZRClo0cG9JTnltR0cvempXbDVXbHNoWVg0UWR3bmpWcXNSbFRpbmMrQXU4bTRRbThjWTkreXJRWS9uVTg0aEpPTkYKVzNOT09ibEUyUUFhRmFWVzUxRzZkMGtoMXY1Y2NUdFU5NitNZCtUY3JxSCtpTWMydlV6bmJBWWVuOXFFSytRdwo3ZG9yUm5VSEd3WmdaSERFZDZiaFFsY1J3NTJ4T0lqMC9mOEpnTWhlSU9EUTFLNUljRkxYMXVsT3BsT0ZiN2MvCjJsVDFTVGdJUXhHMzQwK09vOTNlK2thVVQ0bjRmaTVMQStLL2RzeU94T09MQ3dJREFRQUJvNElCRnpDQ0FSTXcKRGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQwpNQUF3SFFZRFZSME9CQllFRkFPa1hsMXB4eGNZTi9RdGJrNk15U2NOOHp3WU1COEdBMVVkSXdRWU1CYUFGSmpCCmZsaFZXK0toSDN6Nk9qM2FwY0N0UFBYck1HY0dBMVVkRVFSZ01GNkNKbTFsZEhKcFkzTXViM0JsYm5Ob2FXWjAKTFdsdVozSmxjM010YjNCbGNtRjBiM0l1YzNaamdqUnRaWFJ5YVdOekxtOXdaVzV6YUdsbWRDMXBibWR5WlhOegpMVzl3WlhKaGRHOXlMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNRFVHQ3lzR0FRUUJrZ2dSWkFJQkJDWVRKR0ZoCk0yWmtaV0UyTFdFeFlXTXRORGd6TVMwNFlXUTBMVEUzTUdVeVlUSXlZVGhpT0RBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFzQnZkaGx0bkY1bHorSk16UHJpREIxTFAvM3hlcVczZ3MxUlU2VTdsM1JBM2FlYVJHMkRJd3dsMApMVm1OME1GSnpPNXFJbUV1YlFhb1VBMEU1eElxT24vTStTME8wV2M3WXpLb0orUkUvTmVJMkxDak5XU3pnSXlrCmpzOU5qNjNwU0xhekVNV1BhVUNqaEtzUmcxQW1GNk1Nbkh6dWJpbEs3QzNqNEpudlgvdUJwMDVyb1h1ZStmbFIKakJ2VnAwU1N1SUN0THlkcmxpWktPbkhEbHF0NHNpZ1lFT2FlN0RLSGhtZ2dRWWpRTlZTN3RJd1lRMjNDZGU3ZQpwUXBIMlNCVjVPOUluenhZLzJBU1lGL0I3TVpGanZueGU5dWhzSGZCZ1B6N1JXRkx3UjVRWGpPdDFXWEJ2dW16CmRnalEvWkJmcnNNTU5TOHpsMm5XVHNoaDRyaUEzZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-ingress-operator.svc and is annotated to the service with
        annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        metrics-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:45Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:30:45Z"
      service.beta.openshift.io/originating-service-name: metrics
      service.beta.openshift.io/originating-service-uid: aa3fdea6-a1ac-4831-8ad4-170e2a22a8b8
    creationTimestamp: "2026-01-28T09:30:45Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"aa3fdea6-a1ac-4831-8ad4-170e2a22a8b8"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:45Z"
    name: metrics-tls
    namespace: openshift-ingress-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: aa3fdea6-a1ac-4831-8ad4-170e2a22a8b8
    resourceVersion: "6923"
    uid: b32a33ea-4792-49e9-860b-e6d67086daf0
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0cGJtZHkKWlhOekxXOXdaWEpoZEc5eVFERTNOamsxT1RJM01UZ3dIaGNOTWpZd01USTRNRGt6TVRVNFdoY05Namd3TVRJNApNRGt6TVRVNVdqQW1NU1F3SWdZRFZRUUREQnRwYm1keVpYTnpMVzl3WlhKaGRHOXlRREUzTmprMU9USTNNVGd3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN6akZPZm16dmcwMDZyOUY0eUIwcncKZXBLd3ZhcFpGdGpRZkpVWnAvTXBHcXo2UXBIS0Z0SStsaTNqNGxKd3FNVGMxaHlCTVdHK1Z3dXVOc2gyZ2U3egpvTHFJS281REs0ZlE2OVErQ0dtSSs4UFFCcGw5WWFuZTg0emlKc1dBRk9lMVZlenlHSzI3S254OUcxRXkwR2lYClpvZ0dDbnVpWE1oeXhqSGVtNzlRZDErMGRCbjlYa0FuaFRPb0RsUUZGYXlIZy9RRXhpT3oxdXowSy9uNElsOGkKb3RPbGxOU0lKeTI3ZnpMeE5sZkw4cmZBRktibDFoSENjcU5FM2lDTkp0MzgrK0duOS9VVjd3b2QwQkc4KzMxagpoVDJyMGs5bGovQUtlazkzR0xwQ3NrNVpuUnQxVTdvSU1XOVJUN0FKRWRzMjkzbG1PUzU1aU53UFVQMWV5YTMxCkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lDcERBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEcKQTFVZERnUVdCQlFKNk90ZHdVVEdKZThzZUpvdFgzSnRQb2luZWpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQppNkhNdDZjWHFzUS92aGRYUDRrSXFQdlltT3QvZ2RCTVFKZXRBZjhPSVZOalJ6ZDNvdFNyeGJQK0E5eHc2R2FmCkFpQWlYOTBiKzUvbzVYa1NPMWpnY2RwMFlDZUc1RThBMnJiWXpLdUk1aFU4ZVJwa0Zpd0RPVGNlcFBtdlhDa0wKdDZ3OVpwZWVrWkx4bEh1NEtQY2NmNW04dTlLMTd3TG9haUxMaDFiMWg3bk9uL3hNZnpoNDVmT2hQWlVyelQvcQpoNmpSZ2duZGg4V2ZqR0p6SitWRlFpVlhwUzdOUFo4OStlTTlJbTBuaFV4YlI2cmpaWXZtOFl2Zy9DbmlIV0M4CjJDb01yN1NYWGZNSjI5akZnMXk2U0hRSjBmTWxUR3VaQ1ZjTURod3pJT0I3RFpaWWpzUXRXRlQxQ3U4bHBZOGMKYmljWm5Ha0xXSERRaDJoVUtQd2F3Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:31:59Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:type: {}
      manager: ingress-operator
      operation: Update
      time: "2026-01-28T09:31:59Z"
    name: router-ca
    namespace: openshift-ingress-operator
    resourceVersion: "10446"
    uid: 5c4d7838-3f25-4e83-8fb0-fa1beb969e6e
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35043"
