---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-28T09:31:00Z"
  name: operator-controller-controller-manager
  namespace: openshift-operator-controller
  resourceVersion: "7700"
  uid: 3755a42e-73f1-4099-a36a-0cbf38d893f2
