---
apiVersion: v1
items:
- apiVersion: v1
  data:
    clientSecret: NDMgYnl0ZXMgbG9uZw==
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:31:08Z"
    labels:
      app: console
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:clientSecret: {}
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4309f7e9-25ac-4621-a7d8-205a8ab9b717"}: {}
        f:type: {}
      manager: console
      operation: Update
      time: "2026-01-28T09:31:08Z"
    name: console-oauth-config
    namespace: openshift-console
    ownerReferences:
    - apiVersion: operator.openshift.io/v1
      controller: true
      kind: Console
      name: cluster
      uid: 4309f7e9-25ac-4621-a7d8-205a8ab9b717
    resourceVersion: "8236"
    uid: 815fecaa-f8c8-4d12-87c8-c4cc67fc0f69
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1ekNDQXMrZ0F3SUJBZ0lJTkwrRm1tWThhOGN3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE14TURkYUZ3MHlPREF4TWpnd09UTXhNRGhhTUNneEpqQWtCZ05WQkFNVEhXTnZibk52CmJHVXViM0JsYm5Ob2FXWjBMV052Ym5OdmJHVXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVBekxjRjlMUGdZeWkzV2Y5dHpyRmw2WHhmVjg4MkViRkdlQSt2ZjhhWG9NcnJtVWMyamdlRQpPNmxneGxUREY0SCsreWxyRVJ1MlA5L3RUWWhGTEpHMGRkWkpzb01nZC9LZG5yazNock90S2k3UEJIK1RuU2NKCnJkcEg3QWhHT0MwNUh4NDdMOVE2MUxJWHAzZ2VveS9tNE4zb2paUlFqTm81c0JJd1BrMEVGNDlaTyt1ZlNHZkwKc0ttK1ZzVVU5c0JNcTRtcFNEb3l5WGduaUxtdFp4VGFpK0ZNOFNxK3d5WlNDaTc3RTMwNnpoc2lTbU5pVVZJaApjM25XSUtvSmp0UGplSXlxQXhjWFlyOG5kUm94RFhMY0pCaFZKKzRhSTFXbE95VDY5ZkhiRHJTT2Q0SGVUdXl2CjVIVlZMRjNzUzhIb1RISVlzeXZFWXNPUlJGK1U2MzdpZXdJREFRQUJvNElCQlRDQ0FRRXdEZ1lEVlIwUEFRSC8KQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwTwpCQllFRkxBVG1WaTlEeWVqbVZtcUVHRWVxUmsvUHpDRk1COEdBMVVkSXdRWU1CYUFGSmpCZmxoVlcrS2hIM3o2Ck9qM2FwY0N0UFBYck1GVUdBMVVkRVFST01FeUNIV052Ym5OdmJHVXViM0JsYm5Ob2FXWjBMV052Ym5OdmJHVXUKYzNaamdpdGpiMjV6YjJ4bExtOXdaVzV6YUdsbWRDMWpiMjV6YjJ4bExuTjJZeTVqYkhWemRHVnlMbXh2WTJGcwpNRFVHQ3lzR0FRUUJrZ2dSWkFJQkJDWVRKRGhtWlRFM01USTNMV0ZqTUdJdE5EZzVOeTA1TVRFMUxUQTVObVpsClpXSXdOV1EwWlRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQU04N3FOWHhsQ0RYRVpvdkZDUnAreklTNTZTVmIKTHl0dXZJYmFtTnk4YmY2Nm92UWNGODJOd1I0OHNiQklLenR3MW5hc0Y5M2RCSWN5QVFvbkE0bS9wNGthNUJaZAptZzZsdXNmTXJ1TmVnckQwdkUxcVAvTjNpamwwLytmKzhvcnpaRGdtNDdpYzRwbkdlYkNkV3ppNkw1VXlOajYvCi81OHJYaFRrK3ZoT0FCcWcxbFVGUkJ1Uis1NUpCNytNVEVWL0JGa2lZUENxUTlPK0NUTjJtdHFhRHduSHBKVkwKbTl4VXdWQ2FYOE04dFhWZU9rOEtqMVRERTRXVTZIc3Y0WWUvR2kwQVJ3S0I1UDkxMERzaEduQTFFajhoV0RTNwptTVZiUkhNL0xYaGNPQzRNak1ieEZlOGZpcExnM0pWY3VjN0ZEeUVibEdRR3FTelJEUHFzWUE4Mm1nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/console with hostname
        console.openshift-console.svc and is annotated to the service with annotating
        a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        console-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:31:08Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:31:08Z"
      service.beta.openshift.io/originating-service-name: console
      service.beta.openshift.io/originating-service-uid: 8fe17127-ac0b-4897-9115-096feeb05d4e
    creationTimestamp: "2026-01-28T09:31:08Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"8fe17127-ac0b-4897-9115-096feeb05d4e"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:31:08Z"
    name: console-serving-cert
    namespace: openshift-console
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: console
      uid: 8fe17127-ac0b-4897-9115-096feeb05d4e
    resourceVersion: "8263"
    uid: e82558e8-0d41-43e7-a4ba-67346e252ad1
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35027"
