---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:28:23Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: cluster-controller-manager-operator
    operation: Update
    time: "2026-01-28T10:24:18Z"
  name: cluster-cloud-controller-manager-leader
  namespace: openshift-cloud-controller-manager-operator
  resourceVersion: "34771"
  uid: 118973ce-067f-423c-a609-a5f887495569
spec:
  acquireTime: "2026-01-28T09:28:23.096969Z"
  holderIdentity: ip-10-0-108-54_b936cb95-7703-4c54-b5af-babe9bfc0d37
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:18.194484Z"
