---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:28:23Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: config-sync-controllers
    operation: Update
    time: "2026-01-28T10:24:18Z"
  name: cluster-cloud-config-sync-leader
  namespace: openshift-cloud-controller-manager-operator
  resourceVersion: "34772"
  uid: 676cd658-57bf-4a9b-af51-2874a9082a9c
spec:
  acquireTime: "2026-01-28T09:28:23.254616Z"
  holderIdentity: ip-10-0-108-54_5eb99e84-10bf-4500-bdf0-d5b718cbc358
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:18.202141Z"
