---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c21,c10
    openshift.io/sa.scc.supplemental-groups: 1000440000/10000
    openshift.io/sa.scc.uid-range: 1000440000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2026-01-28T09:25:53Z"
  labels:
    kubernetes.io/metadata.name: openshift-nutanix-infra
    name: openshift-nutanix-infra
    openshift.io/run-level: ""
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2026-01-28T09:25:53Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
          f:openshift.io/node-selector: {}
          f:workload.openshift.io/allowed: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
          f:name: {}
          f:openshift.io/run-level: {}
          f:pod-security.kubernetes.io/audit: {}
          f:pod-security.kubernetes.io/enforce: {}
          f:pod-security.kubernetes.io/warn: {}
          f:security.openshift.io/scc.podSecurityLabelSync: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
    manager: cluster-version-operator
    operation: Update
    time: "2026-01-28T09:25:53Z"
  name: openshift-nutanix-infra
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 0370d296-6904-481d-ab90-157c7e5b835a
  resourceVersion: "1390"
  uid: 0e8baf48-0e74-4a08-899f-84ccb107055a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
