---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  creationTimestamp: "2026-01-28T09:30:07Z"
  generateName: csr-
  managedFields:
  - apiVersion: certificates.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:certificate: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2026-01-28T09:30:07Z"
  - apiVersion: certificates.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
    manager: multus-daemon
    operation: Update
    time: "2026-01-28T09:30:07Z"
  - apiVersion: certificates.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Approved"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: ovnkube-identity
    operation: Update
    subresource: approval
    time: "2026-01-28T09:30:07Z"
  name: csr-pbbrr
  resourceVersion: "5365"
  uid: 1de8e66e-b031-450c-b387-061f2392a174
spec:
  expirationSeconds: 86400
  extra:
    authentication.kubernetes.io/credential-id:
    - X509SHA256=c433a3c3ad892b9e243a2fd54a7c403f0d412c599c235532194675e4f9df8bad
  groups:
  - system:nodes
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQkZEQ0J1d0lCQURCWk1SWXdGQVlEVlFRS0V3MXplWE4wWlcwNmJYVnNkSFZ6TVQ4d1BRWURWUVFERXpaegplWE4wWlcwNmJYVnNkSFZ6T21sd0xURXdMVEF0TXkweU1ETXVkWE10ZDJWemRDMHhMbU52YlhCMWRHVXVhVzUwClpYSnVZV3d3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVMyOUFVSWR6NHZCbE5HN3RKTmJ6UkEKcTBBNUhRNnRwUDM1bWt4dndkR3ZJaWpmZm9QZmxleldybCsrRjZhUXJLZy9EOWhLVUcrOEtFVjcyWm5pN2R5cwpvQUF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUxYNlM0eEluZkIwVFMwUWVUTFZXU2JNUUhONlVRdWpac3gvCmQzWmZ0RmJXQWlCdDVPZEZ0dncxU29DOWRvNnNhZEpzOUo5QVFsTFNDZ2VpakdmR0NtYThJQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - client auth
  username: system:node:ip-10-0-3-203.us-west-1.compute.internal
status:
  certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNuRENDQVlTZ0F3SUJBZ0lSQUlPbXB4NkhQa2tZc3FqQm4yenZqSEl3RFFZSktvWklodmNOQVFFTEJRQXcKTFRFU01CQUdBMVVFQ3hNSmIzQmxibk5vYVdaME1SY3dGUVlEVlFRREV3NXJkV0psYkdWMExYTnBaMjVsY2pBZQpGdzB5TmpBeE1qZ3dPVEkxTURkYUZ3MHlOakF4TWprd09URXpNRFphTUZreEZqQVVCZ05WQkFvVERYTjVjM1JsCmJUcHRkV3gwZFhNeFB6QTlCZ05WQkFNVE5uTjVjM1JsYlRwdGRXeDBkWE02YVhBdE1UQXRNQzB6TFRJd015NTEKY3kxM1pYTjBMVEV1WTI5dGNIVjBaUzVwYm5SbGNtNWhiREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSApBMElBQkxiMEJRaDNQaThHVTBidTBrMXZORUNyUURrZERxMmsvZm1hVEcvQjBhOGlLTjkrZzkrVjdOYXVYNzRYCnBwQ3NxRDhQMkVwUWI3d29SWHZabWVMdDNLeWpWakJVTUE0R0ExVWREd0VCL3dRRUF3SUhnREFUQmdOVkhTVUUKRERBS0JnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUI4R0ExVWRJd1FZTUJhQUZMZG1wLzFubGhEKwptUGludHI0Q01RNDR3MDB2TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBeWU1WmdVQU9QV0hSZytENTNuc3lICnM5cllLU2crVkJIckRpeHJKN3Fmd0VSQ2N2clkvejVzRy9QS0lMQjBsK1I5eGVPOS9DWkxjVHpjK2VqN3grS3YKOWxqWGptcEZaYWhCTCtxSnBtTk0wU1pWckRwLy9zYXVkNGxyWU9oMGVaWTVlSkdvNkYxZFNxN0NMTVpobVlzQwp2UEs1Tk0wSWRTeXd4aGxQQVNqTHJrWUZJUzg0aEZCL3BjSXRGdS8xS1V6WkRQRTUvN1BBZ1RxYjRvRjFPZUQ5CkxELzNCWHo1UDV4M1dDc0Mzbkw1TWh2UlB2NWZvWXdWbDExU1R1a3VQTVVPYVdPSUxWdEU3Rm1sYjdLZkYvL1cKU3lTY20rUFo1eUhLUVNMQVZnMCtFQjRXa0NVSURkUGsyRVhJM3F3aWtGSXUrQ1p0OWlsSVU1ZklrdVBpV2l6MAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  conditions:
  - lastTransitionTime: "2026-01-28T09:30:07Z"
    lastUpdateTime: "2026-01-28T09:30:07Z"
    message: Auto-approved CSR "csr-pbbrr"
    reason: AutoApproved
    status: "True"
    type: Approved
