---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  creationTimestamp: "2026-01-28T09:31:56Z"
  generateName: system:openshift:openshift-monitoring-
  labels:
    metrics.openshift.io/csr.subject: prometheus
  managedFields:
  - apiVersion: certificates.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Approved"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: cluster-policy-controller
    operation: Update
    subresource: approval
    time: "2026-01-28T09:31:56Z"
  - apiVersion: certificates.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:certificate: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2026-01-28T09:31:56Z"
  - apiVersion: certificates.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:metrics.openshift.io/csr.subject: {}
    manager: operator
    operation: Update
    time: "2026-01-28T09:31:56Z"
  name: system:openshift:openshift-monitoring-f9sws
  resourceVersion: "9952"
  uid: 18bc7b36-d7f2-4975-b488-02d7908bdf27
spec:
  extra:
    authentication.kubernetes.io/credential-id:
    - JTI=c32834eb-3e49-48e8-97df-8bcc57a034d1
    authentication.kubernetes.io/node-name:
    - ip-10-0-108-54.us-west-1.compute.internal
    authentication.kubernetes.io/node-uid:
    - 8aee47ee-44d2-43c6-8262-ad6e14a5f14a
    authentication.kubernetes.io/pod-name:
    - cluster-monitoring-operator-5f95799b88-rt4b7
    authentication.kubernetes.io/pod-uid:
    - 9c469337-be39-4704-a464-5c68db5f71fe
  groups:
  - system:serviceaccounts
  - system:serviceaccounts:openshift-monitoring
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQkFEQ0JwZ0lCQURCRU1VSXdRQVlEVlFRREV6bHplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2YjNCbApibk5vYVdaMExXMXZibWwwYjNKcGJtYzZjSEp2YldWMGFHVjFjeTFyT0hNd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxCmhrak9QUU1CQndOQ0FBVDdUSndlcG45cFZBL093bVE1MVI4c09nZ084Sm5pNStqZWNkbTljRkJualdadjFjUzUKTnUrWHVPOCtmazZwNVZkVkw5Z3NYWTlxdk92Q05vUEVVY0cxb0FBd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaApBTUh6VkNOUXgycHlkQ2JNTHJSSnQ2ZThEN3Nya3ZXdXpqa0NOUERhaEJ5VkFpRUFzOFJGMGVqNjJsV3FtRlRhClFxWnNRVTNKY2tKWE5wbUh0R2crcmtSZWR4cz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  uid: 594706ba-2833-497a-909f-8cd4ef416224
  usages:
  - digital signature
  - key encipherment
  - client auth
  username: system:serviceaccount:openshift-monitoring:cluster-monitoring-operator
status:
  certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNoekNDQVcrZ0F3SUJBZ0lSQU81WklYczhVVHMyU2M3UDVLcG95bWt3RFFZSktvWklodmNOQVFFTEJRQXcKTFRFU01CQUdBMVVFQ3hNSmIzQmxibk5vYVdaME1SY3dGUVlEVlFRREV3NXJkV0psYkdWMExYTnBaMjVsY2pBZQpGdzB5TmpBeE1qZ3dPVEkyTlRaYUZ3MHlOakF4TWprd09URXpNRFphTUVReFFqQkFCZ05WQkFNVE9YTjVjM1JsCmJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwdmNHVnVjMmhwWm5RdGJXOXVhWFJ2Y21sdVp6cHdjbTl0WlhSb1pYVnoKTFdzNGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQdE1uQjZtZjJsVUQ4N0NaRG5WSHl3NgpDQTd3bWVMbjZONXgyYjF3VUdlTlptL1Z4TGsyNzVlNDd6NStUcW5sVjFVdjJDeGRqMnE4NjhJMmc4UlJ3YldqClZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUIKQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkxkbXAvMW5saEQrbVBpbnRyNENNUTQ0dzAwdk1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUMyYUkvMGtILzJObTRiWC9Rb2ZQK1ljSyswOVFBZmRvcWFsNC9VL2M0aGpzK09QVGw5CnJvdmc1Nlk0a0Q2bEFYNVVRUmtHTFFHci9YRmNYaE9Odkk1R3E0TzVTeUZNcEVMNmg1eUdraXA3ajNsN0swbEwKNTB3d2h1OExoVWFnaTJzVFVVbHkyelNHVVFPN05sU05oR2xXOFVYUVRRYkVSSk1oYi9GV05jOFhhaGRtOUw5SQprUFA4YlFoUEpBYWVrdEdMekh1OUVzUUlhblpUZmVCWXg5TUxjZDM0TW9qWXRVZDdYN1VTYjI4TWdsYlZBcTh2CmkzMGpjVkkwanF4ZGJqY09HNkg3YUhSVWFPbU40STRrOFdJbW41djdKejV5YXlBMGN4SlBuM211UXR3SCt1UTIKL0I1ZDdBZlR2VmYxdEdldDQveHBvajBGSGNXVldsdzRVemRoCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  conditions:
  - lastTransitionTime: "2026-01-28T09:31:56Z"
    lastUpdateTime: "2026-01-28T09:31:56Z"
    message: Auto-approved CSR "system:openshift:openshift-monitoring-f9sws"
    reason: AutoApproved
    status: "True"
    type: Approved
