---
apiVersion: v1
items:
- apiVersion: v1
  data:
    aws_access_key_id: MjAgYnl0ZXMgbG9uZw==
    aws_secret_access_key: NDAgYnl0ZXMgbG9uZw==
    credentials: MTE1IGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    annotations:
      cloudcredential.openshift.io/aws-policy-last-applied: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["iam:GetUser","iam:GetUserPolicy","iam:ListAccessKeys"],"Resource":"*"},{"Effect":"Allow","Action":["iam:GetUser"],"Resource":"arn:aws:iam::387344700001:user/ci-ln-vjb5l1t-76ef8--cloud-credential-operator-iam-ro-vn2ns"}]}'
      cloudcredential.openshift.io/credentials-request: openshift-cloud-credential-operator/cloud-credential-operator-iam-ro
    creationTimestamp: "2026-01-28T09:27:13Z"
    labels:
      cloudcredential.openshift.io/credentials-request: "true"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:aws_access_key_id: {}
          f:aws_secret_access_key: {}
          f:credentials: {}
        f:metadata:
          f:annotations:
            .: {}
            f:cloudcredential.openshift.io/aws-policy-last-applied: {}
            f:cloudcredential.openshift.io/credentials-request: {}
          f:labels:
            .: {}
            f:cloudcredential.openshift.io/credentials-request: {}
        f:type: {}
      manager: cloud-credential-operator
      operation: Update
      time: "2026-01-28T09:27:13Z"
    name: cloud-credential-operator-iam-ro-creds
    namespace: openshift-cloud-credential-operator
    resourceVersion: "3077"
    uid: 37e5c4a5-1e94-4df7-9ff9-e6eee2a3a51f
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVLakNDQXhLZ0F3SUJBZ0lJZXRlTUl3Q1g1Sm93RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpsYUZ3MHlPREF4TWpnd09UTXdOREJhTUQ0eFBEQTZCZ05WQkFNVE0yTmpieTF0ClpYUnlhV056TG05d1pXNXphR2xtZEMxamJHOTFaQzFqY21Wa1pXNTBhV0ZzTFc5d1pYSmhkRzl5TG5OMll6Q0MKQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNSzk4andJWWdNb0lZOEVxUFYwd2QzaQpLeW5Tb3BqdG9kN0hLeXh0TFhabUl6ejVZMGRTa09PNitCbWpHVzd3UC8xRTFRbW80bC9IYWZoTGJURlJ2VGo3CkQ4QUk1QXgrZ3BPYitKQnZ4MTVnRWpiZExnekxjbGtNTGJreEdCZTB0U0tHUy9pS08wM215VklsZUdqb3dPV3IKTXRGQ1pKTXN0ZnQ1ZUNNYmhzeGR2cG9GbnhaTER3ZU5LRENSZTZuTTVLdDhVNDViMkRkV3dGMzFVQlpJbjNtMgpPVUVTOFF1V2lTYWFXTnBTZ29nUnIySnJOSnp1OTBEK3JUVWNkUnhCS0w5RlV0WVNwMkYxQXRRamJiUVpYTFVUCmlZSTRCalpmRkFNaWFuczBQMjVtU0RuVHZINllLTjhkTUtBN2FnWkhDRExlSkZqYTBvRm5LRzlxdmNLWGJhOEMKQXdFQUFhT0NBVEl3Z2dFdU1BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjRApBVEFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUlRwcUMrbXY4TUYrajRwekdYMUdIYjNZWWVyVEFmCkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejE2ekNCZ1FZRFZSMFJCSG93ZUlJelkyTnYKTFcxbGRISnBZM011YjNCbGJuTm9hV1owTFdOc2IzVmtMV055WldSbGJuUnBZV3d0YjNCbGNtRjBiM0l1YzNaagpna0ZqWTI4dGJXVjBjbWxqY3k1dmNHVnVjMmhwWm5RdFkyeHZkV1F0WTNKbFpHVnVkR2xoYkMxdmNHVnlZWFJ2CmNpNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQTFCZ3NyQmdFRUFaSUlFV1FDQVFRbUV5UTNNbVZsTmpVeE5TMWsKT0RRNUxUUmlOMlV0WVdRM1ppMHdOak0xWkdJek1ETmtPVGt3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhWMgpGVC9LVmZsam9DRHFyL2NYN3ZBejg3S1YvMEpEYUVTQjlRbGtacXJ0OVh6WHZ3RHBnVVhVL2pYc3ZiQlRNclNUCnNmZklmSXBiTWlPaHhFZzNNdnNWL2ErN1FWRUY0cExNbmtzdktuNHJxSjMrSFhOQUVsT3V0MVpkVkd0dUwxRFgKMjRqUXQ0NjYvaW4xWDZXazd6U3Q5UFhGcXdnQmV2RHpCejVVS0pqMS9SUTZ2N0JZQXloaXFlU1VidXJ6UHI5Ngo1SytTejJkM1ovcU0xS2RPSU5XQnJvZTc3SHVrZ1B4MER2WGpWMGhtUzc1SitWa2ZXTC93d1c5Q01sUkN2eHRCCjdlK21rekt4bFpaUHQ4UXdpRWZ5WEpiOUJiSlpoM0JGRERpV05nWEZiRWZkWHJUSWZJVXJ0S3pYYTNYTUQ5REcKMlFreEpneElqVFc0ajNxejNLdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/cco-metrics with hostname
        cco-metrics.openshift-cloud-credential-operator.svc and is annotated to the
        service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        cloud-credential-operator-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:40Z"
      service.alpha.openshift.io/originating-service-name: cco-metrics
      service.alpha.openshift.io/originating-service-uid: 72ee6515-d849-4b7e-ad7f-0635db303d99
      service.beta.openshift.io/expiry: "2028-01-28T09:30:40Z"
    creationTimestamp: "2026-01-28T09:30:40Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"72ee6515-d849-4b7e-ad7f-0635db303d99"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:40Z"
    name: cloud-credential-operator-serving-cert
    namespace: openshift-cloud-credential-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: cco-metrics
      uid: 72ee6515-d849-4b7e-ad7f-0635db303d99
    resourceVersion: "6501"
    uid: 900ed2d9-0518-4660-b5f2-1c364c690fd3
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVSekNDQXkrZ0F3SUJBZ0lJTmJibGduazdFTW93RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVFF3TVRGYUZ3MHlPREF4TWpnd09UUXdNVEphTUVjeFJUQkRCZ05WQkFNVFBIQnZaQzFwClpHVnVkR2wwZVMxM1pXSm9iMjlyTG05d1pXNXphR2xtZEMxamJHOTFaQzFqY21Wa1pXNTBhV0ZzTFc5d1pYSmgKZEc5eUxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMYkRuazNhZmVOZQpjZDNsSWdKczB1Slp0b3ZURzBHVUVYOVl1djJkdXZrQUtVdkRhamtoaXpOYkNpYzB2VWdTT3F4djF5b2Z0cFJyCkk2VmhEZFcxSXdqM1AvTU5CakJBcUU4RFRHbTVodlFvV2lEelFhaVpQT1hSbWFEY1MzeSsrRVpLb0Vmd0RVckcKMVdEWGd1Z09vWGp5RVBiTHc5TjJqc0tzY0lRcmRMVWJVZ2Zad2hjazQzcnFqWDZNeTN0TFY1S3hveklHWEEvZApGVDdMaG5HTzcvQis3cEhDUVhKV1ZYaU1uR2FBOGlXYWhzV2xudkcvOFhXNUlVVFg0dEhESTRFZ1dpR2dHa1dPCmRsMDVMMzZveVN5ZHZEeXR5elZqZ2xPTW9DSnJERVBYSTNwQlBCcS9iK0tPaFFrcEJDTWNFK0tlM3BPZkRxanUKWk1RbWtQcDRXaWNDQXdFQUFhT0NBVVl3Z2dGQ01BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBSwpCZ2dyQmdFRkJRY0RBVEFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU3FQV2xqZ29JT2pkakJnOWlLCnhxNUdFRXhDSERBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejE2ekNCbFFZRFZSMFIKQklHTk1JR0tnanh3YjJRdGFXUmxiblJwZEhrdGQyVmlhRzl2YXk1dmNHVnVjMmhwWm5RdFkyeHZkV1F0WTNKbApaR1Z1ZEdsaGJDMXZjR1Z5WVhSdmNpNXpkbU9DU25CdlpDMXBaR1Z1ZEdsMGVTMTNaV0pvYjI5ckxtOXdaVzV6CmFHbG1kQzFqYkc5MVpDMWpjbVZrWlc1MGFXRnNMVzl3WlhKaGRHOXlMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnMKTURVR0N5c0dBUVFCa2dnUlpBSUJCQ1lUSkRkaU4yTTFZVGRsTFRRelpqSXRORFZtTUMxaU5URmtMVGs1TXpRNQpOVEJtTjJReU5qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFZcTh4bEhEMjJ4RE91TlNqWWV4M2xKTlpZcnNICnJOTFNKMlMxT2VQNkFRcDgzZnY0Vk5rUk9YS29sZU1pekozaWpTNzJ5blRsZUVuL0t2RVA4S1NXc1NzSzA4UEIKZ1JmUUwzaHRTNVd4QTg2bXpyaDI5c0tvYXdaMTF5QTFGdHZnK3RVM1VsNE11dDFIRThHUG5lZ1p6OVBWUWx5SQp4UGVWQThCUXhVTWVpN1JSTDhmQlU2clRpVkYxM2NnR2l1WEpydERXaHMwYllrT0E0Ym1SWEFZeWNUM0FOVlBaCkZ2bVhYMStIb09xU2NBeElFTjVZeE1HM0FJNEwxZ0Zmb3Q5c1Mzdk9yZkhsRURaems5QWludGU5cEZuS0lOOUUKOE1tZGdxWndSMmNlaHltSXQyaHhkdkhVS2xCNWZJdlI1ZHVFZ2JMZGlyWFZWaHVvbWF4NFNLNkY0UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/pod-identity-webhook
        with hostname pod-identity-webhook.openshift-cloud-credential-operator.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        pod-identity-webhook''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:40:12Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:40:12Z"
      service.beta.openshift.io/originating-service-name: pod-identity-webhook
      service.beta.openshift.io/originating-service-uid: 7b7c5a7e-43f2-45f0-b51d-9934950f7d26
    creationTimestamp: "2026-01-28T09:40:12Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"7b7c5a7e-43f2-45f0-b51d-9934950f7d26"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:40:12Z"
    name: pod-identity-webhook
    namespace: openshift-cloud-credential-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: pod-identity-webhook
      uid: 7b7c5a7e-43f2-45f0-b51d-9934950f7d26
    resourceVersion: "18469"
    uid: 2b27ce16-4615-47d8-8dc0-836e1dd66626
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "34974"
