---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.0.25/23"],"mac_address":"0a:58:0a:80:00:19","gateway_ips":["10.128.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.128.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.128.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.0.1"}],"ip_address":"10.128.0.25/23","gateway_ip":"10.128.0.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.0.25"
          ],
          "mac": "0a:58:0a:80:00:19",
          "default": true,
          "dns": {}
      }]
    openshift.io/required-scc: restricted-v2
    openshift.io/scc: restricted-v2
    operatorframework.io/managed-by: marketplace-operator
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    security.openshift.io/validated-scc-subject-type: user
  creationTimestamp: "2026-01-28T09:32:01Z"
  generateName: redhat-marketplace-
  generation: 1
  labels:
    olm.catalogSource: redhat-marketplace
    olm.managed: "true"
    olm.pod-spec-hash: 3nY0ZOnDjYFVtUhyvFqXWinq6qdm5EOEEwY5tS
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cluster-autoscaler.kubernetes.io/safe-to-evict: {}
          f:openshift.io/required-scc: {}
          f:operatorframework.io/managed-by: {}
          f:target.workload.openshift.io/management: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:olm.catalogSource: {}
          f:olm.managed: {}
          f:olm.pod-spec-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"50b6dc35-21c8-4854-a510-afb85c08c73c"}: {}
      f:spec:
        f:containers:
          k:{"name":"registry-server"}:
            .: {}
            f:args: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"GOMEMLIMIT"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:exec:
                .: {}
                f:command: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":50051,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:exec:
                .: {}
                f:command: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities:
                .: {}
                f:drop: {}
              f:readOnlyRootFilesystem: {}
            f:startupProbe:
              .: {}
              f:exec:
                .: {}
                f:command: {}
              f:failureThreshold: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/extracted-catalog"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:initContainers:
          .: {}
          k:{"name":"extract-content"}:
            .: {}
            f:args: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities:
                .: {}
                f:drop: {}
              f:readOnlyRootFilesystem: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/extracted-catalog"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/utilities"}:
                .: {}
                f:mountPath: {}
                f:name: {}
          k:{"name":"extract-utilities"}:
            .: {}
            f:args: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities:
                .: {}
                f:drop: {}
              f:readOnlyRootFilesystem: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/utilities"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:nodeSelector: {}
        f:priorityClassName: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:seccompProfile:
            .: {}
            f:type: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"catalog-content"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"utilities"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
    manager: catalog
    operation: Update
    time: "2026-01-28T09:32:01Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.ovn.org/pod-networks: {}
    manager: ip-10-0-3-203
    operation: Update
    subresource: status
    time: "2026-01-28T09:32:01Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
    manager: multus-daemon
    operation: Update
    subresource: status
    time: "2026-01-28T09:32:21Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:initContainerStatuses: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.128.0.25"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2026-01-28T09:33:32Z"
  name: redhat-marketplace-5tppv
  namespace: openshift-marketplace
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: CatalogSource
    name: redhat-marketplace
    uid: 50b6dc35-21c8-4854-a510-afb85c08c73c
  resourceVersion: "12861"
  uid: be585233-44cf-4bd9-b1a4-fe00ac44819c
spec:
  containers:
  - args:
    - serve
    - /extracted-catalog/catalog
    - --cache-dir=/extracted-catalog/cache
    command:
    - /bin/opm
    env:
    - name: GOMEMLIMIT
      value: 20MiB
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:7290800c1daf30f811a950110a15ab75cd366eba88327d15030dc2be641e1d73
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - grpc_health_probe
        - -addr=:50051
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: registry-server
    ports:
    - containerPort: 50051
      name: grpc
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - grpc_health_probe
        - -addr=:50051
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000280000
    startupProbe:
      exec:
        command:
        - grpc_health_probe
        - -addr=:50051
      failureThreshold: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /extracted-catalog
      name: catalog-content
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7kfnz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - /bin/copy-content
    - /utilities/copy-content
    command:
    - cp
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:941c71daa16180c08c62cb401a0337fdb7931e0bbf363172723eede6439b6439
    imagePullPolicy: IfNotPresent
    name: extract-utilities
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000280000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /utilities
      name: utilities
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7kfnz
      readOnly: true
  - args:
    - --catalog.from=/configs
    - --catalog.to=/extracted-catalog/catalog
    - --cache.from=/tmp/cache
    - --cache.to=/extracted-catalog/cache
    command:
    - /utilities/copy-content
    image: registry.redhat.io/redhat/redhat-marketplace-index:v4.20
    imagePullPolicy: Always
    name: extract-content
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000280000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /utilities
      name: utilities
    - mountPath: /extracted-catalog
      name: catalog-content
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7kfnz
      readOnly: true
  nodeName: ip-10-0-3-203.us-west-1.compute.internal
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000280000
    seLinuxOptions:
      level: s0:c17,c4
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: redhat-marketplace
  serviceAccountName: redhat-marketplace
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 120
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 120
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: utilities
  - emptyDir: {}
    name: catalog-content
  - name: kube-api-access-7kfnz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:32:23Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:32:48Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:33:32Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:33:32Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:32:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 10m
      memory: 20Mi
    containerID: cri-o://4bff893c84fbe5e0300368443346c26e39c096d7dd75b216ff80b8aad3d8fa77
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:7290800c1daf30f811a950110a15ab75cd366eba88327d15030dc2be641e1d73
    imageID: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:7290800c1daf30f811a950110a15ab75cd366eba88327d15030dc2be641e1d73
    lastState: {}
    name: registry-server
    ready: true
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-01-28T09:33:05Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1000280000
        uid: 1000280000
    volumeMounts:
    - mountPath: /extracted-catalog
      name: catalog-content
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7kfnz
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.3.203
  hostIPs:
  - ip: 10.0.3.203
  initContainerStatuses:
  - containerID: cri-o://21b4e036466d0e111f89053d07e38bbe7489c681b21aa980c33714ab9d9b2fe6
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:941c71daa16180c08c62cb401a0337fdb7931e0bbf363172723eede6439b6439
    imageID: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:941c71daa16180c08c62cb401a0337fdb7931e0bbf363172723eede6439b6439
    lastState: {}
    name: extract-utilities
    ready: true
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://21b4e036466d0e111f89053d07e38bbe7489c681b21aa980c33714ab9d9b2fe6
        exitCode: 0
        finishedAt: "2026-01-28T09:32:23Z"
        reason: Completed
        startedAt: "2026-01-28T09:32:23Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1000280000
        uid: 1000280000
    volumeMounts:
    - mountPath: /utilities
      name: utilities
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7kfnz
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: cri-o://975efedcb10f7ee356c3b57d04580448e09be3cdacd9792b53d83ccde55e0616
    image: registry.redhat.io/redhat/redhat-marketplace-index:v4.20
    imageID: registry.redhat.io/redhat/redhat-marketplace-index@sha256:2de587bb1487f6b1dd49786d2fc43245365c8f7492fffdb71d054ed573414fa4
    lastState: {}
    name: extract-content
    ready: true
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://975efedcb10f7ee356c3b57d04580448e09be3cdacd9792b53d83ccde55e0616
        exitCode: 0
        finishedAt: "2026-01-28T09:32:48Z"
        reason: Completed
        startedAt: "2026-01-28T09:32:48Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1000280000
        uid: 1000280000
    volumeMounts:
    - mountPath: /utilities
      name: utilities
    - mountPath: /extracted-catalog
      name: catalog-content
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7kfnz
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Running
  podIP: 10.128.0.25
  podIPs:
  - ip: 10.128.0.25
  qosClass: Burstable
  startTime: "2026-01-28T09:32:01Z"
