---
apiVersion: v1
items:
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:10Z"
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: catalogd-controller-manager-67dbc4869c-r2qb5
    namespace: openshift-catalogd
    resourceVersion: "8385"
    uid: efa1985e-a9bc-45f5-868b-11cd5544b2d0
  kind: Event
  lastTimestamp: "2026-01-28T09:31:10Z"
  message: Successfully assigned openshift-catalogd/catalogd-controller-manager-67dbc4869c-r2qb5
    to ip-10-0-3-203.us-west-1.compute.internal
  metadata:
    creationTimestamp: "2026-01-28T09:31:10Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: kube-scheduler
      operation: Update
      time: "2026-01-28T09:31:10Z"
    name: catalogd-controller-manager-67dbc4869c-r2qb5.188edb288bd0efea
    namespace: openshift-catalogd
    resourceVersion: "8389"
    uid: 20b08a7e-7a78-4d73-918b-13c7f45e51cf
  reason: Scheduled
  reportingComponent: default-scheduler
  reportingInstance: ""
  source:
    component: default-scheduler
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:11Z"
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: catalogd-controller-manager-67dbc4869c-r2qb5
    namespace: openshift-catalogd
    resourceVersion: "8387"
    uid: efa1985e-a9bc-45f5-868b-11cd5544b2d0
  kind: Event
  lastTimestamp: "2026-01-28T09:31:11Z"
  message: 'MountVolume.SetUp failed for volume "ca-certs" : configmap "catalogd-trusted-ca-bundle"
    not found'
  metadata:
    creationTimestamp: "2026-01-28T09:31:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: kubelet
      operation: Update
      time: "2026-01-28T09:31:11Z"
    name: catalogd-controller-manager-67dbc4869c-r2qb5.188edb28992daacb
    namespace: openshift-catalogd
    resourceVersion: "8399"
    uid: 409223b9-4559-4a51-a370-7e7388f56e6d
  reason: FailedMount
  reportingComponent: kubelet
  reportingInstance: ip-10-0-3-203.us-west-1.compute.internal
  source:
    component: kubelet
    host: ip-10-0-3-203.us-west-1.compute.internal
  type: Warning
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:11Z"
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: catalogd-controller-manager-67dbc4869c-r2qb5
    namespace: openshift-catalogd
    resourceVersion: "8387"
    uid: efa1985e-a9bc-45f5-868b-11cd5544b2d0
  kind: Event
  lastTimestamp: "2026-01-28T09:31:11Z"
  message: 'MountVolume.SetUp failed for volume "catalogserver-certs" : secret "catalogserver-cert"
    not found'
  metadata:
    creationTimestamp: "2026-01-28T09:31:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: kubelet
      operation: Update
      time: "2026-01-28T09:31:11Z"
    name: catalogd-controller-manager-67dbc4869c-r2qb5.188edb28992eb73c
    namespace: openshift-catalogd
    resourceVersion: "8400"
    uid: 376f8d83-4edc-4992-95eb-e8e0c6b14482
  reason: FailedMount
  reportingComponent: kubelet
  reportingInstance: ip-10-0-3-203.us-west-1.compute.internal
  source:
    component: kubelet
    host: ip-10-0-3-203.us-west-1.compute.internal
  type: Warning
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:11Z"
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: catalogd-controller-manager-67dbc4869c-r2qb5
    namespace: openshift-catalogd
    resourceVersion: "8392"
    uid: efa1985e-a9bc-45f5-868b-11cd5544b2d0
  kind: Event
  lastTimestamp: "2026-01-28T09:31:11Z"
  message: Add eth0 [10.128.0.12/23] from ovn-kubernetes
  metadata:
    creationTimestamp: "2026-01-28T09:31:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: multus-daemon
      operation: Update
      time: "2026-01-28T09:31:11Z"
    name: catalogd-controller-manager-67dbc4869c-r2qb5.188edb28c9edb91a
    namespace: openshift-catalogd
    resourceVersion: "8444"
    uid: 021e974c-8808-49df-956b-d9e73410326b
  reason: AddedInterface
  reportingComponent: multus
  reportingInstance: ""
  source:
    component: multus
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:11Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{manager}
    kind: Pod
    name: catalogd-controller-manager-67dbc4869c-r2qb5
    namespace: openshift-catalogd
    resourceVersion: "8387"
    uid: efa1985e-a9bc-45f5-868b-11cd5544b2d0
  kind: Event
  lastTimestamp: "2026-01-28T09:31:11Z"
  message: Pulling image "registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:f7d0d3af8ca46727b17eae293799af55706dedd1ff2e9ef0fa73f804fd7a93fa"
  metadata:
    creationTimestamp: "2026-01-28T09:31:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: kubelet
      operation: Update
      time: "2026-01-28T09:31:11Z"
    name: catalogd-controller-manager-67dbc4869c-r2qb5.188edb28cb63b6b6
    namespace: openshift-catalogd
    resourceVersion: "8446"
    uid: 1b33e66a-9a68-4303-b1fb-7e265cb0e7b7
  reason: Pulling
  reportingComponent: kubelet
  reportingInstance: ip-10-0-3-203.us-west-1.compute.internal
  source:
    component: kubelet
    host: ip-10-0-3-203.us-west-1.compute.internal
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:14Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{manager}
    kind: Pod
    name: catalogd-controller-manager-67dbc4869c-r2qb5
    namespace: openshift-catalogd
    resourceVersion: "8387"
    uid: efa1985e-a9bc-45f5-868b-11cd5544b2d0
  kind: Event
  lastTimestamp: "2026-01-28T09:31:14Z"
  message: 'Successfully pulled image "registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:f7d0d3af8ca46727b17eae293799af55706dedd1ff2e9ef0fa73f804fd7a93fa"
    in 2.642s (2.642s including waiting). Image size: 453909640 bytes.'
  metadata:
    creationTimestamp: "2026-01-28T09:31:14Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: kubelet
      operation: Update
      time: "2026-01-28T09:31:14Z"
    name: catalogd-controller-manager-67dbc4869c-r2qb5.188edb2968ec6dac
    namespace: openshift-catalogd
    resourceVersion: "8741"
    uid: e1c3bd23-026d-4655-9920-f0138f99a823
  reason: Pulled
  reportingComponent: kubelet
  reportingInstance: ip-10-0-3-203.us-west-1.compute.internal
  source:
    component: kubelet
    host: ip-10-0-3-203.us-west-1.compute.internal
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:14Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{manager}
    kind: Pod
    name: catalogd-controller-manager-67dbc4869c-r2qb5
    namespace: openshift-catalogd
    resourceVersion: "8387"
    uid: efa1985e-a9bc-45f5-868b-11cd5544b2d0
  kind: Event
  lastTimestamp: "2026-01-28T09:31:14Z"
  message: 'Created container: manager'
  metadata:
    creationTimestamp: "2026-01-28T09:31:14Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: kubelet
      operation: Update
      time: "2026-01-28T09:31:14Z"
    name: catalogd-controller-manager-67dbc4869c-r2qb5.188edb2978b58bca
    namespace: openshift-catalogd
    resourceVersion: "8755"
    uid: 27848dea-f702-48be-b158-cf81f74b9464
  reason: Created
  reportingComponent: kubelet
  reportingInstance: ip-10-0-3-203.us-west-1.compute.internal
  source:
    component: kubelet
    host: ip-10-0-3-203.us-west-1.compute.internal
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:14Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{manager}
    kind: Pod
    name: catalogd-controller-manager-67dbc4869c-r2qb5
    namespace: openshift-catalogd
    resourceVersion: "8387"
    uid: efa1985e-a9bc-45f5-868b-11cd5544b2d0
  kind: Event
  lastTimestamp: "2026-01-28T09:31:14Z"
  message: Started container manager
  metadata:
    creationTimestamp: "2026-01-28T09:31:14Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: kubelet
      operation: Update
      time: "2026-01-28T09:31:14Z"
    name: catalogd-controller-manager-67dbc4869c-r2qb5.188edb297958fdb5
    namespace: openshift-catalogd
    resourceVersion: "8757"
    uid: 2c30153e-079d-4af8-a332-35d6179c1f75
  reason: Started
  reportingComponent: kubelet
  reportingInstance: ip-10-0-3-203.us-west-1.compute.internal
  source:
    component: kubelet
    host: ip-10-0-3-203.us-west-1.compute.internal
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:10Z"
  involvedObject:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: catalogd-controller-manager-67dbc4869c
    namespace: openshift-catalogd
    resourceVersion: "8357"
    uid: 0ffe8465-1635-4d10-8369-f7c647c586b3
  kind: Event
  lastTimestamp: "2026-01-28T09:31:10Z"
  message: 'Created pod: catalogd-controller-manager-67dbc4869c-r2qb5'
  metadata:
    creationTimestamp: "2026-01-28T09:31:10Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:31:10Z"
    name: catalogd-controller-manager-67dbc4869c.188edb288b528777
    namespace: openshift-catalogd
    resourceVersion: "8386"
    uid: a697e19a-e32a-4248-aca2-8794a727a54d
  reason: SuccessfulCreate
  reportingComponent: replicaset-controller
  reportingInstance: ""
  source:
    component: replicaset-controller
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:10Z"
  involvedObject:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogd-controller-manager
    namespace: openshift-catalogd
    resourceVersion: "8352"
    uid: 241246cf-e8d4-4364-8c3f-8fdbe912e685
  kind: Event
  lastTimestamp: "2026-01-28T09:31:10Z"
  message: Scaled up replica set catalogd-controller-manager-67dbc4869c from 0 to
    1
  metadata:
    creationTimestamp: "2026-01-28T09:31:10Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:31:10Z"
    name: catalogd-controller-manager.188edb2885b49354
    namespace: openshift-catalogd
    resourceVersion: "8362"
    uid: c3a81091-afd7-47e0-9c90-c10a696b7bc7
  reason: ScalingReplicaSet
  reportingComponent: deployment-controller
  reportingInstance: ""
  source:
    component: deployment-controller
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2026-01-28T09:31:14Z"
  involvedObject:
    apiVersion: coordination.k8s.io/v1
    kind: Lease
    name: catalogd-operator-lock
    namespace: openshift-catalogd
    resourceVersion: "8761"
    uid: 5505062f-f842-42be-8d6a-c741fc931b8e
  kind: Event
  lastTimestamp: "2026-01-28T09:31:14Z"
  message: catalogd-controller-manager-67dbc4869c-r2qb5_b4286554-73cd-40fb-9724-1c72936572dd
    became leader
  metadata:
    creationTimestamp: "2026-01-28T09:31:14Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: catalogd
      operation: Update
      time: "2026-01-28T09:31:14Z"
    name: catalogd-operator-lock.188edb297cfff2b9
    namespace: openshift-catalogd
    resourceVersion: "8763"
    uid: 989ba279-d107-49bc-8757-a083cf5f610b
  reason: LeaderElection
  reportingComponent: catalogd-controller-manager-67dbc4869c-r2qb5_b4286554-73cd-40fb-9724-1c72936572dd
  reportingInstance: ""
  source:
    component: catalogd-controller-manager-67dbc4869c-r2qb5_b4286554-73cd-40fb-9724-1c72936572dd
  type: Normal
kind: EventList
metadata:
  resourceVersion: "35086"
