---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVCVENDQXUyZ0F3SUJBZ0lJUzF3WFpzaHZIVmN3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE14TVRCYUZ3MHlPREF4TWpnd09UTXhNVEZhTURJeE1EQXVCZ05WQkFNVEoyTmhkR0ZzCmIyZGtMWE5sY25acFkyVXViM0JsYm5Ob2FXWjBMV05oZEdGc2IyZGtMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUxCdEU3OTA0MkJYcXpUcDFiRUlNZHAxaGxVRTdtZ2MzcDZCcGtnawpram9CR1Y3MFVicHVEKy9MSUhERmUxcWgzWkRaNW4wbjJ6aTIvbTJNeERPYmR6TzlER09uSWtra05TdWpPcTdNCmI0ZHZlVFlwUmlqOXBCQStPZXdheTNPSUY3dzZYTnZ0MFBtcjh5YzZNYlluVVpVMFE5VVZSUFhLR3lLSXFiRG4KQW1jUFpVVDB2U2JOUWRZUlR0V3RJSkpMeGlGaGgwdHRtYnFlVVFlT1M0Qm1KQmFmMm9tTytUdzcyNFVqbDM4SwpVYlpuYlNXbnpvRVpSakQwQ0tSUWxRSUh4MnBBNWtzeVU5NzlQQXFDdFJGQUJqZWZFcTZtZDZ3ay9GK2gzamdOCldUaHd1OHRITTNzQm9wWHV2SWhibWg4N3RqakZyeWZ5MURsN1hNMHlrcEVVOTU4Q0F3RUFBYU9DQVJrd2dnRVYKTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBTUJnTlZIUk1CQWY4RQpBakFBTUIwR0ExVWREZ1FXQkJTMU0zeU5PVzYvckt0Q1dXVCtNSjlkYWdVVkN6QWZCZ05WSFNNRUdEQVdnQlNZCndYNVlWVnZpb1I5OCtqbzkycVhBclR6MTZ6QnBCZ05WSFJFRVlqQmdnaWRqWVhSaGJHOW5aQzF6WlhKMmFXTmwKTG05d1pXNXphR2xtZEMxallYUmhiRzluWkM1emRtT0NOV05oZEdGc2IyZGtMWE5sY25acFkyVXViM0JsYm5ObwphV1owTFdOaGRHRnNiMmRrTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTURVR0N5c0dBUVFCa2dnUlpBSUJCQ1lUCkpETmtZMll3WlRRekxURXhObVV0TkRJeFlpMDRZalZsTFdJM04yTTVZVFZtTWpobU1EQU5CZ2txaGtpRzl3MEIKQVFzRkFBT0NBUUVBY29xei9SRjI0ZTl0ZnRpejdRaUthZ05maGVnTnM2LzVWU0htdnZ0MVU1b0VoTTVpQldXQwp4N2FDaVk4UmF3clVwVE82b1h0UVBWT25jWlh2Qk8vWGFtTTdieitoSDloeEZtc2ZaVGd2OGFqdGlhcHprM1R3CkgzU0pHUjhWUmZKOVdodGIvYm5DajNlMjNIZVdxcVB3T3kxaEVzanpsNEp2NElqMTVsNVROVnJ2QWQyK3Z4V28Kb1JxQVBFbU9lSERlQXNaWUd1Rm40OW9NUXh0OTFPQkVKVDhBN2hPVzZzRnVzazYwZWpTbjhpWTNHUjV6bEdoOApETEhiZDZJbGtwUWlabWNGVGVtN1lYM0VKRVFJU3Y1QUZCTENKd0xrRFY4c3FCRTgwcVRtcE5GeE5HNzFCdGRuCmw3TGZ3Q1E4bmlFalRHWmcrK2dteGtldm0wTjBTTS9RTVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEVVRDQ0FqbWdBd0lCQWdJSUV3ME8vaXBXSWFZd0RRWUpLb1pJaHZjTkFRRUxCUUF3TmpFME1ESUdBMVVFCkF3d3JiM0JsYm5Ob2FXWjBMWE5sY25acFkyVXRjMlZ5ZG1sdVp5MXphV2R1WlhKQU1UYzJPVFU1TWpZek5UQWUKRncweU5qQXhNamd3T1RNd016UmFGdzB5T0RBek1qZ3dPVE13TXpWYU1EWXhOREF5QmdOVkJBTU1LMjl3Wlc1egphR2xtZEMxelpYSjJhV05sTFhObGNuWnBibWN0YzJsbmJtVnlRREUzTmprMU9USTJNelV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUM2RGdJZTRYOHM0SmtCSkpyUlgzMzZQaVB4eXZMRjhrSzgKbFhNSEhmQmx0c0JXbFBKTGdLYTNCSWw3VFE1SmJLYm8xd09JcC9oSWhUUW05L0NWWjZ3VElIeVhTZkZBS0I2RQp2b3QyVnRscTk2WHA2TlZMTndwckhudHF5RG01djlXVmRucGNTajQxWGZoYmFLMTl5SUd5ckRsUEs4YlBVWEhwCnQ5VWxRdnN5eGxBbitnYzVSSUdoTzVLTWs3TVptM2ZVcjRCeE4ySnloWGVvc25aRFdRMkxWOHA2aEFaYWZ0U08KRkJOd2c5bzZLSTNPS1A3RUliRXBGTjVBR3E1WnBaalp0NDlJWUM0UnlnMmIwSTh0Y1dXOGpibHdGQUxZcXFSWgpNVStlWG9ldmZVbCtlUjAvWjRwazdGZ0E0SDJ1NVNTaGM0M3hxcG1xaFRTeTRYYlZUL1NSQWdNQkFBR2pZekJoCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWXdYNVkKVlZ2aW9SOTgram85MnFYQXJUejE2ekFmQmdOVkhTTUVHREFXZ0JTWXdYNVlWVnZpb1I5OCtqbzkycVhBclR6MQo2ekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUjZVWHdIMHJpWHo0QmtpczZDQkZ2T0YvYzVMS25xV3ZUd1BGCnpiamNWQVMvTW9LUXVYamVVSGV2dHRDMkdDUUkxMG5CcmFKWFJJTkhrVU81TGFVMlVsQTFYei82ZmhsRjJCSksKZUprZGhxd0JxQ3I5amtISlZNZGFucGduU01DVHIrQ2FTVDNHd2ovNE1NYUh3L0ZGOG00N1ZBZFpSZ2ozZWNIdApIRnlQYkdIMW9WYmZJSmtobmJhQnBGTFZ5ZTJ1Yys3a3hkdTAzeG5qNE9UUW5DNzVqbmcxK2NtS3NZZ1VneENkCkMwM3RUWThVOUE5ZE1Sa01IaXJUdVRqcUlySUIwaFphRDR4WVNNVkhZa2RIeDhzYldyaDhsLzRDOUlCMGpRUEUKV0oyb01NT2lNamR5SGZrSGdLb0w4dUFVenR6alRmd3ZYNEVJcHhQazVseUlnRjN5Nnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/catalogd-service with
        hostname catalogd-service.openshift-catalogd.svc and is annotated to the service
        with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        catalogserver-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:31:11Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:31:11Z"
      service.beta.openshift.io/originating-service-name: catalogd-service
      service.beta.openshift.io/originating-service-uid: 3dcf0e43-116e-421b-8b5e-b77c9a5f28f0
    creationTimestamp: "2026-01-28T09:31:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"3dcf0e43-116e-421b-8b5e-b77c9a5f28f0"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:31:11Z"
    name: catalogserver-cert
    namespace: openshift-catalogd
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: catalogd-service
      uid: 3dcf0e43-116e-421b-8b5e-b77c9a5f28f0
    resourceVersion: "8424"
    uid: 137f2747-de89-413e-900b-c28162f7bfc3
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35086"
