---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBakNDQXVxZ0F3SUJBZ0lJUmc0UW1TOUcwcGN3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRGYUZ3MHlPREF4TWpnd09UTXdOREphTURFeEx6QXRCZ05WQkFNVEptMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMV052Ym5OdmJHVXRiM0JsY21GMGIzSXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd2RoSnhLcVBDb3hSMU5taGVYRXhHSnRwZVhheU1BZGkvS2d0UlhycQpzZ0t0VDY4Q25sYUVELzRzN2N4cTV6SzJMK2hRemFZWnAzWXJmR2FVTDJuVWZrcy9FK1R0Q2FWckJXM0F6WEl1CjdneFdtUWIySk5wekY5RWErU2VkQXF0T0lqTm4va3NGNWdUSkZlbnpGRjZKWmtpdzF0Mk4rNWlWdTNPbHFQbnAKUDFGUndUd2dGMzRiSDF0UUtjOHhBQXdwSE5TWW1sRzJDUFhuR1pEUmJXWDBNcksrR1dSdGdXVVp2U2prODVSYwpzcU5NTU5obm5TVFFLdmpYZThidDFHL0drQlJYK05tUDJQMTZkbnRxcXAzdWNSRHpEa1d5dXV4akhNenRnZWN3Cld1M3l1QXY4aVRFaW5ZVHB1elNFVUlaYTFrRjhVWXhLdDRLMCs2dERLZ2JFNXdJREFRQUJvNElCRnpDQ0FSTXcKRGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQwpNQUF3SFFZRFZSME9CQllFRkFVU3RXbnVYUzVFOGJGUnptZGFiVHVObmJnUk1COEdBMVVkSXdRWU1CYUFGSmpCCmZsaFZXK0toSDN6Nk9qM2FwY0N0UFBYck1HY0dBMVVkRVFSZ01GNkNKbTFsZEhKcFkzTXViM0JsYm5Ob2FXWjAKTFdOdmJuTnZiR1V0YjNCbGNtRjBiM0l1YzNaamdqUnRaWFJ5YVdOekxtOXdaVzV6YUdsbWRDMWpiMjV6YjJ4bApMVzl3WlhKaGRHOXlMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNRFVHQ3lzR0FRUUJrZ2dSWkFJQkJDWVRKRGhtCk5HVm1ZMlptTFRNeFlUTXROREUwWmkwNFpETmtMV05tTXpVM01qVXhZMlF5TXpBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFnS2pMWmIvR0srcCtIczZ0aHJSMGVMQWpsdWVTUHpBeHBIdXdrNHZPbWFRYmlGV3NnVkkyQi9tcgpuTVJVVDQxbDFVa3ZuYUY3UnROSHBSMUlaUWkvbDdVVXZrZzNJUHRzWUtvbEc1Z1JYVjBXelpnQlBLdWVQZXhVCktXTkdvaEdrRkR4M3h3RzJsMEhDRkhnNzV6SkM0Uy80NDBTQVdobEVHSVE1N0cvQ1NrNmdEY01NTjhJdFUzRDMKM201L2NKVGFITXVxblp1RkhzbXkxbkNLekFyOUhlc0pYRzRSU0NFMG4zdUhGQ1ROZW5FWVhZRDhwZzQzYVcwSgprbmdUb2Q4dzR5OWxlT1V2dml1eUJiYjE3MDhnZzNBbTBsbGZCQUhwb1R2K2dBaTdUdUFVZU9JaU1UYS9BYWh1CkU0V2FzTDlDeHVPZDhJQlMzMjFwM3BWS29obURtUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-console-operator.svc and is annotated to the service with
        annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:42Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:30:42Z"
      service.beta.openshift.io/originating-service-name: metrics
      service.beta.openshift.io/originating-service-uid: 8f4efcff-31a3-414f-8d3d-cf357251cd23
    creationTimestamp: "2026-01-28T09:30:43Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"8f4efcff-31a3-414f-8d3d-cf357251cd23"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:43Z"
    name: serving-cert
    namespace: openshift-console-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: 8f4efcff-31a3-414f-8d3d-cf357251cd23
    resourceVersion: "6744"
    uid: dd3aaf8d-c10a-4500-a974-a45bb72c79b3
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35023"
