---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnVENDQW1tZ0F3SUJBZ0lJQlZRVXAzd1ZHcDh3RFFZSktvWklodmNOQVFFTEJRQXdUakZNTUVvR0ExVUUKQXd4RGIzQmxibk5vYVdaMExXNWxkSGR2Y21zdGJtOWtaUzFwWkdWdWRHbDBlVjl1WlhSM2IzSnJMVzV2WkdVdAphV1JsYm5ScGRIa3RZMkZBTVRjMk9UVTVNalUzTVRBZUZ3MHlOakF4TWpnd09USTVNekJhRncwek5qQXhNall3Ck9USTVNekZhTUU0eFREQktCZ05WQkFNTVEyOXdaVzV6YUdsbWRDMXVaWFIzYjNKckxXNXZaR1V0YVdSbGJuUnAKZEhsZmJtVjBkMjl5YXkxdWIyUmxMV2xrWlc1MGFYUjVMV05oUURFM05qazFPVEkxTnpFd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEWTVNWTFUdlNjM1FIN2ZoeXhBbFhMSGVvOXMwZUIyTFV6CloxeE1QS1p0c2psaDc1K1lZem1jM0RhaTE2dkZaYWZENDZIUjB4bk81VFIyVGV5NS8zdHVjMFhWTGhGVGpIekwKSW1lLzY0WTlmeUtHTmx6aWZHNnVLSUFnVk5NOGVPWktnY0M5T2NaQnZKZEQ1U1ZtK21vM3JTYmhyVjJnOGtJZQpRcndKc2FtelE4QVdqMGVtK0s5bFhMblR4MDhhbmVabXFkTzB5ZzVCR1lWekUrS2g1SjcwSFE4S0YvL3U0S1U3Cks4Q1U1RE5EbFlBOHNDMFJmNkhpUk9PTE9NQjQ5WlJ5N2V5bEh0SGNXVERlWGc1Q0djenBFRk85M0tTeDM4aTgKNnQ0S0huZU5weTVnejNMQU5UZlRoTnEvTEZsYzQwQ1l3bFN6ZTBoSjc3T3ArTWcvUVM0TEFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCUkRuOUx3CmIwei9QdEFiTlVMOUluempaenJqbmpBZkJnTlZIU01FR0RBV2dCUkRuOUx3YjB6L1B0QWJOVUw5SW56alp6cmoKbmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUJ6NWgrWDJSSTNjZFpZcjdGRkVaY1gwQnUxUmRlVm8xR2ZRegpkWnhkOHZCMzlmTjdNanQyZ0UvTkhyVngzMEhXYXBHOTZrL0FNOHRGUlhnbjVSRzNGTkdQV2dKbUxuZDlhdzJRCjg0Tk5JamtzV1QyZytmRm1OM1QyYndELzcwSEtCSklLZWRFYkxRRUwxNTNFbXg3K1lVK2s3enNyMzhaOXdBWDEKclBTRVcwMmZ6RWVwNTlwQzdoMzhrU0paMXdaQVNLMlBkK25xY05hS09tOFdTK2Q5ekhwWDJkVFQ1U3FRYys0NAorZUxBYXhRR3VNRjZzMVZtaTUwU3ZGNzlPZUNWd0dVRHRpVHhnc1JyYm1WbEdJaVBMOGdYSkk2WDlkbldzdHpRCk9reEVsZEtvYVY0a01YNm9LODlpK1lJdzFCU2NlUi9DbEVnQWdGUVZmejhzc2s4c3RRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-issuer: openshift-network-node-identity_network-node-identity-ca@1769592571
      auth.openshift.io/certificate-not-after: "2036-01-26T09:29:31Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:29:30Z"
      openshift.io/owning-component: Networking / cluster-network-operator
    creationTimestamp: "2026-01-28T09:29:31Z"
    labels:
      auth.openshift.io/managed-certificate-type: signer
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:openshift.io/owning-component: {}
          f:labels:
            .: {}
            f:auth.openshift.io/managed-certificate-type: {}
        f:type: {}
      manager: network-operator
      operation: Update
      time: "2026-01-28T09:29:31Z"
    name: network-node-identity-ca
    namespace: openshift-network-node-identity
    resourceVersion: "4678"
    uid: f8b260d7-1c13-4637-8a2a-7dff7ddb7021
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnVENDQW1tZ0F3SUJBZ0lJZUt4QWZuRUNQYTh3RFFZSktvWklodmNOQVFFTEJRQXdUakZNTUVvR0ExVUUKQXd4RGIzQmxibk5vYVdaMExXNWxkSGR2Y21zdGJtOWtaUzFwWkdWdWRHbDBlVjl1WlhSM2IzSnJMVzV2WkdVdAphV1JsYm5ScGRIa3RZMkZBTVRjMk9UVTVNalUzTVRBZUZ3MHlOakF4TWpnd09USTVNekJhRncweU5qQTNNamt5Ck1USTVNekZhTUJReEVqQVFCZ05WQkFNVENURXlOeTR3TGpBdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFOZmxuNjhhNmlNZkZKU1BUVFB6aGJ4V0VvbnVSNFJybVVwTUp4QmEyalplMGhpMQpDWjZ5blFRRWpjOGdNZlhDcjlibUo3dnVnV2NUSURwZjRZQldxVDRra3pUTU9CUWIvczI0am1UbGVYbHRGcGh3CkRXNlZ2aHVYTDR5UGo3S2RPeGh5dGJScmNoQVNZNURNb2xYTVg4emF3TWovc1Q5Wmc1aWdoVVo0VXpzZVRpYkoKT3ZGSllPZkxCK1hCNHRaNVBzVlFiYytUaHdHZ09UbGhjVjQxL3NwaDlsMWZIc2h6NTZYVnpJS0JyY0ZEbHQybgo5Rm1GNEJuSmprcGRKK1M2RUpZdmZCbGg0TkNJbU0vTFZ2R0R5S0oxclpWNGRFY1JRZzlvaFVMVDk4M3ZyUWRBClYwdU16Nk5jd0VEK2l0TzZoemhMMlF3eXBWUkd3SlkwQnBDR2RBMENBd0VBQWFPQm5EQ0JtVEFPQmdOVkhROEIKQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQgovd1FDTUFBd0hRWURWUjBPQkJZRUZHVmowakNwR0lqRW13QnI3YllzMWkvRnNBdDJNQjhHQTFVZEl3UVlNQmFBCkZFT2YwdkJ2VFA4KzBCczFRdjBpZk9Obk91T2VNQm9HQTFVZEVRUVRNQkdDQ1RFeU55NHdMakF1TVljRWZ3QUEKQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUFJNVBCcnJ3YVh5ZmZnYm5jUTNyU1Nhd2Jxd1VZL0ZuWU80agpPM3ltdWpOLzMwR3dCaW9XSDJOcVBVdnc4aUZoZjRIWFNHK3c3U3hmTmQ0Zmk0RE00WkxIUjBrNmZ5MHFXdzNDCmVOUlFWbVVldU9URERiN2s1WEVQc3ZBVmMxeEE5VWpKVE41a0hyZzZrbGU3NGFsakpQL1BNTHU4ajJrU2RyVmEKNTNlZkZUNDRKYUhvekxyRmhUcU0zWFBSeTg2V3FnWllPLzBBN2I3bEhPM3kzVit4VElxTndER2tCVmZ5U2pXOQpPQUN6cTBMMERjTTBPL2taTnhBamdGQTI1R2JwY2Ztd3hyVDBOS0Zyb3FwSWsybFdTRUlseXQ2a3JnVml2YThnCjBOQ3dQeEswVW9FRWs5NFFVZjFNNWs5akxFQXFSMDB4NEMyNzdTcHJsOUpMR25UMU13PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRGdUQ0NBbW1nQXdJQkFnSUlCVlFVcDN3VkdwOHdEUVlKS29aSWh2Y05BUUVMQlFBd1RqRk1NRW9HQTFVRQpBd3hEYjNCbGJuTm9hV1owTFc1bGRIZHZjbXN0Ym05a1pTMXBaR1Z1ZEdsMGVWOXVaWFIzYjNKckxXNXZaR1V0CmFXUmxiblJwZEhrdFkyRkFNVGMyT1RVNU1qVTNNVEFlRncweU5qQXhNamd3T1RJNU16QmFGdzB6TmpBeE1qWXcKT1RJNU16RmFNRTR4VERCS0JnTlZCQU1NUTI5d1pXNXphR2xtZEMxdVpYUjNiM0pyTFc1dlpHVXRhV1JsYm5ScApkSGxmYm1WMGQyOXlheTF1YjJSbExXbGtaVzUwYVhSNUxXTmhRREUzTmprMU9USTFOekV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURZNU1ZMVR2U2MzUUg3Zmh5eEFsWExIZW85czBlQjJMVXoKWjF4TVBLWnRzamxoNzUrWVl6bWMzRGFpMTZ2RlphZkQ0NkhSMHhuTzVUUjJUZXk1LzN0dWMwWFZMaEZUakh6TApJbWUvNjRZOWZ5S0dObHppZkc2dUtJQWdWTk04ZU9aS2djQzlPY1pCdkpkRDVTVm0rbW8zclNiaHJWMmc4a0llClFyd0pzYW16UThBV2owZW0rSzlsWExuVHgwOGFuZVptcWRPMHlnNUJHWVZ6RStLaDVKNzBIUThLRi8vdTRLVTcKSzhDVTVETkRsWUE4c0MwUmY2SGlST09MT01CNDlaUnk3ZXlsSHRIY1dURGVYZzVDR2N6cEVGTzkzS1N4MzhpOAo2dDRLSG5lTnB5NWd6M0xBTlRmVGhOcS9MRmxjNDBDWXdsU3plMGhKNzdPcCtNZy9RUzRMQWdNQkFBR2pZekJoCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSRG45THcKYjB6L1B0QWJOVUw5SW56alp6cmpuakFmQmdOVkhTTUVHREFXZ0JSRG45THdiMHovUHRBYk5VTDlJbnpqWnpyagpuakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQno1aCtYMlJJM2NkWllyN0ZGRVpjWDBCdTFSZGVWbzFHZlF6CmRaeGQ4dkIzOWZON01qdDJnRS9OSHJWeDMwSFdhcEc5NmsvQU04dEZSWGduNVJHM0ZOR1BXZ0ptTG5kOWF3MlEKODROTklqa3NXVDJnK2ZGbU4zVDJid0QvNzBIS0JKSUtlZEViTFFFTDE1M0VteDcrWVUrazd6c3IzOFo5d0FYMQpyUFNFVzAyZnpFZXA1OXBDN2gzOGtTSloxd1pBU0syUGQrbnFjTmFLT204V1MrZDl6SHBYMmRUVDVTcVFjKzQ0CitlTEFheFFHdU1GNnMxVm1pNTBTdkY3OU9lQ1Z3R1VEdGlUeGdzUnJibVZsR0lpUEw4Z1hKSTZYOWRuV3N0elEKT2t4RWxkS29hVjRrTVg2b0s4OWkrWUl3MUJTY2VSL0NsRWdBZ0ZRVmZ6OHNzazhzdFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-hostnames: 127.0.0.1
      auth.openshift.io/certificate-issuer: openshift-network-node-identity_network-node-identity-ca@1769592571
      auth.openshift.io/certificate-not-after: "2026-07-29T21:29:31Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:29:30Z"
      openshift.io/owning-component: Networking / cluster-network-operator
    creationTimestamp: "2026-01-28T09:29:31Z"
    labels:
      auth.openshift.io/managed-certificate-type: target
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:auth.openshift.io/certificate-hostnames: {}
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:openshift.io/owning-component: {}
          f:labels:
            .: {}
            f:auth.openshift.io/managed-certificate-type: {}
        f:type: {}
      manager: network-operator
      operation: Update
      time: "2026-01-28T09:29:31Z"
    name: network-node-identity-cert
    namespace: openshift-network-node-identity
    resourceVersion: "4706"
    uid: 4971b509-948d-4c95-b2ca-5a018a12b6a1
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35152"
