---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVoekNDQTIrZ0F3SUJBZ0lJV1I2TGh0L0laQzB3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TlRKYUZ3MHlPREF4TWpnd09UTXdOVE5hTURreE56QTFCZ05WQkFNTUxpb3VibVYwCmQyOXlheTF0WlhSeWFXTnpMWE5sY25acFkyVXViM0JsYm5Ob2FXWjBMVzExYkhSMWN5NXpkbU13Z2dFaU1BMEcKQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNkWDZicjBwc2JSZVhXNWRMT2dnYVdhYi8xSWF4MwpKeGxzckRSeFNHN1MrSjNsb1NWdk1RaFNvaU1IbXhvZitNTW1SMWNuSjN4bUJTbjNmSWZRNTFYQjdtSnRxOHRJCk1HeWo1eXVqblVHbUVRelgwZTBNM3RCa2Q0Z2dpMW1LbWUyZkdqUVpnWWpjWkE5c1RxR0lxMFpqTkh6bHplWWEKREJQQjhOendUZDNhNjFxTVVBOHoyZUFrMklhR3QxNkkxenA4NnBaMFNYYXFXcFdwcDZvSSt1UW5xNGUxYW1jeQpjWHJFWm1MZVMwb3hKMVB2cUZrbjhzZVc4UHhqMThWbjB3RjRFWVBodk05MDIvcG1kdVQzcWJ4ZExHT0RFRHJnClUyM090enl5T3pQRUpXZDZoTGpqN3FRdDZ4UnovZkE3WUk4c2wxcUVjcnRSQll6WmJLZzdlSTJOQWdNQkFBR2oKZ2dHVU1JSUJrREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRApWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVQm9SSkt6cDA2YmpiZzY2djcrRHViQUxDVTVFd0h3WURWUjBqCkJCZ3dGb0FVbU1GK1dGVmI0cUVmZlBvNlBkcWx3SzA4OWVzd2dlTUdBMVVkRVFTQjJ6Q0IySUl1S2k1dVpYUjMKYjNKckxXMWxkSEpwWTNNdGMyVnlkbWxqWlM1dmNHVnVjMmhwWm5RdGJYVnNkSFZ6TG5OMlk0SThLaTV1WlhSMwpiM0pyTFcxbGRISnBZM010YzJWeWRtbGpaUzV2Y0dWdWMyaHBablF0YlhWc2RIVnpMbk4yWXk1amJIVnpkR1Z5CkxteHZZMkZzZ2l4dVpYUjNiM0pyTFcxbGRISnBZM010YzJWeWRtbGpaUzV2Y0dWdWMyaHBablF0YlhWc2RIVnoKTG5OMlk0STZibVYwZDI5eWF5MXRaWFJ5YVdOekxYTmxjblpwWTJVdWIzQmxibk5vYVdaMExXMTFiSFIxY3k1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQTFCZ3NyQmdFRUFaSUlFV1FDQVFRbUV5UmpaVEJqTmpZMllTMW1ZVFV4CkxUUTVZV0l0T0RjM1ppMHpNemhtTW1Ga09HWTBZakF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUYwOG9IMWMKTlE0UmowN3lSSnhMd3VtdkZDSmsrUDd5d1JIY0lJWFNGMmxHTDg5MlBpUlhyY1RPTHFpK2h1bEVoVUJ0K1BsSQovM0N5amx1MCtEdkpydGtVK0hMd09zaDc2clEybGJ6TmNVVzU3T2t2K1ZqRkVlcFRQQXBQbkNheFh5ZHgva0VHCkdOTzdxOW1DMFRLM1RNaC9sUXg0Q1o1eG9jaTBBMnM5M3FlbU53ZHJBbUJRY0JxamVFUkhVY3hHR2t3cGJYYVEKOFRua1dBOXRaT244RlFjMlBIdEhvUzcxM05vQ2NMU3ZuZkNsSWFWNGVHcWEvSmRQM3M2aVJkWFFJSlFicnJScwoxeWoxdnJUNzIzK3N4ZEVZVTJUWDFlUFBVYnRhSGVhRlZzdVN1dVorcGx1a1NDbnVNdU13QkVESjRNOE5XcDlZCnV3UW4vMkUwVDFGaTY2QT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/network-metrics-service
        with hostname network-metrics-service.openshift-multus.svc and is annotated
        to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        metrics-daemon-secret''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:53Z"
      service.alpha.openshift.io/originating-service-name: network-metrics-service
      service.alpha.openshift.io/originating-service-uid: ce0c666a-fa51-49ab-877f-338f2ad8f4b0
      service.beta.openshift.io/expiry: "2028-01-28T09:30:53Z"
    creationTimestamp: "2026-01-28T09:30:54Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"ce0c666a-fa51-49ab-877f-338f2ad8f4b0"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:54Z"
    name: metrics-daemon-secret
    namespace: openshift-multus
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: network-metrics-service
      uid: ce0c666a-fa51-49ab-877f-338f2ad8f4b0
    resourceVersion: "7431"
    uid: 036a1abc-0f57-4f1b-abde-848825b6529c
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVJRENDQXdpZ0F3SUJBZ0lJY05oVUNzTUppU1F3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TlRGYUZ3MHlPREF4TWpnd09UTXdOVEphTURzeE9UQTNCZ05WQkFNVE1HMTFiSFIxCmN5MWhaRzFwYzNOcGIyNHRZMjl1ZEhKdmJHeGxjaTV2Y0dWdWMyaHBablF0YlhWc2RIVnpMbk4yWXpDQ0FTSXcKRFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU9rTnl5NEt4RmVJQXl4TkYvTTJkUnJFakRlSgpoUFh5WFNrT2EwSGdyRzk2elB2dXFlMjgvazVpVFIzMUZkVW1GKzhIMG9heEI3U1c2UGtZb29rR25NUllaanRFClNqQk0rZmhobHNRc05mYk5HTWJBckM5VzZGYVA1NkFsZ3d2dHJsVXV3blN3dC8wUU1YOVZnLzBIL1luWXQ0Nk0KRENqRjd3NGFKSm8xc0pWNmRpdEZHemxSMHkvbWp5TkNHcHVLZWt0eXpEVjVqdnpjVGI3NU0yQXdOMGhJNHNKawpzMHhSek9nS3p5SnpPVmViVHN5TGdMbWt6MlZkUWVwTUtpVmVqamIydGh5R0luQW5IajIvMk85bVp4WDJndWNhClFCWC80Vmg5aHhoQ3QrbHRkd0NycWw1K2tlN1dLREZXODlQUVBtNWdiYldSVFd1SE9vNnh2RlI5UEFFQ0F3RUEKQWFPQ0FTc3dnZ0VuTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBTQpCZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTVW9jNXI4RFh2Y1A3aWp2dWdndlYvYXNFVTZEQWZCZ05WCkhTTUVHREFXZ0JTWXdYNVlWVnZpb1I5OCtqbzkycVhBclR6MTZ6QjdCZ05WSFJFRWREQnlnakJ0ZFd4MGRYTXQKWVdSdGFYTnphVzl1TFdOdmJuUnliMnhzWlhJdWIzQmxibk5vYVdaMExXMTFiSFIxY3k1emRtT0NQbTExYkhSMQpjeTFoWkcxcGMzTnBiMjR0WTI5dWRISnZiR3hsY2k1dmNHVnVjMmhwWm5RdGJYVnNkSFZ6TG5OMll5NWpiSFZ6CmRHVnlMbXh2WTJGc01EVUdDeXNHQVFRQmtnZ1JaQUlCQkNZVEpEVXlPRFJqTXprMUxUQTBORFF0TkRrellpMDQKT1RVNExUWTVPREE1WTJJM01tUm1NakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaUZqOUphelJFQVlPb3k5cgpHcmlnaldhZ3FGbDFaUzgvZDJJeU54d3FSZlhndEJPRWE5L29ib2d4dFE5WkdrQktqUVFGZjVzYVluZWw3T21VCmp2djlSOEd2bHJJRDNXWkVJbGtBaXF1UkJESkI5U2ZCeG5kTTI2c2QwYXhnVGZOaUJZQllhcEhaYWVwb3AxZ2YKdjh5dUY1QTRFSHNJaTV5Y2RRUUlmYVVTU2JWTU5Qc0tXSS9BNW5DM0d6STRiSDNITHBhVkVybytzdHpOdXRMYQpnc1VmSmh6UnJ2b2YxNFVkQW5KRGJOcG9DczY1SDBMcXJYWjVBUnlkODBzNFhBeEE2MzFoMXJQck5WNUNPNWEvCjd6ZTc4QytnWUVodG5HNXIrZ09OR3V4T1loVHZPWFpwV3pKZmdIRzVobmZXcjhvZFJ4Z2JWcW1BZHlZbkpTOHYKR0t0dlVRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/multus-admission-controller
        with hostname multus-admission-controller.openshift-multus.svc and is annotated
        to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        multus-admission-controller-secret''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:52Z"
      service.alpha.openshift.io/originating-service-name: multus-admission-controller
      service.alpha.openshift.io/originating-service-uid: 5284c395-0444-493b-8958-69809cb72df2
      service.beta.openshift.io/expiry: "2028-01-28T09:30:52Z"
    creationTimestamp: "2026-01-28T09:30:53Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5284c395-0444-493b-8958-69809cb72df2"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:53Z"
    name: multus-admission-controller-secret
    namespace: openshift-multus
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: multus-admission-controller
      uid: 5284c395-0444-493b-8958-69809cb72df2
    resourceVersion: "7425"
    uid: 6ab7c199-f02c-43d2-a309-228b33efd57f
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35088"
