---
apiVersion: policy/v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: "2026-01-28T09:30:42Z"
    generation: 1
    managedFields:
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:maxUnavailable: {}
          f:selector: {}
          f:unhealthyPodEvictionPolicy: {}
      manager: cluster-openshift-apiserver-operator
      operation: Update
      time: "2026-01-28T09:30:42Z"
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"DisruptionAllowed"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:observedGeneration: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:currentHealthy: {}
          f:desiredHealthy: {}
          f:disruptionsAllowed: {}
          f:expectedPods: {}
          f:observedGeneration: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2026-01-28T09:47:52Z"
    name: openshift-apiserver-pdb
    namespace: openshift-apiserver
    resourceVersion: "26111"
    uid: a849fb11-e154-42a5-b463-5b81d6d79074
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        apiserver: "true"
        app: openshift-apiserver-a
    unhealthyPodEvictionPolicy: AlwaysAllow
  status:
    conditions:
    - lastTransitionTime: "2026-01-28T09:47:52Z"
      message: ""
      observedGeneration: 1
      reason: SufficientPods
      status: "True"
      type: DisruptionAllowed
    currentHealthy: 3
    desiredHealthy: 2
    disruptionsAllowed: 1
    expectedPods: 3
    observedGeneration: 1
kind: PodDisruptionBudgetList
metadata:
  resourceVersion: "35159"
