---
apiVersion: discovery.k8s.io/v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.0.3.203
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-3-203.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: ovnkube-control-plane-74c65dbd9b-k7cjc
      namespace: openshift-ovn-kubernetes
      uid: 08d142ff-e3ef-4577-8d11-5bb7a1ff09d1
    zone: us-west-1a
  - addresses:
    - 10.0.102.200
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-102-200.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: ovnkube-control-plane-74c65dbd9b-gbdrw
      namespace: openshift-ovn-kubernetes
      uid: 9b9aa42c-8d65-4334-8af6-5f857f178fa4
    zone: us-west-1c
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:29:51Z"
    creationTimestamp: "2026-01-28T09:29:23Z"
    generateName: ovn-kubernetes-control-plane-
    generation: 5
    labels:
      app: ovnkube-control-plane
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: ovn-kubernetes-control-plane
      service.kubernetes.io/headless: ""
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
            f:service.kubernetes.io/headless: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"831be7a4-9ffe-44bd-bbf4-3c1b22ca10cd"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:29:51Z"
    name: ovn-kubernetes-control-plane-hmvnb
    namespace: openshift-ovn-kubernetes
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: ovn-kubernetes-control-plane
      uid: 831be7a4-9ffe-44bd-bbf4-3c1b22ca10cd
    resourceVersion: "5042"
    uid: 9c84b2d6-e9ba-4051-8cdd-229325deb748
  ports:
  - name: metrics
    port: 9108
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.0.102.200
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-102-200.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: ovnkube-node-92qj4
      namespace: openshift-ovn-kubernetes
      uid: 232da066-54fb-456e-b1e4-accca95c8489
    zone: us-west-1c
  - addresses:
    - 10.0.108.54
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-108-54.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: ovnkube-node-qrt9l
      namespace: openshift-ovn-kubernetes
      uid: 6c6d8063-b568-4f5d-8ba3-40bddfc0cb81
    zone: us-west-1c
  - addresses:
    - 10.0.3.203
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-3-203.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: ovnkube-node-94ppt
      namespace: openshift-ovn-kubernetes
      uid: 1f1bbf80-c985-4784-819e-8ab0bcfb1783
    zone: us-west-1a
  - addresses:
    - 10.0.78.215
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-78-215.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: ovnkube-node-shtsk
      namespace: openshift-ovn-kubernetes
      uid: 1be56885-fe62-4a33-944b-e1e0aa96276b
    zone: us-west-1c
  - addresses:
    - 10.0.101.165
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-101-165.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: ovnkube-node-58csm
      namespace: openshift-ovn-kubernetes
      uid: f1f39b29-23f5-4078-a73f-a11fb6b59b8c
    zone: us-west-1c
  - addresses:
    - 10.0.22.208
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-22-208.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: ovnkube-node-vp46d
      namespace: openshift-ovn-kubernetes
      uid: 0e4b03e6-1d17-4e78-aa13-77dcd67c90e6
    zone: us-west-1a
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:42:35Z"
    creationTimestamp: "2026-01-28T09:29:24Z"
    generateName: ovn-kubernetes-node-
    generation: 21
    labels:
      app: ovnkube-node
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: ovn-kubernetes-node
      service.kubernetes.io/headless: ""
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
            f:service.kubernetes.io/headless: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"93e62db6-8f2d-4ce5-b286-7cc18b49755b"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:42:35Z"
    name: ovn-kubernetes-node-dthg4
    namespace: openshift-ovn-kubernetes
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: ovn-kubernetes-node
      uid: 93e62db6-8f2d-4ce5-b286-7cc18b49755b
    resourceVersion: "21386"
    uid: 5eb0a2fd-c5a4-45ba-8501-6d95b31c7859
  ports:
  - name: ovn-metrics
    port: 9105
    protocol: TCP
  - name: metrics
    port: 9103
    protocol: TCP
kind: EndpointSliceList
metadata:
  resourceVersion: "35149"
