---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVORENDQXh5Z0F3SUJBZ0lJWmNyenV1eGZqZUF3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TlRGYUZ3MHlPREF4TWpnd09UTXdOVEphTUVFeFB6QTlCZ05WQkFNVE5tMWhjbXRsCmRIQnNZV05sTFc5d1pYSmhkRzl5TFcxbGRISnBZM011YjNCbGJuTm9hV1owTFcxaGNtdGxkSEJzWVdObExuTjIKWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXgzL2MrU2xDWlVOV1lFcUJQTgovY2pCWW8zTUdTa0ZrTWdMMVMwUUFNRjJlQ2VHWUNzNkN3anRZcFdsSnBjS3pSS1k1TDl3cUNoS0NYNXpKblM3Cnl2TFl6SlNJb1E5N2NSMUE0cGo0bjFOL1loaU5aNnpxOHNyangvNTExM2Uzd3k0OUVKY3phV3NuelIreG9LalYKT0tPN0hLMW5zdjN3Uzhod0tjb0gvYTgyQ0ZVZHNtaU9CMkRFVkFnYUFPc21IWHlLNk91TDh3YVBKSDlmQ3p4NQpoTEtLVWI1VStBSDBobGtjZWlOKzZNK1AxWE81K0dKVEhFTUorUlpQdnZSRVhFOUhxMURTUkRYbUt3Q002NHFtClRaeCtsL3k1NHJYbURITXZ6ZmNPNVRtSDBFbGNFSEFXejhXTlE3N3R4R2I0RXlPbXl6a25lSWVnbW1FaGZTZnoKVEFNQ0F3RUFBYU9DQVRrd2dnRTFNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRgpCUWNEQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFMREZXbHd1bFhvNUlnSGZhaWdRRUVhcHFxCk9UQWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxNnpDQmlBWURWUjBSQklHQU1INkMKTm0xaGNtdGxkSEJzWVdObExXOXdaWEpoZEc5eUxXMWxkSEpwWTNNdWIzQmxibk5vYVdaMExXMWhjbXRsZEhCcwpZV05sTG5OMlk0SkViV0Z5YTJWMGNHeGhZMlV0YjNCbGNtRjBiM0l0YldWMGNtbGpjeTV2Y0dWdWMyaHBablF0CmJXRnlhMlYwY0d4aFkyVXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dOUVlMS3dZQkJBR1NDQkZrQWdFRUpoTWsKTkdJeE9UWmtOR0l0TkdKbE1pMDBPV00wTFdFM09HSXRORGxpWW1Jd05EWTNOMkk0TUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQW4rdWFtL0RDUE5UQ29uVkJtd0NOS1NOdGtpcVZGRXVMaG5US2JXaVZtTWU4Y1ZDL1dLbzZDCkhxbEZqK1RrdjFUeC94RXJvb0cyeUlpMnNFbHhnVjA4TDgwS2xBaCtVVTN3aDcrMjIzTm1qWHFmRlp6MVNhNWUKdnE4YkUvWU5FQkxuTFdYU0w1Wm1FUkxwSTQvaEZvYlgyNkEvOTNJRlc4SGdPMld5SHVmT1IvVGluOGNtVFJJMApWNkZSY01jUGJnWFd1SnQ5aGYzZGhvSFJFdjRnMEpYQVdrbGZNQzVWVFVkcnJRV1BQQkdRRVQ1UUh4NitWTEk0Cml0bDBlTnUyYWw3di9KcHFnZktGdGNvekU2YU9QOWxqVWhibzYzK25ucHUvZTBhNzNnYTczNGNvL3JnY3haTEkKQmJWVE9leWwwMENXVGdKOUFCYS9mN2hsd05ERkpyQ2gKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/marketplace-operator-metrics
        with hostname marketplace-operator-metrics.openshift-marketplace.svc and is
        annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        marketplace-operator-metrics''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:52Z"
      service.alpha.openshift.io/originating-service-name: marketplace-operator-metrics
      service.alpha.openshift.io/originating-service-uid: 4b196d4b-4be2-49c4-a78b-49bbb04677b8
      service.beta.openshift.io/expiry: "2028-01-28T09:30:52Z"
    creationTimestamp: "2026-01-28T09:30:53Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4b196d4b-4be2-49c4-a78b-49bbb04677b8"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:53Z"
    name: marketplace-operator-metrics
    namespace: openshift-marketplace
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: marketplace-operator-metrics
      uid: 4b196d4b-4be2-49c4-a78b-49bbb04677b8
    resourceVersion: "7413"
    uid: 71d8fac4-dce0-4f84-858b-edd04d1698ee
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35135"
