---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-28T09:31:06Z"
  name: aws-ebs-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
  resourceVersion: "8056"
  uid: fb5b174e-f5e2-4904-8b17-2a77fdfe6ccd
