---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:31:27Z"
    creationTimestamp: "2026-01-28T09:31:08Z"
    labels:
      control-plane: operator-controller-controller-manager
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:control-plane: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:31:27Z"
    name: operator-controller-service
    namespace: openshift-operator-controller
    resourceVersion: "9250"
    uid: 5406751b-cd01-494b-baa5-1fcf96bb494a
  subsets:
  - addresses:
    - ip: 10.128.0.11
      nodeName: ip-10-0-3-203.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: operator-controller-controller-manager-66b6b87dc7-msqnr
        namespace: openshift-operator-controller
        uid: 75990848-0e55-4d04-99b3-d3df286a47c8
    ports:
    - name: https
      port: 8443
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "35156"
