---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVTakNDQXpLZ0F3SUJBZ0lJVUpPUjhlT21TWlF3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE14TURkYUZ3MHlPREF4TWpnd09UTXhNRGhhTUVneFJqQkVCZ05WQkFNVFBXOXdaWEpoCmRHOXlMV052Ym5SeWIyeHNaWEl0YzJWeWRtbGpaUzV2Y0dWdWMyaHBablF0YjNCbGNtRjBiM0l0WTI5dWRISnYKYkd4bGNpNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFUvT3E5cXc0bApjS0ZGTWdUc0lzaWJYbHJtTktpSWRGSzc1elJlMEUrQWV5S3ZsbnF4U24zdFVqcGtKM3NheXExSGxkQWtUeVl6ClFaK0VaZ29hc0hxVjNKOUhUd3p0bXFOOWF0QnpRWkVhSjhmV0p3SjZRYVJQUXAyV0UvREpZVE4vUG4yK2d1Y2sKZjFkcFZBeVBUVmU2Yk5EZXlmYUpZYnN1QXhScys2Z3NVS0J4eER5L28vV2UyQWZHU09MajlTQXZoWXFOeG55QwpQS2hHLzJLdmVsU3d3OFJZUWNod3dVaU0vZzdqZVJ6dVpDVGZrUUtTTkx1bmtqdjI4TDZ5Zzd2WnQxUWNsS1BDCjRlU082Und3dnU5UzA4RVQ0WnhxWitEd24wcHlGQ1RsUm5ab3ZPK29GWURuK0Q3TVZxUHFPbFVYNnJMWVhlZE4KL2pzeVZKeXU4TnVEQWdNQkFBR2pnZ0ZJTUlJQlJEQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3dwpDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVrTVkxMUlLQUluenE5YVR5CndnN0pGZFVNemJJd0h3WURWUjBqQkJnd0ZvQVVtTUYrV0ZWYjRxRWZmUG82UGRxbHdLMDg5ZXN3Z1pjR0ExVWQKRVFTQmp6Q0JqSUk5YjNCbGNtRjBiM0l0WTI5dWRISnZiR3hsY2kxelpYSjJhV05sTG05d1pXNXphR2xtZEMxdgpjR1Z5WVhSdmNpMWpiMjUwY205c2JHVnlMbk4yWTRKTGIzQmxjbUYwYjNJdFkyOXVkSEp2Ykd4bGNpMXpaWEoyCmFXTmxMbTl3Wlc1emFHbG1kQzF2Y0dWeVlYUnZjaTFqYjI1MGNtOXNiR1Z5TG5OMll5NWpiSFZ6ZEdWeUxteHYKWTJGc01EVUdDeXNHQVFRQmtnZ1JaQUlCQkNZVEpESmlaVFUxTm1ZMkxXWXhNV1V0TkROaE1DMDRZVGd4TFRVNApZV1F3WmpsaU1USTNNREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBSldwbWRyczM1dXZRVnNiYjlka1NsaXFvCmsrdEdNOHlwMVVUTnpuUUNhTEdadFdQZThWMnMycTJPYnEwaUxRSlZRMGdvV3F1UG1pT1JlYUFSK1Y1dnhYcDQKQXNvdHBjTVh6cHhxMmhGaDFKSkFIcENlMzUvL0RnOG9EWEQxRFQzRC9MY1hXQkR6clFjNXVhTTRzNVcwcWJRMgpxcitCcldEYWhmdVRVVnNIOW93RzA3dFozeVF5bUc1NERmTSs1eWtGZDRac3p1bXZLWVkyc2Z4T3NXNEgxSmFZCm5SY1NNbWFQcDZiMk1zejhuQk91aGlCMEI5Zjk2a1BnWTRoRFgyMzhhczNCWExkRXo4dXE0MVNsWHdOL25maVAKclo4aEJYVzM1cDU5NnNOVUNscUpDRnp6bHk2Y0tva0lWdVFzcVB3SHBWV2tQcTJ6MFU3VGdJd0FBRUZ3QUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEVVRDQ0FqbWdBd0lCQWdJSUV3ME8vaXBXSWFZd0RRWUpLb1pJaHZjTkFRRUxCUUF3TmpFME1ESUdBMVVFCkF3d3JiM0JsYm5Ob2FXWjBMWE5sY25acFkyVXRjMlZ5ZG1sdVp5MXphV2R1WlhKQU1UYzJPVFU1TWpZek5UQWUKRncweU5qQXhNamd3T1RNd016UmFGdzB5T0RBek1qZ3dPVE13TXpWYU1EWXhOREF5QmdOVkJBTU1LMjl3Wlc1egphR2xtZEMxelpYSjJhV05sTFhObGNuWnBibWN0YzJsbmJtVnlRREUzTmprMU9USTJNelV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUM2RGdJZTRYOHM0SmtCSkpyUlgzMzZQaVB4eXZMRjhrSzgKbFhNSEhmQmx0c0JXbFBKTGdLYTNCSWw3VFE1SmJLYm8xd09JcC9oSWhUUW05L0NWWjZ3VElIeVhTZkZBS0I2RQp2b3QyVnRscTk2WHA2TlZMTndwckhudHF5RG01djlXVmRucGNTajQxWGZoYmFLMTl5SUd5ckRsUEs4YlBVWEhwCnQ5VWxRdnN5eGxBbitnYzVSSUdoTzVLTWs3TVptM2ZVcjRCeE4ySnloWGVvc25aRFdRMkxWOHA2aEFaYWZ0U08KRkJOd2c5bzZLSTNPS1A3RUliRXBGTjVBR3E1WnBaalp0NDlJWUM0UnlnMmIwSTh0Y1dXOGpibHdGQUxZcXFSWgpNVStlWG9ldmZVbCtlUjAvWjRwazdGZ0E0SDJ1NVNTaGM0M3hxcG1xaFRTeTRYYlZUL1NSQWdNQkFBR2pZekJoCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWXdYNVkKVlZ2aW9SOTgram85MnFYQXJUejE2ekFmQmdOVkhTTUVHREFXZ0JTWXdYNVlWVnZpb1I5OCtqbzkycVhBclR6MQo2ekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUjZVWHdIMHJpWHo0QmtpczZDQkZ2T0YvYzVMS25xV3ZUd1BGCnpiamNWQVMvTW9LUXVYamVVSGV2dHRDMkdDUUkxMG5CcmFKWFJJTkhrVU81TGFVMlVsQTFYei82ZmhsRjJCSksKZUprZGhxd0JxQ3I5amtISlZNZGFucGduU01DVHIrQ2FTVDNHd2ovNE1NYUh3L0ZGOG00N1ZBZFpSZ2ozZWNIdApIRnlQYkdIMW9WYmZJSmtobmJhQnBGTFZ5ZTJ1Yys3a3hkdTAzeG5qNE9UUW5DNzVqbmcxK2NtS3NZZ1VneENkCkMwM3RUWThVOUE5ZE1Sa01IaXJUdVRqcUlySUIwaFphRDR4WVNNVkhZa2RIeDhzYldyaDhsLzRDOUlCMGpRUEUKV0oyb01NT2lNamR5SGZrSGdLb0w4dUFVenR6alRmd3ZYNEVJcHhQazVseUlnRjN5Nnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/operator-controller-service
        with hostname operator-controller-service.openshift-operator-controller.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        operator-controller-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:31:08Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:31:08Z"
      service.beta.openshift.io/originating-service-name: operator-controller-service
      service.beta.openshift.io/originating-service-uid: 2be556f6-f11e-43a0-8a81-58ad0f9b1270
    creationTimestamp: "2026-01-28T09:31:08Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"2be556f6-f11e-43a0-8a81-58ad0f9b1270"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:31:08Z"
    name: operator-controller-cert
    namespace: openshift-operator-controller
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: operator-controller-service
      uid: 2be556f6-f11e-43a0-8a81-58ad0f9b1270
    resourceVersion: "8266"
    uid: 60264729-da57-4e47-aa7a-d5e78dc87804
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35156"
