---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:24:52Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: cluster-version-operator
    operation: Update
    time: "2026-01-28T10:24:09Z"
  name: version
  namespace: openshift-cluster-version
  resourceVersion: "34745"
  uid: e58d7e17-bb1e-4203-b503-730d12000f87
spec:
  acquireTime: "2026-01-28T09:39:57.180698Z"
  holderIdentity: ip-10-0-108-54_9bec53ab-c179-4c1d-8361-de4218a41799
  leaseDurationSeconds: 137
  leaseTransitions: 3
  renewTime: "2026-01-28T10:24:09.985181Z"
