---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:29:45Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: ovnkube-identity
    operation: Update
    time: "2026-01-28T10:24:26Z"
  name: ovnkube-identity
  namespace: openshift-network-node-identity
  resourceVersion: "34828"
  uid: 444fb422-436f-4a69-af76-e0a920f40fe2
spec:
  acquireTime: "2026-01-28T09:29:45.083268Z"
  holderIdentity: ip-10-0-102-200_7978caa9-983f-4714-a0d8-7a4f36fdfc9b
  leaseDurationSeconds: 60
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:26.256568Z"
