---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:31:07Z"
    creationTimestamp: "2026-01-28T09:26:13Z"
    labels:
      app: openshift-config-operator
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:31:07Z"
    name: metrics
    namespace: openshift-config-operator
    resourceVersion: "8164"
    uid: ce650870-c5c3-42a6-b702-74038dfd0cb0
  subsets:
  - addresses:
    - ip: 10.130.0.26
      nodeName: ip-10-0-108-54.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: openshift-config-operator-6ddf5984bb-xrwj6
        namespace: openshift-config-operator
        uid: bc858188-182a-4ed1-92e2-1dd511bd8028
    ports:
    - name: https
      port: 8443
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "34977"
