---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQvekNDQXVlZ0F3SUJBZ0lJUmJkRUhnYjFHcGd3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRGYUZ3MHlPREF4TWpnd09UTXdOREphTURBeExqQXNCZ05WQkFNVEpXMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMV052Ym1acFp5MXZjR1Z5WVhSdmNpNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURQaS9CdGdKUFJ2cFIzY3BUNEpTMHBJdlNDMFJxaU0xMkNMUSsrRS83eApXTERUekhTRXExOU9sL2pMSUV5RWZIeC9QMHpMTlhZaGkvL3ZmdkpVaytJaXp0d1I3d25hTUFDZ01nc09qSy9pCjhrRGZzZUtUQ2FFSm5DL3Q4dlFJb1ZQUDN3YUEyOUowTnFaUmtMSWFQQWNuc3d4dVBBUzVtdFRWWjl0SUJ3VjUKUS9WMHdXZDRTSlJzWkhtelhWMDhKdm5WTGhVTFVHcUNRdE0zZ01XMXh1MXo5OFVuS2tVejU5MjRXRGFnNkkxSQpEMWJ3NmJUeklWSGVvK1lBU0laVEY5UkdGOFc0cTNEOVF1SnkvR3cvODROaGNiQTE1Z2tyOWQ3R3ZLWWhSZTNRCk9zeTdIaHlmdVMyWFlFVXIzZFlSNHo2VzJNdEFRb3FkSExBWml1OVc5N2psQWdNQkFBR2pnZ0VWTUlJQkVUQU8KQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJdwpBREFkQmdOVkhRNEVGZ1FVdzlQQ3ppcnQxQnozUllhYmt5K0ZHVk5uVGt3d0h3WURWUjBqQkJnd0ZvQVVtTUYrCldGVmI0cUVmZlBvNlBkcWx3SzA4OWVzd1pRWURWUjBSQkY0d1hJSWxiV1YwY21samN5NXZjR1Z1YzJocFpuUXQKWTI5dVptbG5MVzl3WlhKaGRHOXlMbk4yWTRJemJXVjBjbWxqY3k1dmNHVnVjMmhwWm5RdFkyOXVabWxuTFc5dwpaWEpoZEc5eUxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01EVUdDeXNHQVFRQmtnZ1JaQUlCQkNZVEpHRXhPREkxCk1qUXdMV1V5WVRNdE5HVXpPUzFoTnpkaUxXVTJNelF5TkdZd01tTTVNekFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQW9tSEd4T2xkRlArMzg3NkhiMHM3K0lpN2FaTUpCcDdkbWIzRzVaV290UE1ZUmpTZ2loNHNZWksvVnkvSApZemhESlNpbjJMNlJUT1FVNC9NNjZwZU9Vb1BxUWwzcnJFR3FwYlREV3NMMXFRcXlwSkpiNDBKQU1MWTJiWDVvCmxGNGtPRE9FZXZOaFZQU0FvZUR3MTdHaUVRbjQvYnB5WVdma25ncmZlN3FadHJFS3J4UVF3a0FFYVo1Ti96UVQKNGVvSDg0T2U3YUJrcGh2MHRrSGdFSW12LzNnK1h0NndicVg5Y0k2ZjQrdmYxQ3VVNE9VVDB2QWhJbXEyYUEzYgpqMUZ1Wm1iakhRL0tCZTQyUXFhczNvNUlwNDQwT0xuOFFSWHpBd28vMTd6YjlYOWY2ZHloT2VZbHhxa29CRUlHCnF1UWtqNDUrek9KUkFDV2tJa0tKc1Q5cG13PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-config-operator.svc and is annotated to the service with
        annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        config-operator-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:42Z"
      service.alpha.openshift.io/originating-service-name: metrics
      service.alpha.openshift.io/originating-service-uid: a1825240-e2a3-4e39-a77b-e63424f02c93
      service.beta.openshift.io/expiry: "2028-01-28T09:30:42Z"
    creationTimestamp: "2026-01-28T09:30:43Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a1825240-e2a3-4e39-a77b-e63424f02c93"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:43Z"
    name: config-operator-serving-cert
    namespace: openshift-config-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: a1825240-e2a3-4e39-a77b-e63424f02c93
    resourceVersion: "6734"
    uid: c0843450-30a8-4cda-beaf-52b79da983f5
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "34977"
