---
apiVersion: policy/v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: "2026-01-28T09:31:59Z"
    generation: 1
    managedFields:
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:maxUnavailable: {}
          f:selector: {}
      manager: csi-snapshot-controller-operator
      operation: Update
      time: "2026-01-28T09:31:59Z"
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"DisruptionAllowed"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:observedGeneration: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:currentHealthy: {}
          f:desiredHealthy: {}
          f:disruptionsAllowed: {}
          f:expectedPods: {}
          f:observedGeneration: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2026-01-28T09:32:23Z"
    name: csi-snapshot-controller-pdb
    namespace: openshift-cluster-storage-operator
    resourceVersion: "11647"
    uid: b21cd21e-e123-4116-b05b-cf77a8b1e2ef
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app: csi-snapshot-controller
  status:
    conditions:
    - lastTransitionTime: "2026-01-28T09:32:23Z"
      message: ""
      observedGeneration: 1
      reason: SufficientPods
      status: "True"
      type: DisruptionAllowed
    currentHealthy: 2
    desiredHealthy: 1
    disruptionsAllowed: 1
    expectedPods: 2
    observedGeneration: 1
kind: PodDisruptionBudgetList
metadata:
  resourceVersion: "35033"
