---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  creationTimestamp: "2026-01-28T09:42:47Z"
  generation: 1
  labels:
    app.kubernetes.io/component: monitoring-plugin
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: monitoring-plugin
    app.kubernetes.io/part-of: openshift-monitoring
  managedFields:
  - apiVersion: console.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
      f:spec:
        .: {}
        f:backend:
          .: {}
          f:service:
            .: {}
            f:basePath: {}
            f:name: {}
            f:namespace: {}
            f:port: {}
          f:type: {}
        f:displayName: {}
        f:i18n:
          .: {}
          f:loadType: {}
    manager: operator
    operation: Update
    time: "2026-01-28T09:42:47Z"
  name: monitoring-plugin
  resourceVersion: "22158"
  uid: 8aa91b51-5ed7-492a-b5a1-a8c6442f8140
spec:
  backend:
    service:
      basePath: /
      name: monitoring-plugin
      namespace: openshift-monitoring
      port: 9443
    type: Service
  displayName: monitoring-plugin
  i18n:
    loadType: Preload
