---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:42:15Z"
    creationTimestamp: "2026-01-28T09:26:11Z"
    labels:
      endpoints.kubernetes.io/managed-by: endpoint-controller
      k8s-app: kube-rbac-proxy-crio
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:endpoints.kubernetes.io/managed-by: {}
            f:k8s-app: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:42:15Z"
    name: kube-rbac-proxy-crio
    namespace: openshift-machine-config-operator
    resourceVersion: "20864"
    uid: b24b9085-df69-4174-be73-147a337d5a64
  subsets:
  - addresses:
    - ip: 10.0.101.165
      nodeName: ip-10-0-101-165.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: kube-rbac-proxy-crio-ip-10-0-101-165.us-west-1.compute.internal
        namespace: openshift-machine-config-operator
        uid: e94894f3-6eed-4fa6-84af-0b82b3f9dfe7
    - ip: 10.0.102.200
      nodeName: ip-10-0-102-200.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: kube-rbac-proxy-crio-ip-10-0-102-200.us-west-1.compute.internal
        namespace: openshift-machine-config-operator
        uid: 2c791061-454d-4e4c-836f-6a1edebf15f0
    - ip: 10.0.108.54
      nodeName: ip-10-0-108-54.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: kube-rbac-proxy-crio-ip-10-0-108-54.us-west-1.compute.internal
        namespace: openshift-machine-config-operator
        uid: 204cd860-764a-4171-ae43-ddc23a51d7a2
    - ip: 10.0.22.208
      nodeName: ip-10-0-22-208.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: kube-rbac-proxy-crio-ip-10-0-22-208.us-west-1.compute.internal
        namespace: openshift-machine-config-operator
        uid: 73389fce-f43a-445d-b566-b85c84bd4fb7
    - ip: 10.0.3.203
      nodeName: ip-10-0-3-203.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: kube-rbac-proxy-crio-ip-10-0-3-203.us-west-1.compute.internal
        namespace: openshift-machine-config-operator
        uid: a2b99556-c586-4845-8d90-9318dc7db950
    - ip: 10.0.78.215
      nodeName: ip-10-0-78-215.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: kube-rbac-proxy-crio-ip-10-0-78-215.us-west-1.compute.internal
        namespace: openshift-machine-config-operator
        uid: 7d3aac80-dd14-4e87-a6fa-22c3583017a5
    ports:
    - name: metrics
      port: 9637
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:32:23Z"
    creationTimestamp: "2026-01-28T09:26:09Z"
    labels:
      endpoints.kubernetes.io/managed-by: endpoint-controller
      k8s-app: machine-config-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:endpoints.kubernetes.io/managed-by: {}
            f:k8s-app: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:32:23Z"
    name: machine-config-controller
    namespace: openshift-machine-config-operator
    resourceVersion: "11662"
    uid: 403a3058-acaa-424e-8a68-03a9ad852154
  subsets:
  - addresses:
    - ip: 10.128.0.26
      nodeName: ip-10-0-3-203.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-controller-684d9b9c86-l4lpq
        namespace: openshift-machine-config-operator
        uid: 0b87ee4a-4977-4279-af7e-08099d08d7b3
    ports:
    - name: metrics
      port: 9001
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:41:55Z"
    creationTimestamp: "2026-01-28T09:26:10Z"
    labels:
      endpoints.kubernetes.io/managed-by: endpoint-controller
      k8s-app: machine-config-daemon
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:endpoints.kubernetes.io/managed-by: {}
            f:k8s-app: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:41:55Z"
    name: machine-config-daemon
    namespace: openshift-machine-config-operator
    resourceVersion: "20063"
    uid: 24b832dc-8fa4-43a4-9c15-e60260eeea2d
  subsets:
  - addresses:
    - ip: 10.0.101.165
      nodeName: ip-10-0-101-165.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-daemon-jjdw6
        namespace: openshift-machine-config-operator
        uid: 46262c23-f994-47c6-ae13-cfe2d3ace1e1
    - ip: 10.0.102.200
      nodeName: ip-10-0-102-200.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-daemon-4tjc6
        namespace: openshift-machine-config-operator
        uid: 4ee1c05d-1237-480f-aeef-086b9a8fd013
    - ip: 10.0.108.54
      nodeName: ip-10-0-108-54.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-daemon-qhq7x
        namespace: openshift-machine-config-operator
        uid: b8bf1d6e-af25-4524-8ea5-b058d378a7ff
    - ip: 10.0.22.208
      nodeName: ip-10-0-22-208.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-daemon-bkv6x
        namespace: openshift-machine-config-operator
        uid: 1360b1ee-c8c0-4165-8d6b-d7adf97dc419
    - ip: 10.0.3.203
      nodeName: ip-10-0-3-203.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-daemon-7ddbq
        namespace: openshift-machine-config-operator
        uid: 2f896487-edc6-4544-8765-eded51871519
    - ip: 10.0.78.215
      nodeName: ip-10-0-78-215.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-daemon-w7kk4
        namespace: openshift-machine-config-operator
        uid: ea051c1b-e02f-4765-8852-79ea834d1997
    ports:
    - name: metrics
      port: 9001
      protocol: TCP
    - name: health
      port: 8798
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:31:53Z"
    creationTimestamp: "2026-01-28T09:26:09Z"
    labels:
      endpoints.kubernetes.io/managed-by: endpoint-controller
      k8s-app: machine-config-operator
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:endpoints.kubernetes.io/managed-by: {}
            f:k8s-app: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:31:53Z"
    name: machine-config-operator
    namespace: openshift-machine-config-operator
    resourceVersion: "9755"
    uid: b92b81a7-2b15-400e-b75a-a4db01effe14
  subsets:
  - addresses:
    - ip: 10.130.0.36
      nodeName: ip-10-0-108-54.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-operator-84ddcf457d-wrwhn
        namespace: openshift-machine-config-operator
        uid: 89e78dd4-ea8d-4f5e-8672-d000fbcdfaca
    ports:
    - name: metrics
      port: 9001
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:32:27Z"
    creationTimestamp: "2026-01-28T09:26:11Z"
    labels:
      endpoints.kubernetes.io/managed-by: endpoint-controller
      k8s-app: machine-config-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:endpoints.kubernetes.io/managed-by: {}
            f:k8s-app: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:32:27Z"
    name: machine-config-server
    namespace: openshift-machine-config-operator
    resourceVersion: "11824"
    uid: 6e43406d-df5e-4a8d-9d63-730f143abd92
  subsets:
  - addresses:
    - ip: 10.0.102.200
      nodeName: ip-10-0-102-200.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-server-qlftk
        namespace: openshift-machine-config-operator
        uid: 15136cdc-b805-4645-935e-c13390189bfe
    - ip: 10.0.108.54
      nodeName: ip-10-0-108-54.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-server-6mw62
        namespace: openshift-machine-config-operator
        uid: 2511186f-e8f7-4188-8a1c-0a009c3ac19c
    - ip: 10.0.3.203
      nodeName: ip-10-0-3-203.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: machine-config-server-759xv
        namespace: openshift-machine-config-operator
        uid: 936d95e1-0689-4cb5-9439-83a2e28b1575
    ports:
    - name: https
      port: 22623
      protocol: TCP
    - name: http
      port: 22624
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "35117"
