---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQTlHZ0F3SUJBZ0lJTXJQL0wvSmo2Umd3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpsYUZ3MHlPREF4TWpnd09UTXdOREJhTUV3eFNqQklCZ05WQkFNTVFTb3VibTlrClpTMTBkVzVwYm1jdGIzQmxjbUYwYjNJdWIzQmxibk5vYVdaMExXTnNkWE4wWlhJdGJtOWtaUzEwZFc1cGJtY3QKYjNCbGNtRjBiM0l1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBb3RuRgphbS82SWt2Z0RiMTk1SmlQTFJCOEdrNkZrS09nZmxFMjRDeWVFa2lKc3BNMlRjT2w2aEF3bXYvTlVBZ3JIRjBkCnV3RnovcEZjbVMveTNKZEhHdmJORDk4TGErYXdVN1ZoZythdjNMUnpaWmpjVU9NcVU3eFlQK0NDdW02c2FPQ2QKLzN0RTB2N1JBZmx6ZHdEMkxKd2F3SktMMTlvekJ1a1ZxUGlIVHJOd3R5VDRtNVljMUpiVUxRTnh5TlNiY3JudAp0Rk5zZkttdmZrZ2xQb3YzTmJGZ0xQVEErZ1NDaGpSc1YwK2JQb0dUTmJIZFpYbEZiYTV2YVA2bi82ckdPNWxPCkJsYy8vMkEreXpvY3htejI2Ymc0b2ZjQmdtZ2FTQUZhdVVpai93cHBUbHlBa3JtRzJJeWxsV0VVMC8yblNrQkIKS3o0TWFpTGllaHp2VC9qN1VRSURBUUFCbzRJQjR6Q0NBZDh3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZApKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkJXZmFXN2FkZ2xnClNFU2VhN2x4ZHovSEF1Q3pNQjhHQTFVZEl3UVlNQmFBRkpqQmZsaFZXK0toSDN6Nk9qM2FwY0N0UFBYck1JSUIKTVFZRFZSMFJCSUlCS0RDQ0FTU0NRU291Ym05a1pTMTBkVzVwYm1jdGIzQmxjbUYwYjNJdWIzQmxibk5vYVdaMApMV05zZFhOMFpYSXRibTlrWlMxMGRXNXBibWN0YjNCbGNtRjBiM0l1YzNaamdrOHFMbTV2WkdVdGRIVnVhVzVuCkxXOXdaWEpoZEc5eUxtOXdaVzV6YUdsbWRDMWpiSFZ6ZEdWeUxXNXZaR1V0ZEhWdWFXNW5MVzl3WlhKaGRHOXkKTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzZ2o5dWIyUmxMWFIxYm1sdVp5MXZjR1Z5WVhSdmNpNXZjR1Z1YzJocApablF0WTJ4MWMzUmxjaTF1YjJSbExYUjFibWx1WnkxdmNHVnlZWFJ2Y2k1emRtT0NUVzV2WkdVdGRIVnVhVzVuCkxXOXdaWEpoZEc5eUxtOXdaVzV6YUdsbWRDMWpiSFZ6ZEdWeUxXNXZaR1V0ZEhWdWFXNW5MVzl3WlhKaGRHOXkKTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTURVR0N5c0dBUVFCa2dnUlpBSUJCQ1lUSkdGaU5USmxOR1F5TFdJMApaVFl0TkRFMFlpMDVNbUpoTFdWaE5EbGtZVGc0TnpOaFl6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFmL29mClRETitnSXJXeTlrL3VxMWl2QXN3LzNkanIveUd0WWlJNS9uK2dDL0hxay9udDlaakdCVnlyemJvQTZTNUpJQUEKVUZzSW1NNytwWDBsMGlFN3ptN3ptZXZlSmpjRG4ra0IyODdiY0JUSlZ0Q2JkVTRHTTRLZ3FBRWtmU1l2cTVEMwpwV1FLaXFaYXRSSktVUmRUVDZFSGE1eTNhMFREY2FBd05wRWJzVHhNTE5IZ0ZCS0ZJRUM2RDBReklzRWV2SWxQClBKS1k3U2tCME5vL3lzMEtVelZrckdXUVNCUHowbEprWDI1VjlJTGFXWjFDckE0alAzc2VFOFk5clBTRHh5TDAKbXJ5Z3hoN251RC8rdVdHb0Y3cTkyWXhMN2N3ZXhWd1lrNElyWTFSTjRZVThhYVRoTzl2aWNUcmphT2tmSDdpSQpzRjNsMmdDM1Y3RTVNQTBrNnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEVVRDQ0FqbWdBd0lCQWdJSUV3ME8vaXBXSWFZd0RRWUpLb1pJaHZjTkFRRUxCUUF3TmpFME1ESUdBMVVFCkF3d3JiM0JsYm5Ob2FXWjBMWE5sY25acFkyVXRjMlZ5ZG1sdVp5MXphV2R1WlhKQU1UYzJPVFU1TWpZek5UQWUKRncweU5qQXhNamd3T1RNd016UmFGdzB5T0RBek1qZ3dPVE13TXpWYU1EWXhOREF5QmdOVkJBTU1LMjl3Wlc1egphR2xtZEMxelpYSjJhV05sTFhObGNuWnBibWN0YzJsbmJtVnlRREUzTmprMU9USTJNelV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUM2RGdJZTRYOHM0SmtCSkpyUlgzMzZQaVB4eXZMRjhrSzgKbFhNSEhmQmx0c0JXbFBKTGdLYTNCSWw3VFE1SmJLYm8xd09JcC9oSWhUUW05L0NWWjZ3VElIeVhTZkZBS0I2RQp2b3QyVnRscTk2WHA2TlZMTndwckhudHF5RG01djlXVmRucGNTajQxWGZoYmFLMTl5SUd5ckRsUEs4YlBVWEhwCnQ5VWxRdnN5eGxBbitnYzVSSUdoTzVLTWs3TVptM2ZVcjRCeE4ySnloWGVvc25aRFdRMkxWOHA2aEFaYWZ0U08KRkJOd2c5bzZLSTNPS1A3RUliRXBGTjVBR3E1WnBaalp0NDlJWUM0UnlnMmIwSTh0Y1dXOGpibHdGQUxZcXFSWgpNVStlWG9ldmZVbCtlUjAvWjRwazdGZ0E0SDJ1NVNTaGM0M3hxcG1xaFRTeTRYYlZUL1NSQWdNQkFBR2pZekJoCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWXdYNVkKVlZ2aW9SOTgram85MnFYQXJUejE2ekFmQmdOVkhTTUVHREFXZ0JTWXdYNVlWVnZpb1I5OCtqbzkycVhBclR6MQo2ekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUjZVWHdIMHJpWHo0QmtpczZDQkZ2T0YvYzVMS25xV3ZUd1BGCnpiamNWQVMvTW9LUXVYamVVSGV2dHRDMkdDUUkxMG5CcmFKWFJJTkhrVU81TGFVMlVsQTFYei82ZmhsRjJCSksKZUprZGhxd0JxQ3I5amtISlZNZGFucGduU01DVHIrQ2FTVDNHd2ovNE1NYUh3L0ZGOG00N1ZBZFpSZ2ozZWNIdApIRnlQYkdIMW9WYmZJSmtobmJhQnBGTFZ5ZTJ1Yys3a3hkdTAzeG5qNE9UUW5DNzVqbmcxK2NtS3NZZ1VneENkCkMwM3RUWThVOUE5ZE1Sa01IaXJUdVRqcUlySUIwaFphRDR4WVNNVkhZa2RIeDhzYldyaDhsLzRDOUlCMGpRUEUKV0oyb01NT2lNamR5SGZrSGdLb0w4dUFVenR6alRmd3ZYNEVJcHhQazVseUlnRjN5Nnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/node-tuning-operator
        with hostname node-tuning-operator.openshift-cluster-node-tuning-operator.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        node-tuning-operator-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:40Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:30:40Z"
      service.beta.openshift.io/originating-service-name: node-tuning-operator
      service.beta.openshift.io/originating-service-uid: ab52e4d2-b4e6-414b-92ba-ea49da8873ac
    creationTimestamp: "2026-01-28T09:30:41Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"ab52e4d2-b4e6-414b-92ba-ea49da8873ac"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:41Z"
    name: node-tuning-operator-tls
    namespace: openshift-cluster-node-tuning-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: node-tuning-operator
      uid: ab52e4d2-b4e6-414b-92ba-ea49da8873ac
    resourceVersion: "6615"
    uid: 3403c391-62e9-4a28-8a3e-210b5ad75d1e
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVlakNDQTJLZ0F3SUJBZ0lJWEExRjNKcCtPWkl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpsYUZ3MHlPREF4TWpnd09UTXdOREJhTUZneFZqQlVCZ05WQkFNVFRYQmxjbVp2CmNtMWhibU5sTFdGa1pHOXVMVzl3WlhKaGRHOXlMWE5sY25acFkyVXViM0JsYm5Ob2FXWjBMV05zZFhOMFpYSXQKYm05a1pTMTBkVzVwYm1jdGIzQmxjbUYwYjNJdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QQpNSUlCQ2dLQ0FRRUEwNGxMUW15UWRRaHBQajZ1U0pSVU1US0VOMiszNXcyWmExQzFnbUZoZzlIOUx0ZWw4emoyCmRsbmRVd0lmNGJwelQ0b05KeXliYlVabWN4RWpBZUp0VlBtNmJiT0pwOURtcW4rSjBNNFR0eGlOL2xXbFJHRUwKRmhKY3FZVzM3Z1ZNUDJ0QWl6ODN5cVR0djA5U0loZGpIbDJ1SWVWeUlYbVF2MjVudlhXWFY4YSs4SXlUR0QvTgphRmk5K1ovbDN0Z1NWMEt4dUJ4ZkhFZmU3RHNQSFQ4MWpKSktySjBEZnZXQmpiLzNlSDFqMy92OWhSQTRIQXBVCkJzYXRiMW5GUnAwQjNOTjhNVkZJVnIyV1U1SUlJWXZ4NytWb2dWUHlKZXp2MjVZbjlnaGU1V094K2xjSFpYL1QKbzBjZ01JZ1ZRalp4SXpidVNaV2d4NS9abUo4UzBpbDF0UUlEQVFBQm80SUJhRENDQVdRd0RnWURWUjBQQVFILwpCQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPCkJCWUVGQlI1RWh5aENqMFd4dUxWQUdJQUQ5c3pWWEZXTUI4R0ExVWRJd1FZTUJhQUZKakJmbGhWVytLaEgzejYKT2ozYXBjQ3RQUFhyTUlHM0JnTlZIUkVFZ2E4d2dheUNUWEJsY21admNtMWhibU5sTFdGa1pHOXVMVzl3WlhKaApkRzl5TFhObGNuWnBZMlV1YjNCbGJuTm9hV1owTFdOc2RYTjBaWEl0Ym05a1pTMTBkVzVwYm1jdGIzQmxjbUYwCmIzSXVjM1pqZ2x0d1pYSm1iM0p0WVc1alpTMWhaR1J2YmkxdmNHVnlZWFJ2Y2kxelpYSjJhV05sTG05d1pXNXoKYUdsbWRDMWpiSFZ6ZEdWeUxXNXZaR1V0ZEhWdWFXNW5MVzl3WlhKaGRHOXlMbk4yWXk1amJIVnpkR1Z5TG14dgpZMkZzTURVR0N5c0dBUVFCa2dnUlpBSUJCQ1lUSkRZNFlXTTJOekUwTFdRME5qa3RORFZtT1MxaE56WXlMVGxpCk1HTmtPV0l3TUdZelpUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFFaWQ3TTdrOS9xUkYxYi9vbDN4cG5Nb2YKWCt5OWJTQ3RMdmNVM2NzRERGeXR3eUNPVS8xNGJ4L2ZPRFJWaW9hMFFqZlhjbis5SUltQkRwS3gxODVIUk5GRwptZU1wM1BNUVhzWGVSTndHbUxSRWErUkRZRnBrcTFLQTVRNEpIc1J2Qng5elpScDJSTWFuVTd6M1Znd0QyVTFOClZmRnBMb2ZkVDdIQ0VUcWdWaHdIVWhQMGxncEt6Nndtc1FpMTIyazBuajE5bGRSa2NRcUVjZWVQSHVTT0hUY0wKRFdJdjlHbUhibHpOam5XVFRhNHhsVFRoRXJld0MvampFejhMU09hUFZ6em9nSi9RSzZrZ3B5elZWTmVyMkx6ZgpUOWM0QUNZY3h5a3lsM3dlYmdVWkFiUG9XR0JqOEpTUXVkYmRRNm1SNjZaT2hqK2lyUDJsVVlVTXNnRVovUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/performance-addon-operator-service
        with hostname performance-addon-operator-service.openshift-cluster-node-tuning-operator.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        performance-addon-operator-webhook-cert''. The certificate is valid for 2
        years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:40Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:30:40Z"
      service.beta.openshift.io/originating-service-name: performance-addon-operator-service
      service.beta.openshift.io/originating-service-uid: 68ac6714-d469-45f9-a762-9b0cd9b00f3e
    creationTimestamp: "2026-01-28T09:30:40Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"68ac6714-d469-45f9-a762-9b0cd9b00f3e"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:40Z"
    name: performance-addon-operator-webhook-cert
    namespace: openshift-cluster-node-tuning-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: performance-addon-operator-service
      uid: 68ac6714-d469-45f9-a762-9b0cd9b00f3e
    resourceVersion: "6529"
    uid: f76c8b39-6c16-4864-8069-210c0619dcfc
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35076"
