---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVrVENDQTNtZ0F3SUJBZ0lJTUFrSFRKbE1wbWt3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE14TkRCYUZ3MHlPREF4TWpnd09UTXhOREZhTURzeE9UQTNCZ05WQkFNTU1Db3ViV1YwCmNtbGpjeTV2Y0dWdWMyaHBablF0WTJ4MWMzUmxjaTF6WVcxd2JHVnpMVzl3WlhKaGRHOXlMbk4yWXpDQ0FTSXcKRFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU0vV2NGanYzcGo1MUwyUGVZM2h0QktQYlhwRAoxRWtYNC9wTzRTWDVCZ2M4TStodm81OEV5aHFNbzVGdENaZ1FjQW5SL2hybmM4cTFOdDA1TFYycXpUSWVsOXZjCnhHeXNiamRpejVCLytkNlZaREl2VGZTbFpFdmlRdlJGYTZkTHlpZ3VOa2hjTFNHdm5aOC9mM0JTYks4Y0NTWWcKZ0t5OUQ2eHVLcStWWUU2djBVM29aUTd0MnVoM1cxNkJjM211cE56NkJ6dUhoRjJkR01VVXY0aW9IYzVUVkloLwplSmxDTlRsWWhkZVVzVlJYMTg0RzJhVm1LQUpDa0JkZmxWWkF3Z21vN0hXSVRpRTJSWnZlY0prZ0tjUjdvUGVrCkRCaU41TVFVYXBkd0tQSXZLdFBCOUFCZ2xUNENyMVZRUFhFN2FHTHNsYStlcU56bmk5TDlMZW1SR3FFQ0F3RUEKQWFPQ0Fad3dnZ0dZTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBTQpCZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRY1lSNi8wN3FHSU0rcWxycERGMUhuNXl1Uk1EQWZCZ05WCkhTTUVHREFXZ0JTWXdYNVlWVnZpb1I5OCtqbzkycVhBclR6MTZ6Q0I2d1lEVlIwUkJJSGpNSUhnZ2pBcUxtMWwKZEhKcFkzTXViM0JsYm5Ob2FXWjBMV05zZFhOMFpYSXRjMkZ0Y0d4bGN5MXZjR1Z5WVhSdmNpNXpkbU9DUGlvdQpiV1YwY21samN5NXZjR1Z1YzJocFpuUXRZMngxYzNSbGNpMXpZVzF3YkdWekxXOXdaWEpoZEc5eUxuTjJZeTVqCmJIVnpkR1Z5TG14dlkyRnNnaTV0WlhSeWFXTnpMbTl3Wlc1emFHbG1kQzFqYkhWemRHVnlMWE5oYlhCc1pYTXQKYjNCbGNtRjBiM0l1YzNaamdqeHRaWFJ5YVdOekxtOXdaVzV6YUdsbWRDMWpiSFZ6ZEdWeUxYTmhiWEJzWlhNdApiM0JsY21GMGIzSXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dOUVlMS3dZQkJBR1NDQkZrQWdFRUpoTWtOR1kxCk1XUTBaV1V0TXpBek1pMDBPRGhoTFRrd1lUQXRaREUzWTJRMVl6RXpNelpqTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQ2V4SEZsYk1kdjVXNWRFemhkcnlnM29teVg3MURGVHdMcGhKaTN6aXlydFR3QWJtbkpvT0lFSEFWTwpjOG9jWHU0aStidVBZOTBnOVhNYWhaMGJralVCY3pFNE04TkN5NzlhUWI2OTFkY3BpU1I0dEJ5eXpTUmF2WGRsCnlGWm1ReXRQTlZjOEVhRHZDWVhhWWFjV0pza2p6VjZtaTFuNURDS2I3dHJLWUw3Ky9ITURiSmJXd1I4ZXRvaFcKMExDSHpZWEZBK1pBMGc4QXRiZjBTZkdmZmlkbTRNQkJzQnRhbUFGK3RELzQrdmJPeTF0WjF5S25WZTRieGZyNwpCR0NxQ2ZHQ1N6ZFJ5dTgxcVFhZm5kTU9JWTdaOVVBMVc5UHcrS25zcDJTTy93NGV3MUtjenI4SU5RWSt2c1Z0CmxMcTkxdjhnNGRzemxjcG9vOFpjNGZidlB4UGoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-cluster-samples-operator.svc and is annotated to the service
        with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        samples-operator-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:31:41Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:31:41Z"
      service.beta.openshift.io/originating-service-name: metrics
      service.beta.openshift.io/originating-service-uid: 4f51d4ee-3032-488a-90a0-d17cd5c1336c
    creationTimestamp: "2026-01-28T09:31:41Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4f51d4ee-3032-488a-90a0-d17cd5c1336c"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:31:41Z"
    name: samples-operator-tls
    namespace: openshift-cluster-samples-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: 4f51d4ee-3032-488a-90a0-d17cd5c1336c
    resourceVersion: "9445"
    uid: b5524687-46e4-4fad-a50d-1407ab7402f5
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35160"
