---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2026-01-28T09:31:08Z"
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
      f:roleRef: {}
      f:subjects: {}
    manager: cluster-olm-operator
    operation: Update
    time: "2026-01-28T09:31:08Z"
  name: catalogd-metrics-monitor-rolebinding
  namespace: openshift-catalogd
  resourceVersion: "8267"
  uid: f93bdff1-562a-4021-80be-8ce8a2af9575
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: catalogd-metrics-monitor-role
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
