---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPRENDQWlDZ0F3SUJBZ0lJTTU1cXc1TTJmWkF3RFFZSktvWklodmNOQVFFTEJRQXdMVEVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SY3dGUVlEVlFRREV3NXJkV0psYkdWMExYTnBaMjVsY2pBZUZ3MHlOakF4TWpndwpPVE13TXpWYUZ3MHlOakF4TWprd09URXpNRFphTUNZeEpEQWlCZ05WQkFNTUcydDFZbVV0WTNOeUxYTnBaMjVsCmNsOUFNVGMyT1RVNU1qWXpOakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNS2QKQjVHVElTaXZncDREY2RMWksvV0pNUVBLeGMyL0Q0WjI0QnpydkJMUmpQU1lTNXNDcVZ1ZG9WZ3pIRGxkZ1A5cApITHRKT2NkOHNsWDNCcGFEdUIrdTNGR3h3Yno3elJhZDk3N2FoaStpVFZ4T1V5TlBiWHUzVDhhc0ZXUmd1UGdaCkVCVHZRSGpVM1FQWlg0Zmd0L3RjdFBLcTBDZWVXMndKZDRhbHdKTGN1N3VqdEpqSjJvWE4vUjNhMCt1d3NLOE8KSG4vdnRieThvdWFwVWltR3lPdUFOMHJxQVltcTVZSGNuWk9uSjh3bUc5STJVSkdzcFZwdXRrNXVsSk5iRVUybQpkMUh5OGNScnE5Tkpnc2FpV1l2MXJMMWk2OEdabUJFM0tsSWFEdTNzQXpadXo5c21wV0FtaTlFVXpvdDg0UG9KCnc4bzNZQXVjTGJ5Sm9VaVlYODhDQXdFQUFhTmpNR0V3RGdZRFZSMFBBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIKL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkQ0YXd3MVdIQmNXNzZ0RGVmY3ljOStieE5iNk1COEdBMVVkSXdRWQpNQmFBRkxkbXAvMW5saEQrbVBpbnRyNENNUTQ0dzAwdk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWhqUFJECi9TVysvakY5cWlhOEJ4WDZqRERiRkcwZHVOVFNRSTVSdlpuTGdOYnNLL01uTDJTbVNWUUM2amIyb1ZqTkMwZEEKVFVGTzAvL2xHcUM2TmVVQzFpc21iajg4eUNHZlZQbk5nMC9na2RDeFFocTZ3eTd5M2VmRWJYeG9jUTBFQXVaYgoza0tKYVZjTlp5QmtZaFJrYjF6OFZQWmVtTjhEQUdpSlY3aENmcGxmbytxeU53QS9mV05qLzExTWdzbnZ5Zkw3Cm94c2Q0ZTdyR003RkF4ckltbUpyWW5JWFg2Z216aFlEa0YwU3lsaDRGMzBjMktUVmI2eXdMd0ttVnZPUmc2bGMKOGhGeVI1RXNyczlYMVFOSTlqM0d1aGE0MFg3cE5jdDVNdEtTYXlhMmZkMTB0VVFzUTVvVDhZOG9ZWml2WmhqLwpXU3dQL04raXJWTTVxNTFPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIakNDQWdhZ0F3SUJBZ0lJRlBqOTg3NWxrbXd3RFFZSktvWklodmNOQVFFTEJRQXdMVEVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SY3dGUVlEVlFRREV3NXJkV0psYkdWMExYTnBaMjVsY2pBZUZ3MHlOakF4TWpndwpPVEV6TURaYUZ3MHlOakF4TWprd09URXpNRFphTUMweEVqQVFCZ05WQkFzVENXOXdaVzV6YUdsbWRERVhNQlVHCkExVUVBeE1PYTNWaVpXeGxkQzF6YVdkdVpYSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFoyV2VtQkRVNmlHMGtBVkg5aWcwQXo0YXdSdlhZUzE3S1BQN1UwME5lNzl0UUQ2NjBjR0ZIUW82TQpQQWl5N2x3UW1BWVdzZW93TmJwRVhZQjdRVkVvUmtaWWYwQlpDdjBxMzNxWS9RdEJUMU5QY0k1VlMrL2l2cFB3CkRsZ1VTVzdVYmNxdVdqN1duZU1zV0xHU3lQTjdldHlkY0RFRFc5ZHNCTzNtY3JES08yb1grUkhkeUVlSzd6aHkKM3pFVitxRnVEb3dEdndqNkxOR0QxamZGS2orYkRCSFIwQlprLzV1QVpMamVqQnF1RStrbFdwZTNvMHhicXpuZgpnZFZIUmhRSllFL090eTZ6WThDWHZGdGREUUZIRUU0UzBBNTE0NlhORDV2QlZNR3Y2MHgxekV6bjM2cFV1UUg5CjZEL0kzT29PekxYVU5XSWwyNWpSYlZ0TGRiRU5BZ01CQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlMzWnFmOVo1WVEvcGo0cDdhK0FqRU9PTU5OTHpBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFrSzFNL2pkSmRWZVlwYk1VNjdoZk01ODY1NjUwanBCdEFXWDUrQ1ZFCnozZHNpVm9yYjlrTnlWT3dpVnExTktjN29oY0QxWTVMNzlZZHVnVmdpdVBTZFJqNk1sMjBQL1ZrKzZXaE82ZG4KYml2aGQ4UGtrMjkxOGZ5R1RVZUJpTHIvU0xxMnF2ak93NzVGZGw1b0J2MUNXbERGVXZ3eGZtTytENGFuTGpGZQppbVVDK1lXbWNJejBQbUpHYjBiNXZNaENNdWV5Y3J3TjFMeWFzNkFEdHZZRmdzK2p3dSsrQnJ4cDViM29nZjlrCkZwb0FXK1oxVFVSSUZaQURuQ1h0M3IyY0orWEFHWCtzZmhOeXF4bW40bWpFWmd0cUJYWm9Mc2JrMFpNNWZrNGUKSmxsdDJrb24zL0k3VWxLRmdad2hvVk1QT1lmNGhrV0xUVTJqcVh0dWh0OVh1QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-issuer: kubelet-signer
      auth.openshift.io/certificate-not-after: "2026-01-29T09:13:06Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:30:35Z"
      certificates.openshift.io/refresh-period: 360h0m0s
      openshift.io/owning-component: kube-controller-manager
    creationTimestamp: "2026-01-28T09:30:38Z"
    labels:
      auth.openshift.io/managed-certificate-type: target
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:certificates.openshift.io/refresh-period: {}
            f:openshift.io/owning-component: {}
          f:labels:
            .: {}
            f:auth.openshift.io/managed-certificate-type: {}
        f:type: {}
      manager: cluster-kube-controller-manager-operator
      operation: Update
      time: "2026-01-28T09:30:38Z"
    name: csr-signer
    namespace: openshift-kube-controller-manager-operator
    resourceVersion: "6336"
    uid: 673692fc-12b3-40b7-84b8-77033811c70a
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIakNDQWdhZ0F3SUJBZ0lJRlBqOTg3NWxrbXd3RFFZSktvWklodmNOQVFFTEJRQXdMVEVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SY3dGUVlEVlFRREV3NXJkV0psYkdWMExYTnBaMjVsY2pBZUZ3MHlOakF4TWpndwpPVEV6TURaYUZ3MHlOakF4TWprd09URXpNRFphTUMweEVqQVFCZ05WQkFzVENXOXdaVzV6YUdsbWRERVhNQlVHCkExVUVBeE1PYTNWaVpXeGxkQzF6YVdkdVpYSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFoyV2VtQkRVNmlHMGtBVkg5aWcwQXo0YXdSdlhZUzE3S1BQN1UwME5lNzl0UUQ2NjBjR0ZIUW82TQpQQWl5N2x3UW1BWVdzZW93TmJwRVhZQjdRVkVvUmtaWWYwQlpDdjBxMzNxWS9RdEJUMU5QY0k1VlMrL2l2cFB3CkRsZ1VTVzdVYmNxdVdqN1duZU1zV0xHU3lQTjdldHlkY0RFRFc5ZHNCTzNtY3JES08yb1grUkhkeUVlSzd6aHkKM3pFVitxRnVEb3dEdndqNkxOR0QxamZGS2orYkRCSFIwQlprLzV1QVpMamVqQnF1RStrbFdwZTNvMHhicXpuZgpnZFZIUmhRSllFL090eTZ6WThDWHZGdGREUUZIRUU0UzBBNTE0NlhORDV2QlZNR3Y2MHgxekV6bjM2cFV1UUg5CjZEL0kzT29PekxYVU5XSWwyNWpSYlZ0TGRiRU5BZ01CQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlMzWnFmOVo1WVEvcGo0cDdhK0FqRU9PTU5OTHpBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFrSzFNL2pkSmRWZVlwYk1VNjdoZk01ODY1NjUwanBCdEFXWDUrQ1ZFCnozZHNpVm9yYjlrTnlWT3dpVnExTktjN29oY0QxWTVMNzlZZHVnVmdpdVBTZFJqNk1sMjBQL1ZrKzZXaE82ZG4KYml2aGQ4UGtrMjkxOGZ5R1RVZUJpTHIvU0xxMnF2ak93NzVGZGw1b0J2MUNXbERGVXZ3eGZtTytENGFuTGpGZQppbVVDK1lXbWNJejBQbUpHYjBiNXZNaENNdWV5Y3J3TjFMeWFzNkFEdHZZRmdzK2p3dSsrQnJ4cDViM29nZjlrCkZwb0FXK1oxVFVSSUZaQURuQ1h0M3IyY0orWEFHWCtzZmhOeXF4bW40bWpFWmd0cUJYWm9Mc2JrMFpNNWZrNGUKSmxsdDJrb24zL0k3VWxLRmdad2hvVk1QT1lmNGhrV0xUVTJqcVh0dWh0OVh1QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-issuer: kubelet-signer
      auth.openshift.io/certificate-not-after: "2026-01-29T09:13:06Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:13:06Z"
      openshift.io/owning-component: kube-controller-manager
    creationTimestamp: "2026-01-28T09:25:32Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:openshift.io/owning-component: {}
        f:type: {}
      manager: cluster-bootstrap
      operation: Update
      time: "2026-01-28T09:25:32Z"
    name: csr-signer-signer
    namespace: openshift-kube-controller-manager-operator
    resourceVersion: "672"
    uid: c30b4f01-79d3-4f72-8c5c-541352f75b4c
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVORENDQXh5Z0F3SUJBZ0lJUE9pbllvb3M0WVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRWYUZ3MHlPREF4TWpnd09UTXdORFphTUVFeFB6QTlCZ05WQkFNVE5tMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMV3QxWW1VdFkyOXVkSEp2Ykd4bGNpMXRZVzVoWjJWeUxXOXdaWEpoZEc5eUxuTjIKWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDhyNmRwcXN1UDh3QnVlQ3dsOQpidk5vblExM2M4R0t2K1dtVWFISlR6TFdDZk5JR3EyNVVLcUd3UWdOakFadVpsY09BRnc3YW9NSXhGdnVXcUNiCkFHT3cxVHorMytNcUw1Mms4Q2NpdERNZTZyWFk4eVJjM25OU2wzNE02UEpuZVNaMnVjMTE4RHltaG53REZheVQKdEptTmVpQm1sY1VhL0pqd0tOSWpTbWxqUXptemcreStjZlVyQ2ZKRllMSVhqbDArTmdtMDRtcFNjK3VHVm1YWQpjTkxoSldRTkMybXR4YVVWUSt1NU1GOFEwOWNGa3pmTUhTSmxNZGR6ZjlhTi84OWV6SUxjcDJhZlA0NHhUVFBHClhMZ0ZxOWpxV3drekFjMkxvQVpha3BxRWJ5T090eVprelpjY3RJNnkrMFgySVg5cTZIazRBY280czVzR3c3aTgKWjFFQ0F3RUFBYU9DQVRrd2dnRTFNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRgpCUWNEQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlMzWk5LbVRTZVFRR01HN211QXp2bFI4ZkJECit6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxNnpDQmlBWURWUjBSQklHQU1INkMKTm0xbGRISnBZM011YjNCbGJuTm9hV1owTFd0MVltVXRZMjl1ZEhKdmJHeGxjaTF0WVc1aFoyVnlMVzl3WlhKaApkRzl5TG5OMlk0SkViV1YwY21samN5NXZjR1Z1YzJocFpuUXRhM1ZpWlMxamIyNTBjbTlzYkdWeUxXMWhibUZuClpYSXRiM0JsY21GMGIzSXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dOUVlMS3dZQkJBR1NDQkZrQWdFRUpoTWsKTlRsaVl6Y3daR1V0WTJKaU5TMDBOakJpTFRobU9XSXROemN3TmpreE5tSXhaakUzTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQTZNK2xkMXh5VkRHNER6QWt3bmY3TlA3ZkxjSnh6M201TWIyb25NSndUTms5cFJ6WFgyZzV3CklCNDJySXJsMGRrcGdBTUFUTnFmd0pveEk3VHBHQkF1ZUpHZiszZ2dlOEdTQWFRdFE5WmdIbmNRWUpzbFZ0MEsKOVhDMGQ2YkwyZjFWQzhnVzRMMUhBclpNcXFsUUxYSTN2aUNEYncxaDZiMjlyczFYeExRZ1lUWG5wQXhES2xZMQp0YmpPUWF6THVENjhuaXVMMlpQK2NrNzhORjlDNG0rbm1NV29UOVFTZXVWZlR5bUJwK0wxMFVvaFNyMTJmanRVCkpDbVF3ZDhkTmdqaG9VdHNjMXdRL2FlSXprS0FJNHE1dFQxdzg5MjQ1ZVFtczNZV1NzODVCek9FMDAvdCsxOVgKU2JFTDAzZUlUYWlOc1FkMnFTR0hJdkdBU05oTUtFTmMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-kube-controller-manager-operator.svc and is annotated to
        the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        kube-controller-manager-operator-serving-cert''. The certificate is valid
        for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:46Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:30:46Z"
      service.beta.openshift.io/originating-service-name: metrics
      service.beta.openshift.io/originating-service-uid: 59bc70de-cbb5-460b-8f9b-7706916b1f17
    creationTimestamp: "2026-01-28T09:30:47Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"59bc70de-cbb5-460b-8f9b-7706916b1f17"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:47Z"
    name: kube-controller-manager-operator-serving-cert
    namespace: openshift-kube-controller-manager-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: 59bc70de-cbb5-460b-8f9b-7706916b1f17
    resourceVersion: "7050"
    uid: a11e006d-87d1-4586-aa8b-7864c3228558
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    service-account.key: MzI0MyBieXRlcyBsb25n
    service-account.pub: ODA4IGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    annotations:
      kube-controller-manager.openshift.io/ready-to-use: "2026-01-28T09:44:54Z"
    creationTimestamp: "2026-01-28T09:39:55Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:service-account.key: {}
          f:service-account.pub: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kube-controller-manager.openshift.io/ready-to-use: {}
        f:type: {}
      manager: cluster-kube-controller-manager-operator
      operation: Update
      time: "2026-01-28T09:39:55Z"
    name: next-service-account-private-key
    namespace: openshift-kube-controller-manager-operator
    resourceVersion: "18178"
    uid: 8ad80bd4-69c6-4eb2-a054-bb5138b1caac
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "35094"
