---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:31:55Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: machine-config-operator
    operation: Update
    time: "2026-01-28T10:24:22Z"
  name: machine-config
  namespace: openshift-machine-config-operator
  resourceVersion: "34786"
  uid: d37f0467-a4bf-41d1-a967-866fab76b3d9
spec:
  acquireTime: "2026-01-28T09:31:55.446550Z"
  holderIdentity: machine-config-operator-84ddcf457d-wrwhn_9fcc6235-7034-4936-a055-3dd69d5ba59c
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:22.232309Z"
