---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:32:24Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: machine-config-controller
    operation: Update
    time: "2026-01-28T10:24:25Z"
  name: machine-config-controller
  namespace: openshift-machine-config-operator
  resourceVersion: "34823"
  uid: 0a8dab91-ce83-409d-83d5-0d7e3d759067
spec:
  acquireTime: "2026-01-28T09:32:24.304111Z"
  holderIdentity: machine-config-controller-684d9b9c86-l4lpq_a78bd9fd-cec0-4838-bb42-4d7139496ce9
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:25.205024Z"
