---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-28T09:31:00Z"
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
    manager: cluster-olm-operator
    operation: Update
    time: "2026-01-28T09:31:00Z"
  name: catalogd-controller-manager
  namespace: openshift-catalogd
  resourceVersion: "7736"
  uid: 92884097-17b7-47d3-9322-71ae32df05b1
