---
apiVersion: v1
items:
- apiVersion: v1
  data:
    aws_access_key_id: MjAgYnl0ZXMgbG9uZw==
    aws_secret_access_key: NDAgYnl0ZXMgbG9uZw==
    credentials: MTE1IGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    annotations:
      cloudcredential.openshift.io/aws-policy-last-applied: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["ec2:DescribeInstances","ec2:DescribeInstanceStatus","ec2:DescribeInstanceTypes","ec2:UnassignPrivateIpAddresses","ec2:AssignPrivateIpAddresses","ec2:UnassignIpv6Addresses","ec2:AssignIpv6Addresses","ec2:DescribeSubnets","ec2:DescribeNetworkInterfaces"],"Resource":"*"},{"Effect":"Allow","Action":["iam:GetUser"],"Resource":"arn:aws:iam::387344700001:user/ci-ln-vjb5l1t-76ef8--openshift-cloud-network-config-contro-jf8w8"}]}'
      cloudcredential.openshift.io/credentials-request: openshift-cloud-credential-operator/openshift-cloud-network-config-controller-aws
    creationTimestamp: "2026-01-28T09:27:06Z"
    labels:
      cloudcredential.openshift.io/credentials-request: "true"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:aws_access_key_id: {}
          f:aws_secret_access_key: {}
          f:credentials: {}
        f:metadata:
          f:annotations:
            .: {}
            f:cloudcredential.openshift.io/aws-policy-last-applied: {}
            f:cloudcredential.openshift.io/credentials-request: {}
          f:labels:
            .: {}
            f:cloudcredential.openshift.io/credentials-request: {}
        f:type: {}
      manager: cloud-credential-operator
      operation: Update
      time: "2026-01-28T09:27:06Z"
    name: cloud-credentials
    namespace: openshift-cloud-network-config-controller
    resourceVersion: "2973"
    uid: 0baef6fb-970c-4c82-8254-8f9fb12c275b
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "35155"
