---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1ekNDQXMrZ0F3SUJBZ0lJZjgwVHViZzBqYnd3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE14TlRoYUZ3MHlPREF4TWpnd09UTXhOVGxhTUNneEpqQWtCZ05WQkFNVEhXUnVjeTFrClpXWmhkV3gwTG05d1pXNXphR2xtZEMxa2JuTXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVBeG5VZ0xNVEo0bmZtTzJyMUlKRmV5ak9mM3hhZ3pPOWozN1FoWUlEZndIbDFuVk1ENXBnYgpNd2tSbjBzVHRZbWw5YmJZZVJWaHFsTklvOXhIQ2FoSW1Vb2lDTXZMSFJxRE9NaTVaQjdoWHF2bzJHYm53RnhtCmxxRzJ5T0hIbEhNQkxhRWdBWXkzM3RWMGFCQTVUVXdmOTIvUjFMTEtRbmxsMGlsZG9jMFQ5TXpscUVwSVFML28KWkgwNTRlSjQwTWY3N2k2OEZCdnRlSzQ1UE5aZXJqalNvVmFWdWp2a2tOU2JRWVFJbjRBdVdWZ3NIdi84bE1hbApMWVQxU05HYVYrVVJRNUhkekpSOHFMUlYyRW4wa3RHMDlxSS9raGx1aENLSGVOK0ZZTXFBc2x6blN5eGZKa0tUCjV4N0lKRFNmTXZpeEo3Mkx2VDkvU3ZNY1doTklCaG5IcXdJREFRQUJvNElCQlRDQ0FRRXdEZ1lEVlIwUEFRSC8KQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwTwpCQllFRkllMEZsQnNxYXI1L01LSlR5cjRxZzFuS0w1MU1COEdBMVVkSXdRWU1CYUFGSmpCZmxoVlcrS2hIM3o2Ck9qM2FwY0N0UFBYck1GVUdBMVVkRVFST01FeUNIV1J1Y3kxa1pXWmhkV3gwTG05d1pXNXphR2xtZEMxa2JuTXUKYzNaamdpdGtibk10WkdWbVlYVnNkQzV2Y0dWdWMyaHBablF0Wkc1ekxuTjJZeTVqYkhWemRHVnlMbXh2WTJGcwpNRFVHQ3lzR0FRUUJrZ2dSWkFJQkJDWVRKR013WkRkaVpHVTRMVGcyT0dRdE5ESTJPQzFpTTJNeUxUWmpZbUUyCk5HUTJZV0ZpWWpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXJsMEx1ZmFDOFA1eWpvQ1dRaE94T1ZJZkF3V04KSWNpbVU4Q3hNUXpuUDZQQWQ2MjJ2VGJaRmxiMW5SNlc3Y2VzTjRGMHdCajA2ZGFOdnVQL0YwVEpkczU3TW92WgpYY2JtZmdJV3J4OVBVRmhINWV6OEFRSEhodE5zUUF4REFiaS9IWUxlNkFvVURLaW5FZFFGY3pvVHJ1elUwZG15CnZFS2hFMlltN0U4TGl6a2RWZC9wQTVFeXVOR0MvOFNTbzNQRm1FVDFTVUNEQ2RyNTI0clI2TzROdExFcGJ6NDcKV1B3UWdMU3lmaTFmYkpWWUNSWW1FeEVCbjBNQmJBcyt2bnZXTG9kYWFSaGR6SXhXU1dEMlBudjZwWXc4RFBINApQWGhPWlFtVGlEZWQzUGtYOWpTd1lieTVWUjNvaEp3bXEvZkFFWEF1SW5tWHh3RlFrRXY1THNjdS9BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/dns-default with hostname
        dns-default.openshift-dns.svc and is annotated to the service with annotating
        a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        dns-default-metrics-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:31:59Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:31:59Z"
      service.beta.openshift.io/originating-service-name: dns-default
      service.beta.openshift.io/originating-service-uid: c0d7bde8-868d-4268-b3c2-6cba64d6aabb
    creationTimestamp: "2026-01-28T09:31:59Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"c0d7bde8-868d-4268-b3c2-6cba64d6aabb"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:31:59Z"
    name: dns-default-metrics-tls
    namespace: openshift-dns
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: dns-default
      uid: c0d7bde8-868d-4268-b3c2-6cba64d6aabb
    resourceVersion: "10444"
    uid: b9666f05-9645-40ac-b5d4-166b3ecd0e4c
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35035"
