---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpDZ0F3SUJBZ0lJUnByV0xoZU9FTmd3RFFZSktvWklodmNOQVFFTEJRQXdNREV1TUN3R0ExVUUKQXd3bGIzQmxibk5vYVdaMExXVjBZMlJmWlhSalpDMXphV2R1WlhKQU1UYzJPVFU1TWpFNU5UQWVGdzB5TmpBeApNamd3T1RJek1UVmFGdzB6TVRBeE1qY3dPVEl6TVRWYU1FQXhLREFTQmdOVkJBb1RDMlYwWTJRdFkyeHBaVzUwCk1CSUdBMVVFQ2hNTGMzbHpkR1Z0T21WMFkyUXhGREFTQmdOVkJBTVRDMlYwWTJRdFkyeHBaVzUwTUlJQklqQU4KQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcjBFd1R6a0Q1bUZNTy9yTWlCZXhVUGlDbSsycgp4TEJGVVQ5bHBGazFVNnE1SFZDKzVyMkZDYy9HM0lyVFEvZWZOM0YzWTlZU1dQU2xjVXBzMHFoYm1EN0tWZmJ4Cmd4djRBNXNuRlkxSWdsMWRDZmRPUjR1NS9BckMyb3E5N3FnVHk1ZU5TbzNCd0xRVDlwNmlrUjRsdnkzZkFxY0IKU3FOM1JQNzBKV0txNU1HUWxUUlNrSE5oc08ybWZtblFmSmUyVGhNUnZOSDdpNDI0Tk40R095SnFoU3JhSTY1aAp4b21QeU1KOU9laCtpRTV0Y3QxaWpLcFpUQmYzUC9KK2N2WXBqY2dTL3UwOGxpMk1NWi9jMkh0b1hHaE9vbE9yCkovUDVWemlySlF4Nk5nVGV1bnNDcGhOaXF4WXViSEpWU2loc29jcTFjdGVaZW9pWXVLUHN6ZFVKalFJREFRQUIKbzFZd1ZEQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3SXdEQVlEVlIwVApBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlM5bmEwK3h0QTE2cW5aT2E3cVQ2bk0yNVlzUVRBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFUQ0ozWDBEd2NGNE5aTTAzTnVtWkYzSUpTNSs0bzh5ckpZY0cvMEE5cmFWdXVqWUkKbEFGbnp4ZVh3ZktYQS9mdGtWVXdGWHN4R0NSOTdlZjI4TXRZZEV1Ky9DTTh1OFA4TEp1dzFlUGcwVlJDYkIzcgpZSlVsdEZTbUkvMmRUd1BBTG14bStvOWRmU0NUaUR2WXV4NTZ0Ry82UElLM01YdnJndXEyL0szNlpuc2lVT1FICkxmZXJoMkJMYk8vQVhvZEYrQkZlTHdTY2ZGbStkSlNDSkpvYnhQRDZxRTVCM3RjbkUwaUl0ZVpqVWtiak5ocUoKZGVFeFBhaTd1VThrZm9TMko1OXU4U3psUTNjc2hKR1pOTWloSVMwT0UybjVmWE1JVnVFclNDY3FWaE0reVgwOApmZkhFdDhwVUNEc2hLcFFOQW5adlZHejFhNTl2QVZ2MG93WTVQZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-issuer: openshift-etcd_etcd-signer@1769592195
      auth.openshift.io/certificate-not-after: "2031-01-27T09:23:15Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:23:15Z"
      certificates.openshift.io/refresh-period: 36792h0m0s
      openshift.io/description: Client certificate for apiserver, cluster-etcd-operator
        and etcdctl to reach etcd. Generated by cluster-etcd-operator for etcd. This
        certificate is valid for 1825 days and starts refreshing after 1533 days.
      openshift.io/owning-component: etcd
    creationTimestamp: "2026-01-28T09:30:43Z"
    labels:
      auth.openshift.io/managed-certificate-type: target
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:certificates.openshift.io/refresh-period: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
          f:labels:
            .: {}
            f:auth.openshift.io/managed-certificate-type: {}
        f:type: {}
      manager: cluster-etcd-operator
      operation: Update
      time: "2026-01-28T09:30:43Z"
    name: etcd-client
    namespace: openshift-config
    resourceVersion: "6752"
    uid: fb9e1e67-c1fc-4457-a07c-2e015e3f5cc6
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    service-account.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:26:17Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:service-account.key: {}
        f:type: {}
      manager: cluster-bootstrap
      operation: Update
      time: "2026-01-28T09:26:17Z"
    name: initial-service-account-private-key
    namespace: openshift-config
    resourceVersion: "2525"
    uid: d2da7bf8-5df8-4713-b243-6f05d6a7a149
  type: Opaque
- apiVersion: v1
  data:
    .dockerconfigjson: NDU4OCBieXRlcyBsb25n
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:26:16Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:.dockerconfigjson: {}
        f:type: {}
      manager: cluster-bootstrap
      operation: Update
      time: "2026-01-28T09:26:16Z"
    name: pull-secret
    namespace: openshift-config
    resourceVersion: "2441"
    uid: 74fb6dd7-15a3-4429-801d-d0f984ecbbd4
  type: kubernetes.io/dockerconfigjson
- apiVersion: v1
  data:
    kubeConfig: MzY2NiBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/owning-component: apiserver-auth
    creationTimestamp: "2026-01-28T09:32:09Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:kubeConfig: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/owning-component: {}
        f:type: {}
      manager: authentication-operator
      operation: Update
      time: "2026-01-28T09:32:09Z"
    name: webhook-authentication-integrated-oauth
    namespace: openshift-config
    resourceVersion: "11277"
    uid: 017f1b61-e3ac-4c11-a6ec-8fd4c176ca6c
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "34866"
