---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2026-01-28T09:40:12Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:rules: {}
    manager: cloud-credential-operator
    operation: Update
    time: "2026-01-28T09:40:12Z"
  name: pod-identity-webhook
  namespace: openshift-cloud-credential-operator
  resourceVersion: "18425"
  uid: 8ecc4c4b-6058-40a0-9467-7e18f9bdce83
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - pod-identity-webhook
  resources:
  - secrets
  verbs:
  - get
  - update
  - patch
