---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-28T09:40:12Z"
  name: pod-identity-webhook
  namespace: openshift-cloud-credential-operator
  resourceVersion: "18421"
  uid: a66cc0e7-c0d0-491a-b2bc-139b243ef781
