---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:31:48Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: csi-provisioner
    operation: Update
    time: "2026-01-28T10:24:14Z"
  name: ebs-csi-aws-com
  namespace: openshift-cluster-csi-drivers
  resourceVersion: "34760"
  uid: 9119f708-4057-44bc-a166-fceb5f88a2d9
spec:
  acquireTime: "2026-01-28T09:35:36.329177Z"
  holderIdentity: 1769592773649-8228-ebs-csi-aws-com
  leaseDurationSeconds: 137
  leaseTransitions: 1
  renewTime: "2026-01-28T10:24:14.123268Z"
