---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:32:05Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: csi-resizer
    operation: Update
    time: "2026-01-28T10:24:16Z"
  name: external-resizer-ebs-csi-aws-com
  namespace: openshift-cluster-csi-drivers
  resourceVersion: "34767"
  uid: 7fad37df-0ca1-4f74-ad64-043b14d53d85
spec:
  acquireTime: "2026-01-28T09:35:38.267003Z"
  holderIdentity: aws-ebs-csi-driver-controller-5cbc97cfdb-pct52
  leaseDurationSeconds: 137
  leaseTransitions: 1
  renewTime: "2026-01-28T10:24:16.113078Z"
