---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:32:08Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: csi-snapshotter
    operation: Update
    time: "2026-01-28T10:24:16Z"
  name: external-snapshotter-leader-ebs-csi-aws-com
  namespace: openshift-cluster-csi-drivers
  resourceVersion: "34768"
  uid: 8659677a-24e5-4810-ae05-ac176c70f2b3
spec:
  acquireTime: "2026-01-28T09:35:38.652655Z"
  holderIdentity: aws-ebs-csi-driver-controller-5cbc97cfdb-cf4f6
  leaseDurationSeconds: 137
  leaseTransitions: 1
  renewTime: "2026-01-28T10:24:16.388497Z"
