---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:31:55Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: csi-attacher
    operation: Update
    time: "2026-01-28T10:24:27Z"
  name: external-attacher-leader-ebs-csi-aws-com
  namespace: openshift-cluster-csi-drivers
  resourceVersion: "34838"
  uid: f3b31377-e84d-4f4e-ab93-c7ab3310da84
spec:
  acquireTime: "2026-01-28T09:35:24.122130Z"
  holderIdentity: aws-ebs-csi-driver-controller-5cbc97cfdb-cf4f6
  leaseDurationSeconds: 137
  leaseTransitions: 1
  renewTime: "2026-01-28T10:24:27.868313Z"
