---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Red Hat Single Sign-On 7.6 on OpenJDK
    openshift.io/display-name: Red Hat Single Sign-On 7.6 on OpenJDK
    openshift.io/provider-display-name: Red Hat, Inc.
    samples.operator.openshift.io/version: 4.20.0-0-2026-01-28-090915-test-ci-ln-vjb5l1t-latest
    version: 7.6.7.GA
  creationTimestamp: "2026-01-28T09:42:08Z"
  generation: 1
  labels:
    samples.operator.openshift.io/managed: "true"
  managedFields:
  - apiVersion: image.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:description: {}
          f:openshift.io/display-name: {}
          f:openshift.io/provider-display-name: {}
          f:samples.operator.openshift.io/version: {}
          f:version: {}
        f:labels:
          .: {}
          f:samples.operator.openshift.io/managed: {}
      f:spec:
        f:tags:
          .: {}
          k:{"name":"7.6"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:supports: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"latest"}:
            .: {}
            f:annotations: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
    manager: cluster-samples-operator
    operation: Update
    time: "2026-01-28T09:42:08Z"
  name: sso76-openshift-rhel8
  namespace: openshift
  resourceVersion: "20557"
  uid: 0c89758e-016f-4c99-ad63-e14c941f61d4
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Red Hat Single Sign-On 7.6 on OpenJDK image
      iconClass: icon-sso
      openshift.io/display-name: Red Hat Single Sign-On 7.6 on OpenJDK
      supports: sso:7.6
      tags: sso,keycloak,redhat,hidden
      version: "1.0"
    from:
      kind: DockerImage
      name: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8:7.6
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "7.6"
    referencePolicy:
      type: Local
  - annotations: null
    from:
      kind: ImageStreamTag
      name: "7.6"
    generation: 1
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/openshift/sso76-openshift-rhel8
