---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
    openshift.io/provider-display-name: Red Hat, Inc.
    samples.operator.openshift.io/version: 4.20.0-0-2026-01-28-090915-test-ci-ln-vjb5l1t-latest
  creationTimestamp: "2026-01-28T09:42:09Z"
  generation: 1
  labels:
    samples.operator.openshift.io/managed: "true"
  managedFields:
  - apiVersion: image.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/display-name: {}
          f:openshift.io/provider-display-name: {}
          f:samples.operator.openshift.io/version: {}
        f:labels:
          .: {}
          f:samples.operator.openshift.io/managed: {}
      f:spec:
        f:tags:
          .: {}
          k:{"name":"1.9"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"1.10"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"1.11"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"1.12"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"1.13"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"1.14"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"1.15"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"1.16"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"1.17"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
          k:{"name":"1.18"}:
            .: {}
            f:annotations:
              .: {}
              f:description: {}
              f:iconClass: {}
              f:openshift.io/display-name: {}
              f:tags: {}
              f:version: {}
            f:from: {}
            f:generation: {}
            f:importPolicy:
              .: {}
              f:importMode: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
    manager: cluster-samples-operator
    operation: Update
    time: "2026-01-28T09:42:09Z"
  name: ubi8-openjdk-8-runtime
  namespace: openshift
  resourceVersion: "20576"
  uid: 2c02bca5-e6da-45c6-a5ae-b2388caa276c
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.10"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.10
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.10"
    referencePolicy:
      type: Local
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.11"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.11
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.11"
    referencePolicy:
      type: Local
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.12"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.12
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.12"
    referencePolicy:
      type: Local
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.13"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.13
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.13"
    referencePolicy:
      type: Local
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.14"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.14
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.14"
    referencePolicy:
      type: Local
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.15"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.15
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.15"
    referencePolicy:
      type: Local
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.16"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.16
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.16"
    referencePolicy:
      type: Local
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.17"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.17
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.17"
    referencePolicy:
      type: Local
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.18"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.18
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.18"
    referencePolicy:
      type: Local
  - annotations:
      description: Run Java applications using OpenJDK 8 upon UBI8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 Runtime (UBI8)
      tags: java,openjdk,ubi8
      version: "1.9"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-8-runtime:1.9
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "1.9"
    referencePolicy:
      type: Local
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/openshift/ubi8-openjdk-8-runtime
