---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVFVENDQXZtZ0F3SUJBZ0lJVUlRWDdua1R2R2t3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE00TVRSYUZ3MHlPREF4TWpnd09UTTRNVFZhTURZeE5EQXlCZ05WQkFNVEsybHVaM0psCmMzTXRZMkZ1WVhKNUxtOXdaVzV6YUdsbWRDMXBibWR5WlhOekxXTmhibUZ5ZVM1emRtTXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREhzLzB0aSsvUmN2clpGM1VsczZ4UmEzSVd6d1VLd0sxWgpLYW91Qm90NlAxbTcyemc0dkZnNXZpZTFFL0Rhblp4MWFjTzJSZnpmTXNIalNabEV5aXYxVzV3cDRvT1pBckdKCmhrTUtIeEFlWUZXbzRwYVQ3WHdyNTJSdStCU1hkWk5ONmFYYVNrN0NSVkprR3dPWURRQ2tVbDFBZVU4QWh2UTQKdFpXZ2hYd0QyUURCYjNHMFlTTzlzT1liOVZPSzR5NWgydXRpU0x3NWY1bmNSaEsveDJsalltc3R4VnE3MFRkMgpvR2xWWFZ4cHU2YVMxelN4UE4zdjZQQ0szTmQ2M0JiWU5tV3JLVVcybVBVczdmNUNxbTVWTDJGRHFleXBTNzFzCklzM2J6dDZrazlNRG94bkh0VisvaTZKNVg3ZlJXTGk5QjRqZnRwdzQ3bWtZMDBHNVJlN3RBZ01CQUFHamdnRWgKTUlJQkhUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEQVlEVlIwVApBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVQaitCRTVpT2pvejNLdWd0S3lNRU43VmRDTjR3SHdZRFZSMGpCQmd3CkZvQVVtTUYrV0ZWYjRxRWZmUG82UGRxbHdLMDg5ZXN3Y1FZRFZSMFJCR293YUlJcmFXNW5jbVZ6Y3kxallXNWgKY25rdWIzQmxibk5vYVdaMExXbHVaM0psYzNNdFkyRnVZWEo1TG5OMlk0STVhVzVuY21WemN5MWpZVzVoY25rdQpiM0JsYm5Ob2FXWjBMV2x1WjNKbGMzTXRZMkZ1WVhKNUxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01EVUdDeXNHCkFRUUJrZ2dSWkFJQkJDWVRKREprWW1RMVl6YzRMV0UxTVRZdE5EVTJaQzA1TXpjMExURTRaVFZpWXpkbFl6TTEKT0RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXJjMFRjVVdURVNWWUZ4ZW44NFQvdHVHZjNpVGkxZmNONEduZApSOWN6WTh1Y1VYdlVnUXJHcng4d0h4SEh6bE03Tit2d0xoWFAwdmdSd3puNEE5WjFHTjJIMFJIUXpSaWFzVTlxCjFMdGpTdkpEbENneUs3RWRoNGR2UnJmdWdpNW4vMVhRa2EvZEVaT0ZHMWZ3WkhjbVlZbUppaFlxa21ERU8yRkcKL2grTDFMUllsWXRUV3Rjc1JoTmJYSk1BVThxQlluS0dDN0lkMStnY3JBWlREbUxyUlM2RTlSaVBtdnZ5eW9SUwo5b0pWUVlzVjlWSFRFZkJjQkI5UDgvU2x5SXlwMnc4TXpOa1h1NnQ2a1gydWlRTGQvSXdCS2w4NkFpM1pQV1ZxCm9DdHZWcDVscnVSYWJaWlVkWXFUbkl3VDdDejEzMGUvUjlVK2FyMG9qdmIrMi9OUzhRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/ingress-canary with hostname
        ingress-canary.openshift-ingress-canary.svc and is annotated to the service
        with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        canary-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:38:15Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:38:15Z"
      service.beta.openshift.io/originating-service-name: ingress-canary
      service.beta.openshift.io/originating-service-uid: 2dbd5c78-a516-456d-9374-18e5bc7ec358
    creationTimestamp: "2026-01-28T09:38:15Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"2dbd5c78-a516-456d-9374-18e5bc7ec358"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:38:15Z"
    name: canary-serving-cert
    namespace: openshift-ingress-canary
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: ingress-canary
      uid: 2dbd5c78-a516-456d-9374-18e5bc7ec358
    resourceVersion: "16963"
    uid: 0af3f2af-16a2-4609-a8df-ca3eb02b5275
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35043"
