---
apiVersion: policy/v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: "2026-01-28T09:40:12Z"
    generation: 1
    managedFields:
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:minAvailable: {}
          f:selector: {}
      manager: cloud-credential-operator
      operation: Update
      time: "2026-01-28T09:40:12Z"
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"DisruptionAllowed"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:observedGeneration: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:currentHealthy: {}
          f:desiredHealthy: {}
          f:disruptionsAllowed: {}
          f:expectedPods: {}
          f:observedGeneration: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2026-01-28T09:40:15Z"
    name: pod-identity-webhook
    namespace: openshift-cloud-credential-operator
    resourceVersion: "18592"
    uid: 368eefe0-02da-4365-8f0e-746ab186e404
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        app: pod-identity-webhook
  status:
    conditions:
    - lastTransitionTime: "2026-01-28T09:40:15Z"
      message: ""
      observedGeneration: 1
      reason: SufficientPods
      status: "True"
      type: DisruptionAllowed
    currentHealthy: 2
    desiredHealthy: 1
    disruptionsAllowed: 1
    expectedPods: 2
    observedGeneration: 1
kind: PodDisruptionBudgetList
metadata:
  resourceVersion: "34974"
