---
apiVersion: monitoring.coreos.com/v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2026-01-28T09:31:08Z"
    generation: 1
    labels:
      control-plane: operator-controller-controller-manager
      openshift.io/cluster-monitoring: "true"
    managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:control-plane: {}
            f:openshift.io/cluster-monitoring: {}
        f:spec:
          .: {}
          f:endpoints: {}
          f:namespaceSelector:
            .: {}
            f:matchNames: {}
          f:selector: {}
      manager: cluster-olm-operator
      operation: Update
      time: "2026-01-28T09:31:08Z"
    name: operator-controller-metrics-monitor
    namespace: openshift-operator-controller
    resourceVersion: "8250"
    uid: b43de67c-6a4d-48ed-b8cb-ad255f709fbf
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      path: /metrics
      port: https
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
        keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
        serverName: operator-controller-service.openshift-operator-controller.svc
    namespaceSelector:
      matchNames:
      - openshift-operator-controller
    selector:
      matchLabels:
        control-plane: operator-controller-controller-manager
kind: ServiceMonitorList
metadata:
  continue: ""
  resourceVersion: "35156"
