---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    openshift.io/description: Grants access from any authenticated user to the openshift-network-features
      ConfigMap
  creationTimestamp: "2026-01-28T09:29:29Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/description: {}
        f:ownerReferences:
          k:{"uid":"7763cebb-f1d7-4359-81b8-b55ef9916383"}: {}
      f:roleRef: {}
      f:subjects: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2026-01-28T09:29:29Z"
  name: openshift-network-public-role-binding
  namespace: openshift-config-managed
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 7763cebb-f1d7-4359-81b8-b55ef9916383
  resourceVersion: "4630"
  uid: 7c8e3e1a-1f7a-4b9f-b0df-8d65c2d19870
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-network-public-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
