---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZRekNDQkN1Z0F3SUJBZ0lJR1lXZHo0K0RUWjB3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpsYUZ3MHlPREF4TWpnd09UTXdOREJhTUY0eFhEQmFCZ05WQkFNTVV5b3VZMnh2CmRXUXRZMjl1ZEhKdmJHeGxjaTF0WVc1aFoyVnlMVzl3WlhKaGRHOXlMbTl3Wlc1emFHbG1kQzFqYkc5MVpDMWoKYjI1MGNtOXNiR1Z5TFcxaGJtRm5aWEl0YjNCbGNtRjBiM0l1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXcreDhLbldqOEtGYmRucmRBQmRBeEUremEzdVo5RHAxSHhNSjV1cHk3Y1l4Ck0ycjdiZkwzN0o1U3V4RTVQeEF0MVhyQ1B2QkFBZEtwSTF2aWVuenVJL0ZXUlFDdWtlUXdsZlhyWlVVMVhVNTEKZjJRSDFCUEQ1K2d2bUV5dW9mY3pIWnBFVGZSVTRoSmorT0dtQXpoR0pWWndxRzcvNU44QlRocTVlQW12cDlrNQpnMVQ0cEZWM3hsRGEvOUNFa1R1dHZsMEFuUm85NFhydW5ab1hGSjZ5cWprTGFjMmZhN09YMDYrb1dlMk1NQXd0CmJQd3ltNERvNDdqQnN1T0QyQVN4TGFDeGFBcndnQjV4TkFDSGFWbHViT3ZDTGZ3L05QNU1wWkFqSGFhR2NFSXMKNmFlUmlOOWdqaFUxcjBocGtITWt4dldFRTFLZ3dZRzRMaFJRQ2NVMVV3SURBUUFCbzRJQ0t6Q0NBaWN3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3CkhRWURWUjBPQkJZRUZBdzNkQlIrVmN3TmVkcWxqZ0JvYVZyWG51M0lNQjhHQTFVZEl3UVlNQmFBRkpqQmZsaFYKVytLaEgzejZPajNhcGNDdFBQWHJNSUlCZVFZRFZSMFJCSUlCY0RDQ0FXeUNVeW91WTJ4dmRXUXRZMjl1ZEhKdgpiR3hsY2kxdFlXNWhaMlZ5TFc5d1pYSmhkRzl5TG05d1pXNXphR2xtZEMxamJHOTFaQzFqYjI1MGNtOXNiR1Z5CkxXMWhibUZuWlhJdGIzQmxjbUYwYjNJdWMzWmpnbUVxTG1Oc2IzVmtMV052Ym5SeWIyeHNaWEl0YldGdVlXZGwKY2kxdmNHVnlZWFJ2Y2k1dmNHVnVjMmhwWm5RdFkyeHZkV1F0WTI5dWRISnZiR3hsY2kxdFlXNWhaMlZ5TFc5dwpaWEpoZEc5eUxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc2dsRmpiRzkxWkMxamIyNTBjbTlzYkdWeUxXMWhibUZuClpYSXRiM0JsY21GMGIzSXViM0JsYm5Ob2FXWjBMV05zYjNWa0xXTnZiblJ5YjJ4c1pYSXRiV0Z1WVdkbGNpMXYKY0dWeVlYUnZjaTV6ZG1PQ1gyTnNiM1ZrTFdOdmJuUnliMnhzWlhJdGJXRnVZV2RsY2kxdmNHVnlZWFJ2Y2k1dgpjR1Z1YzJocFpuUXRZMnh2ZFdRdFkyOXVkSEp2Ykd4bGNpMXRZVzVoWjJWeUxXOXdaWEpoZEc5eUxuTjJZeTVqCmJIVnpkR1Z5TG14dlkyRnNNRFVHQ3lzR0FRUUJrZ2dSWkFJQkJDWVRKRGcxTldOallXTTRMVFF3TVdJdE5EUmwKWlMwNU5tTTBMVFUxTVRBME5tRTFabVJoTmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQU4wano2eFp2STNpQwppM21COFN1b0dRVU5LR1RQS1NXS2kwaDdQajcxM29Ob294a04zVnJFSE9IRlNWZGtId1VWWllxZnZvbmpScEVLCk8vbWdRalRnK0ZjN3RBTG5MM1NidWtSMURYSE5rSGVyT0R4bUFMcnF4S3dpTU1vd2t1d0FxYkJoalFlUUxzcVUKR0hYNklXYkc1dnZVMjdmK21xS2Q4T3FBeHZRK2wzL3ZEOGIreWxWbFdNVkFyTnZzRDExQVBGUHgyL1RHUThPeApUZXZqSnU5akJaS1EzS3VrSnoyMDJ4ZFNnMEdtdzFZT2RjdmpMSk9VMTlPWTk3ejUxdWFFYS9yQkJaemlabENVCkdaMjBJd0k1MjZiRGJRVDVlcGQxdVlBUERiWEwvL0tFbW82OVdJVndBakVMZ21uNUJIOExlWnduSGxuaC9zR0MKVitNbitRM2NsQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/cloud-controller-manager-operator
        with hostname cloud-controller-manager-operator.openshift-cloud-controller-manager-operator.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        cloud-controller-manager-operator-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:40Z"
      service.alpha.openshift.io/originating-service-name: cloud-controller-manager-operator
      service.alpha.openshift.io/originating-service-uid: 855ccac8-401b-44ee-96c4-551046a5fda6
      service.beta.openshift.io/expiry: "2028-01-28T09:30:40Z"
    creationTimestamp: "2026-01-28T09:30:40Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"855ccac8-401b-44ee-96c4-551046a5fda6"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:40Z"
    name: cloud-controller-manager-operator-tls
    namespace: openshift-cloud-controller-manager-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: cloud-controller-manager-operator
      uid: 855ccac8-401b-44ee-96c4-551046a5fda6
    resourceVersion: "6546"
    uid: 9465ef5e-016a-4819-8a31-6fd5698d4f68
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "34969"
