---
apiVersion: discovery.k8s.io/v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.0.102.200
    conditions:
      ready: true
    nodeName: ip-10-0-102-200.us-west-1.compute.internal
    targetRef:
      kind: Node
      name: ip-10-0-102-200.us-west-1.compute.internal
      uid: 64bba62c-c331-4f4e-9112-9298c88bdae0
  - addresses:
    - 10.0.101.165
    conditions:
      ready: true
    nodeName: ip-10-0-101-165.us-west-1.compute.internal
    targetRef:
      kind: Node
      name: ip-10-0-101-165.us-west-1.compute.internal
      uid: b0fef558-e9cb-478b-80f8-c8c43c81a878
  - addresses:
    - 10.0.108.54
    conditions:
      ready: true
    nodeName: ip-10-0-108-54.us-west-1.compute.internal
    targetRef:
      kind: Node
      name: ip-10-0-108-54.us-west-1.compute.internal
      uid: 8aee47ee-44d2-43c6-8262-ad6e14a5f14a
  - addresses:
    - 10.0.3.203
    conditions:
      ready: true
    nodeName: ip-10-0-3-203.us-west-1.compute.internal
    targetRef:
      kind: Node
      name: ip-10-0-3-203.us-west-1.compute.internal
      uid: 96871530-1a97-4a09-81f1-3cab61f897b8
  - addresses:
    - 10.0.22.208
    conditions:
      ready: true
    nodeName: ip-10-0-22-208.us-west-1.compute.internal
    targetRef:
      kind: Node
      name: ip-10-0-22-208.us-west-1.compute.internal
      uid: 70a9365a-adc1-449a-8f3e-5fd2bcec4b45
  - addresses:
    - 10.0.78.215
    conditions:
      ready: true
    nodeName: ip-10-0-78-215.us-west-1.compute.internal
    targetRef:
      kind: Node
      name: ip-10-0-78-215.us-west-1.compute.internal
      uid: 15f7ea9d-72f7-4a8c-b969-0328a57ba32a
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2026-01-28T09:42:40Z"
    generateName: kubelet-
    generation: 1
    labels:
      app.kubernetes.io/managed-by: prometheus-operator
      app.kubernetes.io/name: kubelet
      endpointslice.kubernetes.io/managed-by: endpointslicemirroring-controller.k8s.io
      k8s-app: kubelet
      kubernetes.io/service-name: kubelet
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:k8s-app: {}
            f:kubernetes.io/service-name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"75efd9d3-86eb-4240-a349-e640f5907582"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:42:40Z"
    name: kubelet-xrmwq
    namespace: kube-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Endpoints
      name: kubelet
      uid: 75efd9d3-86eb-4240-a349-e640f5907582
    resourceVersion: "21574"
    uid: 80bd9e4a-0c89-46a1-b6dc-a9778c5d1cfa
  ports:
  - name: http-metrics
    port: 10255
    protocol: TCP
  - name: https-metrics
    port: 10250
    protocol: TCP
  - name: cadvisor
    port: 4194
    protocol: TCP
kind: EndpointSliceList
metadata:
  resourceVersion: "35098"
