---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    openshift.io/description: Can read the openshift-network-features ConfigMap values
  creationTimestamp: "2026-01-28T09:29:28Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/description: {}
        f:ownerReferences:
          k:{"uid":"7763cebb-f1d7-4359-81b8-b55ef9916383"}: {}
      f:rules: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2026-01-28T09:29:28Z"
  name: openshift-network-public-role
  namespace: openshift-config-managed
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 7763cebb-f1d7-4359-81b8-b55ef9916383
  resourceVersion: "4626"
  uid: 9bc8b80f-ab7c-40c1-9682-3df35108d12e
rules:
- apiGroups:
  - ""
  resourceNames:
  - openshift-network-features
  resources:
  - configmaps
  verbs:
  - get
