---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  annotations:
    capability.openshift.io/name: CloudCredential
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  creationTimestamp: "2026-01-28T09:27:12Z"
  finalizers:
  - cloudcredential.openshift.io/deprovision
  generation: 1
  managedFields:
  - apiVersion: cloudcredential.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"cloudcredential.openshift.io/deprovision": {}
    manager: cloud-credential-operator
    operation: Update
    time: "2026-01-28T09:27:12Z"
  - apiVersion: cloudcredential.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:exclude.release.openshift.io/internal-openshift-hosted: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
      f:spec:
        .: {}
        f:providerSpec:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:statementEntries: {}
        f:secretRef: {}
        f:serviceAccountNames: {}
    manager: cluster-version-operator
    operation: Update
    time: "2026-01-28T09:27:12Z"
  - apiVersion: cloudcredential.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:lastSyncCloudCredsSecretResourceVersion: {}
        f:lastSyncGeneration: {}
        f:lastSyncInfrastructureResourceVersion: {}
        f:lastSyncTimestamp: {}
        f:providerStatus:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:policy: {}
          f:user: {}
        f:provisioned: {}
    manager: cloud-credential-operator
    operation: Update
    subresource: status
    time: "2026-01-28T09:27:13Z"
  name: cloud-credential-operator-iam-ro
  namespace: openshift-cloud-credential-operator
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 0370d296-6904-481d-ab90-157c7e5b835a
  resourceVersion: "3078"
  uid: f1e0d57a-41be-4a29-bf8e-61d7746e0d24
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - iam:GetUser
      - iam:GetUserPolicy
      - iam:ListAccessKeys
      effect: Allow
      resource: '*'
  secretRef:
    name: cloud-credential-operator-iam-ro-creds
    namespace: openshift-cloud-credential-operator
  serviceAccountNames:
  - cloud-credential-operator
status:
  lastSyncCloudCredsSecretResourceVersion: "2820"
  lastSyncGeneration: 1
  lastSyncInfrastructureResourceVersion: "547"
  lastSyncTimestamp: "2026-01-28T09:27:13Z"
  providerStatus:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderStatus
    policy: ci-ln-vjb5l1t-76ef8--cloud-credential-operator-iam-ro-vn2ns-policy
    user: ci-ln-vjb5l1t-76ef8--cloud-credential-operator-iam-ro-vn2ns
  provisioned: true
