---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  annotations:
    capability.openshift.io/name: CloudCredential+CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2026-01-28T09:28:42Z"
  generation: 1
  managedFields:
  - apiVersion: cloudcredential.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
        f:lastSyncGeneration: {}
        f:provisioned: {}
    manager: cloud-credential-operator
    operation: Update
    subresource: status
    time: "2026-01-28T09:28:42Z"
  - apiVersion: cloudcredential.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
      f:spec:
        .: {}
        f:providerSpec:
          .: {}
          f:apiVersion: {}
          f:kind: {}
        f:secretRef: {}
    manager: cluster-version-operator
    operation: Update
    time: "2026-01-28T09:28:42Z"
  name: openshift-openstack-cloud-controller-manager
  namespace: openshift-cloud-credential-operator
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 0370d296-6904-481d-ab90-157c7e5b835a
  resourceVersion: "3622"
  uid: 8b176c06-d483-410d-ad8b-aa7d4a8c38f0
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
  secretRef:
    name: openstack-cloud-credentials
    namespace: openshift-cloud-controller-manager
status:
  conditions:
  - lastProbeTime: "2026-01-28T09:28:42Z"
    lastTransitionTime: "2026-01-28T09:28:42Z"
    message: CredentialsRequest is not for platform AWS
    reason: InfrastructureMismatch
    status: "True"
    type: Ignored
  lastSyncGeneration: 0
  provisioned: false
