---
apiVersion: discovery.k8s.io/v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.130.0.15
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-108-54.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: authentication-operator-7455db8cdd-mtphg
      namespace: openshift-authentication-operator
      uid: 363ea6e0-b5c6-4318-b056-674f63b4982f
    zone: us-west-1c
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:31:55Z"
    creationTimestamp: "2026-01-28T09:25:49Z"
    generateName: metrics-
    generation: 4
    labels:
      app: authentication-operator
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: metrics
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"32d4f69f-3df2-4095-8762-1fda8dcdf728"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:31:55Z"
    name: metrics-lk4pc
    namespace: openshift-authentication-operator
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: metrics
      uid: 32d4f69f-3df2-4095-8762-1fda8dcdf728
    resourceVersion: "9853"
    uid: 35f4ebfe-8a6c-4f8d-a005-fd9aa72c1b2e
  ports:
  - name: https
    port: 8443
    protocol: TCP
kind: EndpointSliceList
metadata:
  resourceVersion: "34884"
