---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2026-01-28T09:43:16Z"
  generation: 1
  labels:
    app.kubernetes.io/component: metrics-server
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: openshift-monitoring
  managedFields:
  - apiVersion: monitoring.coreos.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
      f:spec:
        .: {}
        f:endpoints: {}
        f:namespaceSelector: {}
        f:scrapeClass: {}
        f:selector: {}
    manager: operator
    operation: Update
    time: "2026-01-28T09:43:16Z"
  name: metrics-server
  namespace: openshift-monitoring
  resourceVersion: "23011"
  uid: 88ef5d66-935e-46e5-b246-42ba8d996cbf
spec:
  endpoints:
  - port: https
    scheme: https
    tlsConfig:
      ca: {}
      cert: {}
      insecureSkipVerify: false
      serverName: metrics-server.openshift-monitoring.svc
  namespaceSelector: {}
  scrapeClass: tls-client-certificate-auth
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics-server
      app.kubernetes.io/name: metrics-server
      app.kubernetes.io/part-of: openshift-monitoring
