---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2026-01-28T09:26:06Z"
  generation: 1
  managedFields:
  - apiVersion: monitoring.coreos.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:endpoints: {}
        f:namespaceSelector:
          .: {}
          f:matchNames: {}
        f:selector: {}
    manager: cluster-bootstrap
    operation: Update
    time: "2026-01-28T09:26:06Z"
  name: promtail-monitor
  namespace: openshift-monitoring
  resourceVersion: "1927"
  uid: 2434984f-23ed-471a-8ebe-08983ed067ea
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    bearerTokenSecret:
      key: ""
      name: ""
    interval: 30s
    port: metrics
    scheme: https
    targetPort: 9001
    tlsConfig:
      ca: {}
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      cert: {}
      serverName: promtail.openshift-e2e-loki.svc
  namespaceSelector:
    matchNames:
    - openshift-e2e-loki
  selector: {}
