---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpDZ0F3SUJBZ0lJUnByV0xoZU9FTmd3RFFZSktvWklodmNOQVFFTEJRQXdNREV1TUN3R0ExVUUKQXd3bGIzQmxibk5vYVdaMExXVjBZMlJmWlhSalpDMXphV2R1WlhKQU1UYzJPVFU1TWpFNU5UQWVGdzB5TmpBeApNamd3T1RJek1UVmFGdzB6TVRBeE1qY3dPVEl6TVRWYU1FQXhLREFTQmdOVkJBb1RDMlYwWTJRdFkyeHBaVzUwCk1CSUdBMVVFQ2hNTGMzbHpkR1Z0T21WMFkyUXhGREFTQmdOVkJBTVRDMlYwWTJRdFkyeHBaVzUwTUlJQklqQU4KQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcjBFd1R6a0Q1bUZNTy9yTWlCZXhVUGlDbSsycgp4TEJGVVQ5bHBGazFVNnE1SFZDKzVyMkZDYy9HM0lyVFEvZWZOM0YzWTlZU1dQU2xjVXBzMHFoYm1EN0tWZmJ4Cmd4djRBNXNuRlkxSWdsMWRDZmRPUjR1NS9BckMyb3E5N3FnVHk1ZU5TbzNCd0xRVDlwNmlrUjRsdnkzZkFxY0IKU3FOM1JQNzBKV0txNU1HUWxUUlNrSE5oc08ybWZtblFmSmUyVGhNUnZOSDdpNDI0Tk40R095SnFoU3JhSTY1aAp4b21QeU1KOU9laCtpRTV0Y3QxaWpLcFpUQmYzUC9KK2N2WXBqY2dTL3UwOGxpMk1NWi9jMkh0b1hHaE9vbE9yCkovUDVWemlySlF4Nk5nVGV1bnNDcGhOaXF4WXViSEpWU2loc29jcTFjdGVaZW9pWXVLUHN6ZFVKalFJREFRQUIKbzFZd1ZEQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3SXdEQVlEVlIwVApBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlM5bmEwK3h0QTE2cW5aT2E3cVQ2bk0yNVlzUVRBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFUQ0ozWDBEd2NGNE5aTTAzTnVtWkYzSUpTNSs0bzh5ckpZY0cvMEE5cmFWdXVqWUkKbEFGbnp4ZVh3ZktYQS9mdGtWVXdGWHN4R0NSOTdlZjI4TXRZZEV1Ky9DTTh1OFA4TEp1dzFlUGcwVlJDYkIzcgpZSlVsdEZTbUkvMmRUd1BBTG14bStvOWRmU0NUaUR2WXV4NTZ0Ry82UElLM01YdnJndXEyL0szNlpuc2lVT1FICkxmZXJoMkJMYk8vQVhvZEYrQkZlTHdTY2ZGbStkSlNDSkpvYnhQRDZxRTVCM3RjbkUwaUl0ZVpqVWtiak5ocUoKZGVFeFBhaTd1VThrZm9TMko1OXU4U3psUTNjc2hKR1pOTWloSVMwT0UybjVmWE1JVnVFclNDY3FWaE0reVgwOApmZkhFdDhwVUNEc2hLcFFOQW5adlZHejFhNTl2QVZ2MG93WTVQZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-issuer: openshift-etcd_etcd-signer@1769592195
      auth.openshift.io/certificate-not-after: "2031-01-27T09:23:15Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:23:15Z"
      certificates.openshift.io/refresh-period: 36792h0m0s
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      openshift.io/description: Client certificate for apiserver, cluster-etcd-operator
        and etcdctl to reach etcd. Generated by cluster-etcd-operator for etcd. This
        certificate is valid for 1825 days and starts refreshing after 1533 days.
      openshift.io/owning-component: etcd
      release.openshift.io/create-only: "true"
    creationTimestamp: "2026-01-28T09:25:58Z"
    labels:
      auth.openshift.io/managed-certificate-type: target
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data: {}
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
            f:release.openshift.io/create-only: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
        f:type: {}
      manager: cluster-version-operator
      operation: Update
      time: "2026-01-28T09:25:58Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:certificates.openshift.io/refresh-period: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
          f:labels:
            .: {}
            f:auth.openshift.io/managed-certificate-type: {}
      manager: cluster-etcd-operator
      operation: Update
      time: "2026-01-28T09:30:42Z"
    name: etcd-client
    namespace: openshift-etcd-operator
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 0370d296-6904-481d-ab90-157c7e5b835a
    resourceVersion: "6701"
    uid: c6231b2b-eb50-4eed-805e-7be80dc3a382
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUekNDQWplZ0F3SUJBZ0lJYWx1ZzZyVGZkY0l3RFFZSktvWklodmNOQVFFTEJRQXdOekUxTURNR0ExVUUKQXd3c2IzQmxibk5vYVdaMExXVjBZMlJmWlhSalpDMXRaWFJ5YVdNdGMybG5ibVZ5UURFM05qazFPVEl4T1RVdwpIaGNOTWpZd01USTRNRGt5TXpFMVdoY05NekV3TVRJM01Ea3lNekUxV2pCQU1TZ3dFZ1lEVlFRS0V3dGxkR05rCkxXMWxkSEpwWXpBU0JnTlZCQW9UQzNONWMzUmxiVHBsZEdOa01SUXdFZ1lEVlFRREV3dGxkR05rTFcxbGRISnAKWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUw0MzVGUmNZa2dNV01KNm9CdgpDMXdzQVpyeEZrN1RSRXoxWld0aTlYZlVNSW5xSFRxUzMrYVYvemk4eklQdkJNM0Q1RDNUTGRKUWhYd0Jod21DCjBOUjA4U0hDelJGa0tqN0tENzJXQ2Z4YVBrRlhkLys3MkVJWTZQTWdlSFZGOGV4NURxR2MzRGVyb2RZSDlwRXgKQXIrWHg0VDBJdm5hOGhsVldSMFNIb1RHVnB4b3RYbks0dWF5VklZUVF5aEpxdGdnb3B2ajJ4YmI3ZXMxbTNxWgp3RHFrelRpUGowTkVwbzRXd1lXZmpMc29iRGlGTHJLNk1sKzNhbnZWTjJlbGtIMHd2OEpSeFV4YnJmdjgyMVNGCkpXdzJYSjVlMFRvek84WWltUmZGcTVWbXVvOFV1TS8yOGtaY1JDT2ppZVZURzdnWERjeHI2eDJJVnFXN04wOEoKVWxjQ0F3RUFBYU5XTUZRd0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQwpNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVV5RHk3Y0JmZHd0MWJzeVduZE9ybExBN0ZzVGd3CkRRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBbVNZdTNmMlRwUVQreUxFb2o4R2hOZ3dPMG9GQjA0WklGRnd6SUgKWE0zRmZLcm02QTNjcVZobE5sVUtXME9WNHgwUDJsWHBkbHFNM3pRTFd5MFZvYnN3Zm9HOUhObnRvYSttdDhNRQpLL1Z4aTBsUW1QOU1rWkJlZ2N4eFMreFYwb093YnN2NlBRSW9mUE51NE52Rm5JNUI2dU8zRW1acElsMEFDT3lTClBnTnEzeWg3YWZEa0V5SzJvWTFKUWZCYVdIVHdhOFhKK2h0d3grc3EydzRmZEphMlc3Ym0ycXNuVEM5cFpTak8KaitGYU4wdFJYcHhSQ29ScEhzZzhnMFRSdVEyNGt5cVIzUjJqNk5tYjJCNUpVcFZ0TDd3ejRndU5JVnZhWm5rSwpKT2s0RDMrcUs1LytOVnNuZ3hRUjlRVjVXaXFEbyt2R0pZQlVHWTNaWWNBN3lGOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-issuer: openshift-etcd_etcd-metric-signer@1769592195
      auth.openshift.io/certificate-not-after: "2031-01-27T09:23:15Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:23:15Z"
      certificates.openshift.io/refresh-period: 36792h0m0s
      openshift.io/description: Client certificate for Prometheus ServiceMonitors
        to reach etcd grpc-proxy to retrieve metrics. Generated by cluster-etcd-operator
        for etcd. This certificate is valid for 1825 days and starts refreshing after
        1533 days.
      openshift.io/owning-component: etcd
    creationTimestamp: "2026-01-28T09:30:41Z"
    labels:
      auth.openshift.io/managed-certificate-type: target
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:certificates.openshift.io/refresh-period: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
          f:labels:
            .: {}
            f:auth.openshift.io/managed-certificate-type: {}
        f:type: {}
      manager: cluster-etcd-operator
      operation: Update
      time: "2026-01-28T09:30:41Z"
    name: etcd-metric-client
    namespace: openshift-etcd-operator
    resourceVersion: "6623"
    uid: 524dfdf8-88bc-4662-9c25-bda9178aa200
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQrVENDQXVHZ0F3SUJBZ0lJV2ZFQWtkVzg1d0V3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkROYUZ3MHlPREF4TWpnd09UTXdORFJhTUM0eExEQXFCZ05WQkFNVEkyMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMV1YwWTJRdGIzQmxjbUYwYjNJdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUEycngxZVo4TDRxQzRTb2lIb1FtN0dZeTlvN0gxNjdGWnVRcWkzL2R4Uis0SwpNNFhncEdyaDFHbTEwWUVxQkRoRkJRQms0dkU1Z1NRRWVnRVRoYWJnUUt3aGRDajRVSGU1U2cxS25Yd1U5NmExCkFWS0lZTDFoaUhHYW1sdTNDNTQxY1NYbDhTbW9QcDV6MUN6M2pBQmoyT3ozWVhDREkydDNLSW03YUlTa1JlZysKTjV2NFdlMjExV2dEODVHOW5Hdmt0SXRqamtmMGkvUXVNUmxkYUN6VlJ1ODNmaDBlVlB1QWJZSlhpdEowV2FPcApxRmdnOHVDTDVuQlVaUWsyZnNqUjU4azE5SktnOUw4bjJRS3Zla0svSlZ5dS9SK1JHR0VLTU5qMitScVlERFlpCnFCL0dnZG9RNXVlaGNxayttVHNBZjkzajlXZ29VN2tTeU5NUEhHSG5kUUlEQVFBQm80SUJFVENDQVEwd0RnWUQKVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQXdHQTFVZEV3RUIvd1FDTUFBdwpIUVlEVlIwT0JCWUVGSGxUYWJxV0l2OHdFM3lmaCs0SnRMamxQTnlLTUI4R0ExVWRJd1FZTUJhQUZKakJmbGhWClcrS2hIM3o2T2ozYXBjQ3RQUFhyTUdFR0ExVWRFUVJhTUZpQ0kyMWxkSEpwWTNNdWIzQmxibk5vYVdaMExXVjAKWTJRdGIzQmxjbUYwYjNJdWMzWmpnakZ0WlhSeWFXTnpMbTl3Wlc1emFHbG1kQzFsZEdOa0xXOXdaWEpoZEc5eQpMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNRFVHQ3lzR0FRUUJrZ2dSWkFJQkJDWVRKRFl5T0dVeU9UZzFMVEZtCllqVXROREJpWkMwNU9UYzNMV1ppTURVeU5HUTBaakk1TnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXQweGkKUUo4RFNKdEJ5dzBwZmtzb04yMWJYdTJOSkVMaXNWZkNCcUNUVlR5VUlqL3loMGFkYWN6VDhqSFR1M29tQVg0dgo4N0lXb0VRM2hMazN0eWd6dkpjSmx0bk9QNm1HQUpDOTRqWXgrVUJ4U1FyUWlqU2dNNzJ6blRlUDNjNWN2MEI2CkNkU1lxbkdnMDJmUmJXU0hpVGdicnAycnVOcDdlQnJzREhyVEs1ODVWTXUwZVdQWHE1LzJMSXkvUzN2WUNBcjYKdlpLaVBTSkZXaW9mVXZ0aU54Ylh4S2hxSVVsSmh5b2pSd2ZUbWZCWm5aa0pPRi9oMFNNWFhrR0ZNcEFVTDZJcgpaOUh4dzlCOTZma3BYSGl1TldwYU5GaDB5Uy9LZm56Q2dVVVhZUm1XWExRUzl2Z1VXeTlJVzF5SUUrcmp3U0h4CncwMzlCbUgrcmdDTkJVdWU2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-etcd-operator.svc and is annotated to the service with annotating
        a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        etcd-operator-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:44Z"
      service.alpha.openshift.io/originating-service-name: metrics
      service.alpha.openshift.io/originating-service-uid: 628e2985-1fb5-40bd-9977-fb0524d4f297
      service.beta.openshift.io/expiry: "2028-01-28T09:30:44Z"
    creationTimestamp: "2026-01-28T09:30:45Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"628e2985-1fb5-40bd-9977-fb0524d4f297"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:45Z"
    name: etcd-operator-serving-cert
    namespace: openshift-etcd-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: 628e2985-1fb5-40bd-9977-fb0524d4f297
    resourceVersion: "6898"
    uid: 78875bb2-b9c8-4488-bb90-7881e25c304c
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35036"
