---
apiVersion: discovery.k8s.io/v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.130.0.29
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-108-54.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: console-operator-5cfd85677c-vtxq2
      namespace: openshift-console-operator
      uid: c5459a4b-bf52-4ff7-990e-3574633725ee
    zone: us-west-1c
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:41:09Z"
    creationTimestamp: "2026-01-28T09:26:18Z"
    generateName: metrics-
    generation: 5
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: metrics
      name: console-operator
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
            f:name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"8f4efcff-31a3-414f-8d3d-cf357251cd23"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:41:09Z"
    name: metrics-rdwxb
    namespace: openshift-console-operator
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: metrics
      uid: 8f4efcff-31a3-414f-8d3d-cf357251cd23
    resourceVersion: "19362"
    uid: 2760bef7-885f-4573-8b85-e32c098d957f
  ports:
  - name: https
    port: 8443
    protocol: TCP
kind: EndpointSliceList
metadata:
  resourceVersion: "35023"
