---
apiVersion: oauth.openshift.io/v1
grantMethod: auto
kind: OAuthClient
metadata:
  creationTimestamp: "2026-01-28T09:43:39Z"
  managedFields:
  - apiVersion: oauth.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:grantMethod: {}
      f:redirectURIs:
        .: {}
        v:"https://console-openshift-console.apps.ci-ln-vjb5l1t-76ef8.XXXXXXXXXXXXXXXXXXXXXX/auth/callback": {}
      f:secret: {}
    manager: console
    operation: Update
    time: "2026-01-28T09:43:39Z"
  name: console
  resourceVersion: "23274"
  uid: 6d0a8524-ed1b-45d5-afbd-2bb507e76e9a
redirectURIs:
- https://console-openshift-console.apps.ci-ln-vjb5l1t-76ef8.XXXXXXXXXXXXXXXXXXXXXX/auth/callback
secret: ipeZiV8SJN5YyTVM8AfYWMXvq0tV507fGpaiZhTNup0
