---
apiVersion: discovery.k8s.io/v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.0.108.54
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-108-54.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: kube-controller-manager-ip-10-0-108-54.us-west-1.compute.internal
      namespace: openshift-kube-controller-manager
      uid: 8c08f38e-1d03-461f-bf12-56cfca5636d7
    zone: us-west-1c
  - addresses:
    - 10.0.102.200
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-102-200.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: kube-controller-manager-ip-10-0-102-200.us-west-1.compute.internal
      namespace: openshift-kube-controller-manager
      uid: f54fda70-2ab8-45ec-b9f8-a71d8bdd53f0
    zone: us-west-1c
  - addresses:
    - 10.0.3.203
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-3-203.us-west-1.compute.internal
    targetRef:
      kind: Pod
      name: kube-controller-manager-ip-10-0-3-203.us-west-1.compute.internal
      namespace: openshift-kube-controller-manager
      uid: 66639111-8871-4a6e-92e9-a9f985a407d7
    zone: us-west-1a
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:49:37Z"
    creationTimestamp: "2026-01-28T09:30:42Z"
    generateName: kube-controller-manager-
    generation: 27
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: kube-controller-manager
      prometheus: kube-controller-manager
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
            f:prometheus: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"222ee297-d987-47a8-9805-0d1bdd110d9d"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:49:37Z"
    name: kube-controller-manager-5j9lw
    namespace: openshift-kube-controller-manager
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: kube-controller-manager
      uid: 222ee297-d987-47a8-9805-0d1bdd110d9d
    resourceVersion: "26710"
    uid: 25bb7cea-c14f-4506-baed-ec11c7b2ad73
  ports:
  - name: https
    port: 10257
    protocol: TCP
kind: EndpointSliceList
metadata:
  resourceVersion: "35092"
