---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2026-01-28T09:31:00Z"
  labels:
    control-plane: operator-controller-controller-manager
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:control-plane: {}
      f:rules: {}
    manager: cluster-olm-operator
    operation: Update
    time: "2026-01-28T09:31:00Z"
  name: operator-controller-metrics-monitor-role
  namespace: openshift-operator-controller
  resourceVersion: "7710"
  uid: 2f4344b1-c893-4261-aa7e-0ea407d907f9
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
