---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.130.0.39/23"],"mac_address":"0a:58:0a:82:00:27","gateway_ips":["10.130.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.130.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.130.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.130.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.130.0.1"}],"ip_address":"10.130.0.39/23","gateway_ip":"10.130.0.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.130.0.39"
          ],
          "mac": "0a:58:0a:82:00:27",
          "default": true,
          "dns": {}
      }]
    openshift.io/required-scc: restricted-v2
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    security.openshift.io/validated-scc-subject-type: user
  creationTimestamp: "2026-01-28T09:29:03Z"
  generateName: insights-operator-c7975f6f-
  generation: 1
  labels:
    app: insights-operator
    pod-template-hash: c7975f6f
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/required-scc: {}
          f:target.workload.openshift.io/management: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"19956ad3-daf4-485c-9c07-56690990d6d5"}: {}
      f:spec:
        f:containers:
          k:{"name":"insights-operator"}:
            .: {}
            f:args: {}
            f:env:
              .: {}
              k:{"name":"POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"POD_NAMESPACE"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"RELEASE_VERSION"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8443,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities:
                .: {}
                f:drop: {}
              f:readOnlyRootFilesystem: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/tmp"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/lib/insights-operator"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/run/configmaps/service-ca-bundle"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/var/run/configmaps/trusted-ca-bundle"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/var/run/secrets/serving-cert"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:nodeSelector: {}
        f:priorityClassName: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:runAsNonRoot: {}
          f:seccompProfile:
            .: {}
            f:type: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"service-ca-bundle"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
              f:optional: {}
            f:name: {}
          k:{"name":"serving-cert"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:optional: {}
              f:secretName: {}
          k:{"name":"snapshots"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"tmp"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"trusted-ca-bundle"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
              f:optional: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-01-28T09:29:03Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"PodScheduled"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-scheduler
    operation: Update
    subresource: status
    time: "2026-01-28T09:29:03Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.ovn.org/pod-networks: {}
    manager: ip-10-0-108-54
    operation: Update
    subresource: status
    time: "2026-01-28T09:30:09Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
    manager: multus-daemon
    operation: Update
    subresource: status
    time: "2026-01-28T09:30:10Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.130.0.39"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2026-01-28T09:31:55Z"
  name: insights-operator-c7975f6f-qbb65
  namespace: openshift-insights
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: insights-operator-c7975f6f
    uid: 19956ad3-daf4-485c-9c07-56690990d6d5
  resourceVersion: "9856"
  uid: 73d760e7-9217-4df6-ba2e-f7c261a80aae
spec:
  containers:
  - args:
    - start
    - --config=/etc/insights-operator/server.yaml
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: RELEASE_VERSION
      value: 4.20.0-0-2026-01-28-090915-test-ci-ln-vjb5l1t-latest
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:d563f26ef566da43a1c8ab34d29852f477533686074d0adbd29bb98e51195571
    imagePullPolicy: IfNotPresent
    name: insights-operator
    ports:
    - containerPort: 8443
      name: metrics
      protocol: TCP
    resources:
      requests:
        cpu: 10m
        memory: 54Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsUser: 1000270000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/lib/insights-operator
      name: snapshots
    - mountPath: /var/run/configmaps/trusted-ca-bundle
      name: trusted-ca-bundle
      readOnly: true
    - mountPath: /var/run/configmaps/service-ca-bundle
      name: service-ca-bundle
      readOnly: true
    - mountPath: /var/run/secrets/serving-cert
      name: serving-cert
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gp2xw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-108-54.us-west-1.compute.internal
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000270000
    runAsNonRoot: true
    seLinuxOptions:
      level: s0:c16,c15
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: operator
  serviceAccountName: operator
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 900
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 900
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: tmp
  - emptyDir: {}
    name: snapshots
  - configMap:
      defaultMode: 420
      name: trusted-ca-bundle
      optional: true
    name: trusted-ca-bundle
  - configMap:
      defaultMode: 420
      name: service-ca-bundle
      optional: true
    name: service-ca-bundle
  - name: serving-cert
    secret:
      defaultMode: 420
      optional: true
      secretName: openshift-insights-serving-cert
  - name: kube-api-access-gp2xw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:30:29Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:30:09Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:31:55Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:31:55Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:30:08Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 10m
      memory: 54Mi
    containerID: cri-o://13172dcb106986b3d2968c018ce4a9a00b53550a667c5126a92302802e2b5767
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:d563f26ef566da43a1c8ab34d29852f477533686074d0adbd29bb98e51195571
    imageID: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:d563f26ef566da43a1c8ab34d29852f477533686074d0adbd29bb98e51195571
    lastState:
      terminated:
        containerID: cri-o://47bedf8dd833f8cf77b11a56c18ee6ab03b8f0e813be0334a52d88dd319e87c8
        exitCode: 0
        finishedAt: "2026-01-28T09:31:46Z"
        reason: Completed
        startedAt: "2026-01-28T09:30:29Z"
    name: insights-operator
    ready: true
    resources:
      requests:
        cpu: 10m
        memory: 54Mi
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2026-01-28T09:31:52Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1000270000
        uid: 1000270000
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/lib/insights-operator
      name: snapshots
    - mountPath: /var/run/configmaps/trusted-ca-bundle
      name: trusted-ca-bundle
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/run/configmaps/service-ca-bundle
      name: service-ca-bundle
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/run/secrets/serving-cert
      name: serving-cert
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gp2xw
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.108.54
  hostIPs:
  - ip: 10.0.108.54
  phase: Running
  podIP: 10.130.0.39
  podIPs:
  - ip: 10.130.0.39
  qosClass: Burstable
  startTime: "2026-01-28T09:30:09Z"
