---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      operator.openshift.io/spec-hash: d29530d808e44f1f4a698399863590ec8ebf044dbf20277dfeafa074ae9f16aa
    creationTimestamp: "2026-01-28T09:30:44Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:operator.openshift.io/spec-hash: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":6080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":17697,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: cluster-kube-apiserver-operator
      operation: Update
      time: "2026-01-28T09:30:44Z"
    name: apiserver
    namespace: openshift-kube-apiserver
    resourceVersion: "6769"
    uid: 35c79a8e-8236-4570-965e-6b9daac9b157
  spec:
    clusterIP: 172.30.56.132
    clusterIPs:
    - 172.30.56.132
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    - name: insecure-readyz
      port: 6080
      protocol: TCP
      targetPort: 6080
    - name: check-endpoints
      port: 17697
      protocol: TCP
      targetPort: 17697
    selector:
      apiserver: "true"
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "35084"
