---
apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  creationTimestamp: "2026-01-28T09:29:27Z"
  labels:
    app: network-check-source
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:include.release.openshift.io/self-managed-high-availability: {}
        f:labels:
          f:app: {}
        f:ownerReferences:
          k:{"uid":"7763cebb-f1d7-4359-81b8-b55ef9916383"}: {}
      f:spec:
        f:clusterIP: {}
        f:ports:
          k:{"port":17698,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:targetPort: {}
        f:selector: {}
        f:type: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2026-01-28T09:29:27Z"
  name: network-check-source
  namespace: openshift-network-diagnostics
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 7763cebb-f1d7-4359-81b8-b55ef9916383
  resourceVersion: "4579"
  uid: 2158064d-6981-4410-beb6-afbd63e11308
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: check-endpoints
    port: 17698
    protocol: TCP
    targetPort: 17698
  selector:
    app: network-check-source
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
