---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ5akNDQXQ2Z0F3SUJBZ0lJR0U0d3Y3WllaY293RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRKYUZ3MHlPREF4TWpnd09UTXdORE5hTUMweEt6QXBCZ05WQkFNVEltMWxkSEpwClkzTXViM0JsYm5Ob2FXWjBMV1J1Y3kxdmNHVnlZWFJ2Y2k1emRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRQ3lpZDhUL2xQa1RsRlp4bm5YK0NEY294cTRhbG5MbmRIVGFyNm9LbGlyVEVrRwp1S2VGNDVaRklZaVY2eXJhN2svTlk2QVAzQ0ZrSGFIeHVIZEFVYlgvRVlCemxUclNzMlZ2NnFDU05FRUlJbWNvCnRHNzdHSXdacG1qaFZvYzYxMWs4cU9Ic2VWUHByQjRLdE9MR01VUWpXLy9wbG9xcCtsUmZQeCtrQUp1NS9qakkKYUtDeXVvSTlnUUlPUFJNNkZKaE1UYVZQNTdxOGdYM2kwMkl2MjlWQlNDRTBLRENBbHZOS3RvcjMrYmpHelRvQwpzQ3RZUFV1Rmh4aG1RTmlWQ3JqOHpGV0JwU3RSTlUvenNYQllZaUJNT1NCUEFmS1BKZmRmV2ZQdE9yVXNWekJWCkFhdHI0U0RtZHVOY2JodUhZK1UyWmZMMmYwNFJjbDdpZG9IN0E5SGZBZ01CQUFHamdnRVBNSUlCQ3pBT0JnTlYKSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEQVlEVlIwVEFRSC9CQUl3QURBZApCZ05WSFE0RUZnUVVJNWxLWFUveU1md1FjQWoxSnZmOW41RkovNHd3SHdZRFZSMGpCQmd3Rm9BVW1NRitXRlZiCjRxRWZmUG82UGRxbHdLMDg5ZXN3WHdZRFZSMFJCRmd3Vm9JaWJXVjBjbWxqY3k1dmNHVnVjMmhwWm5RdFpHNXoKTFc5d1pYSmhkRzl5TG5OMlk0SXdiV1YwY21samN5NXZjR1Z1YzJocFpuUXRaRzV6TFc5d1pYSmhkRzl5TG5OMgpZeTVqYkhWemRHVnlMbXh2WTJGc01EVUdDeXNHQVFRQmtnZ1JaQUlCQkNZVEpEUXhNak15TXprMUxXTTVaR0V0Ck5EVTROaTFoTmprd0xXUmpZakV4TXpjMU1XSTNOekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBWUQxVnlEN0kKNVRFSTgwZGZidnVmSExlMDArQ1VydXhYbjhHM0NlSE1iS21aZEFNOFhKZFZENitTT25LOU56dDdPVTFzZDJRMQpza1hKSWVEbzMxUFRPbkE2V0d4OWU0OHdia2k4ejI1eG12VW9VcXlxWTc1eUtKVXpMbjdTQVRyV25MVDU5Z050CmFPdEFyQjFyRmVnTkxwYW5IY2ZnR3pQWmNnQUhkOHdFOFVUR09hK21PSktoQWRJUi9vMWkzRzV6TnlFSzdQMkwKajBadWJRamlXc1h0akdKMHoydlJZNGtmdEFDUHN3TUhYT093OVU1eVRCc2NCa2JxUURiZEJVV3dtMHJoa211bApPbDQ3K3hZRC83bExvSE8wRnp2R25tRCtweDJ3UlZ0bUhTUWJrNlE1QTRxc2NPY1RYcmtqdGdHbjJENlZwT1lzCldDUFlFQ1NXaFMzSjBBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRFVUQ0NBam1nQXdJQkFnSUlFdzBPL2lwV0lhWXdEUVlKS29aSWh2Y05BUUVMQlFBd05qRTBNRElHQTFVRQpBd3dyYjNCbGJuTm9hV1owTFhObGNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVGMyT1RVNU1qWXpOVEFlCkZ3MHlOakF4TWpnd09UTXdNelJhRncweU9EQXpNamd3T1RNd016VmFNRFl4TkRBeUJnTlZCQU1NSzI5d1pXNXoKYUdsbWRDMXpaWEoyYVdObExYTmxjblpwYm1jdGMybG5ibVZ5UURFM05qazFPVEkyTXpVd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNkRnSWU0WDhzNEprQkpKclJYMzM2UGlQeHl2TEY4a0s4CmxYTUhIZkJsdHNCV2xQSkxnS2EzQklsN1RRNUpiS2JvMXdPSXAvaEloVFFtOS9DVlo2d1RJSHlYU2ZGQUtCNkUKdm90MlZ0bHE5NlhwNk5WTE53cHJIbnRxeURtNXY5V1ZkbnBjU2o0MVhmaGJhSzE5eUlHeXJEbFBLOGJQVVhIcAp0OVVsUXZzeXhsQW4rZ2M1UklHaE81S01rN01abTNmVXI0QnhOMkp5aFhlb3NuWkRXUTJMVjhwNmhBWmFmdFNPCkZCTndnOW82S0kzT0tQN0VJYkVwRk41QUdxNVpwWmpadDQ5SVlDNFJ5ZzJiMEk4dGNXVzhqYmx3RkFMWXFxUloKTVUrZVhvZXZmVWwrZVIwL1o0cGs3RmdBNEgydTVTU2hjNDN4cXBtcWhUU3k0WGJWVC9TUkFnTUJBQUdqWXpCaApNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1l3WDVZClZWdmlvUjk4K2pvOTJxWEFyVHoxNnpBZkJnTlZIU01FR0RBV2dCU1l3WDVZVlZ2aW9SOTgram85MnFYQXJUejEKNnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVI2VVh3SDByaVh6NEJraXM2Q0JGdk9GL2M1TEtucVd2VHdQRgp6YmpjVkFTL01vS1F1WGplVUhldnR0QzJHQ1FJMTBuQnJhSlhSSU5Ia1VPNUxhVTJVbEExWHovNmZobEYyQkpLCmVKa2RocXdCcUNyOWprSEpWTWRhbnBnblNNQ1RyK0NhU1QzR3dqLzRNTWFIdy9GRjhtNDdWQWRaUmdqM2VjSHQKSEZ5UGJHSDFvVmJmSUpraG5iYUJwRkxWeWUydWMrN2t4ZHUwM3huajRPVFFuQzc1am5nMStjbUtzWWdVZ3hDZApDMDN0VFk4VTlBOWRNUmtNSGlyVHVUanFJcklCMGhaYUQ0eFlTTVZIWWtkSHg4c2JXcmg4bC80QzlJQjBqUVBFCldKMm9NTU9pTWpkeUhma0hnS29MOHVBVXp0empUZnd2WDRFSXB4UGs1bHlJZ0YzeTZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/metrics with hostname
        metrics.openshift-dns-operator.svc and is annotated to the service with annotating
        a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        metrics-tls''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:43Z"
      service.beta.openshift.io/expiry: "2028-01-28T09:30:43Z"
      service.beta.openshift.io/originating-service-name: metrics
      service.beta.openshift.io/originating-service-uid: 41232395-c9da-4586-a690-dcb113751b77
    creationTimestamp: "2026-01-28T09:30:44Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.beta.openshift.io/expiry: {}
            f:service.beta.openshift.io/originating-service-name: {}
            f:service.beta.openshift.io/originating-service-uid: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"41232395-c9da-4586-a690-dcb113751b77"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:44Z"
    name: metrics-tls
    namespace: openshift-dns-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: metrics
      uid: 41232395-c9da-4586-a690-dcb113751b77
    resourceVersion: "6764"
    uid: a31edff4-173d-4c01-9349-0709f4990288
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35034"
