---
apiVersion: v1
kind: Service
metadata:
  annotations:
    operator.openshift.io/spec-hash: efe4f2f5d8efbcf19c0f55e33c097d427deb03e23e258c8f1ae3031eac8cc136
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1769592635
    service.beta.openshift.io/serving-cert-secret-name: operator-controller-cert
    service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1769592635
  creationTimestamp: "2026-01-28T09:31:08Z"
  labels:
    control-plane: operator-controller-controller-manager
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:operator.openshift.io/spec-hash: {}
          f:service.beta.openshift.io/serving-cert-secret-name: {}
        f:labels:
          .: {}
          f:control-plane: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: cluster-olm-operator
    operation: Update
    time: "2026-01-28T09:31:08Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:service.alpha.openshift.io/serving-cert-signed-by: {}
          f:service.beta.openshift.io/serving-cert-signed-by: {}
    manager: service-ca-operator
    operation: Update
    time: "2026-01-28T09:31:08Z"
  name: operator-controller-service
  namespace: openshift-operator-controller
  resourceVersion: "8268"
  uid: 2be556f6-f11e-43a0-8a81-58ad0f9b1270
spec:
  clusterIP: 172.30.21.76
  clusterIPs:
  - 172.30.21.76
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: operator-controller-controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
