---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    capability.openshift.io/name: MachineAPI
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2026-01-28T09:26:18Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"0370d296-6904-481d-ab90-157c7e5b835a"}: {}
      f:rules: {}
    manager: cluster-version-operator
    operation: Update
    time: "2026-01-28T09:26:18Z"
  name: prometheus-k8s-machine-api-operator
  namespace: openshift-machine-api
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 0370d296-6904-481d-ab90-157c7e5b835a
  resourceVersion: "2553"
  uid: 69b22c5b-e086-47c6-96b0-5db884b195d4
rules:
- apiGroups:
  - ""
  resources:
  - namespace/metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
