---
apiVersion: network.operator.openshift.io/v1
kind: OperatorPKI
metadata:
  creationTimestamp: "2026-01-28T09:29:30Z"
  generation: 1
  managedFields:
  - apiVersion: network.operator.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"7763cebb-f1d7-4359-81b8-b55ef9916383"}: {}
      f:spec:
        f:targetCert:
          f:commonName: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2026-01-28T09:29:30Z"
  name: network-node-identity
  namespace: openshift-network-node-identity
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 7763cebb-f1d7-4359-81b8-b55ef9916383
  resourceVersion: "4668"
  uid: 55b3f0f8-c2b0-408b-9b88-0465859d9d6b
spec:
  targetCert:
    commonName: 127.0.0.1
