---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPVENDQWlHZ0F3SUJBZ0lJZFVhVmZ3WGdIcWt3RFFZSktvWklodmNOQVFFTEJRQXdPREVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1TSXdJQVlEVlFRREV4bHJkV0psTFdOdmJuUnliMnd0Y0d4aGJtVXRjMmxuYm1WeQpNQjRYRFRJMk1ERXlPREE1TXpBME9Gb1hEVEkyTURJeU56QTVNekEwT1Zvd0tURW5NQ1VHQTFVRUF4TWVjM2x6CmRHVnRPbXQxWW1VdFkyOXVkSEp2Ykd4bGNpMXRZVzVoWjJWeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0MKQVE4QU1JSUJDZ0tDQVFFQXRqTTg2dy9PU05wVnZ1bmhWSkJhaEY4clJFdnhQQ1pzY09MOURSRGJrVEFLYTlvKwpDclBEVkowMmlNdVlDZGltZ0Q0Q1hqSXkrREphQXllYXBHYXpCaGlnWkFBY2hDRVJlQk1Qc25EZXJCVE9EaVA3Ci9FQkkxeXZzYWxOU2FYczZBK0VZd0ptVzJUdmhqVWw0QUpwWVVSRUVPQ0RBN25wMklkcm1XU08yQmhxU0ZZK2MKOFNTTjRMYlR0c1FNTXQzbUMxdWhXRjUwZE5NeVZSdzN5M0ppb1dVQWNUQ2VHcDBOT28zY0ZyNVJOWE92ZEcweApQa1NQc0NCSDN0c1FNSlJ5YmFpa0hScVJ5QkN6QVEzcGgwUjgvb0F4MW9jVDQ1aGJISS95d0dNLzZSeUZwOVZPCldVb3crQkxublE5S2FESEhmaldsaEhlV3duWGVwS3Z5RVZ2RG93SURBUUFCbzFZd1ZEQU9CZ05WSFE4QkFmOEUKQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRQpHREFXZ0JSbmNya1FIZXZNc1BsUGxZWlhJb2JsVm90amtUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFvR2VWCnNtTGtYTVArN3VybnhNMUNwV0JVMFVQV0NpSmFHS1ZMYkJNUmFJRjdsblpSRVJsUVZIYVVUeWduZnI3NGxkdWgKQ0F2d21LN3p0VStaRURFS2loY3lkc2hMWGhIeHFLeHRKN3N1RGo3Skp5RkJtU051SmxUNU9DRGErWEsxL2xkVgoydVpYY1Yrd2FBZGRMMlNVYk1YTi9NSzQ3U2tsdlZWK3dZSTd6ZDIwYUJIVWM0VFIyaHRSY0dtMmViOVpSZVM5CmxPT0tPUjNwQjM5OUsrQ1paaFl0ZGhlSE9Tb2svVlk3d0FHRFR0djlVdVdYYXAydytuWnhCNHNJZGlGMEM1ckoKTjhCL1ltYldZZDZCR0R5Rk5SYkdlZG9IMmo3WmxST3lrcnMzWFJDVjduR2RxRklvdytSc2NaSkxOVCt4YWdKcQpJd1dScDhWaEM0ak5Ba3dSdnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-issuer: kube-control-plane-signer
      auth.openshift.io/certificate-not-after: "2026-02-27T09:30:49Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:30:48Z"
      certificates.openshift.io/auto-regenerate-after-offline-expiry: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1631,'[sig-apps]
        Deployment RollingUpdateDeployment should delete old pods and create new ones
        [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]'
      certificates.openshift.io/refresh-period: 360h0m0s
      openshift.io/description: Client certificate used by the kube-controller-manager
        to authenticate to the kube-apiserver.
      openshift.io/owning-component: kube-apiserver
    creationTimestamp: "2026-01-28T09:30:50Z"
    labels:
      auth.openshift.io/managed-certificate-type: target
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:certificates.openshift.io/auto-regenerate-after-offline-expiry: {}
            f:certificates.openshift.io/refresh-period: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
          f:labels:
            .: {}
            f:auth.openshift.io/managed-certificate-type: {}
        f:type: {}
      manager: cluster-kube-apiserver-operator
      operation: Update
      time: "2026-01-28T09:30:50Z"
    name: kube-controller-manager-client-cert-key
    namespace: openshift-config-managed
    resourceVersion: "7284"
    uid: e562e3e5-30d1-4580-9d36-bbf483bf4002
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNRENDQWhpZ0F3SUJBZ0lJU1FrWVFKcG11RVl3RFFZSktvWklodmNOQVFFTEJRQXdPREVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1TSXdJQVlEVlFRREV4bHJkV0psTFdOdmJuUnliMnd0Y0d4aGJtVXRjMmxuYm1WeQpNQjRYRFRJMk1ERXlPREE1TXpBME1Wb1hEVEkyTURJeU56QTVNekEwTWxvd0lERWVNQndHQTFVRUF4TVZjM2x6CmRHVnRPbXQxWW1VdGMyTm9aV1IxYkdWeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQXJORDF0RVpKaTk2ZUJYNDRhOVdZVFlqbFJYamxJV0JGTHlEeEE3aW5LYVNYa1VnRnZScDBQWnFnTXphLwpwREVFcldBUHRwa0xwUE10UG43MTM2QmZrSnJXcEtucXFabyt4UjNFaUNyaFNrREl3SVp6OHNFRVJmazNlQ21DCjJxdVFzcVZNaERyUHczYWk0R1MvU2t1OG1ESTBIcXo0OG5GQWUvSThLMU9XeDVmaDVZUVpIdmoySHA5ZGlCc0EKbWxwOTJCWmxHLzQwRUh2dEtQTWpKTTlKV3Y1bnlLY2crZnpIMDN5bTJhNWJ5cW51M2tnSVhhd2NOZEw1aWYydwpwTEhoMmR5WUN4MkhLVzkrQmFCNEd2UUx1TER6djFDdDVTMWhKaHA2aWdPS0RHZHBxSlB5LzNlSENWQ0R3eGY2CnNTVmJaWEg5Y0JabFhCcjhKcHgxUHdEdUN3SURBUUFCbzFZd1ZEQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WUQKVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlJuY3JrUQpIZXZNc1BsUGxZWlhJb2JsVm90amtUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFaYlBCZks0ditDblpzUlBsCi81cDc1TVdsZDJFY21ROElBSTdhanRaMEZtdUt0eUJYYzRaaytiTUdxQmsxYVN2YWREUVFzZHBHNEgyOUI0encKaWZMcWxibmltVzI5bnRhZUlnNXcrOXJyVnY2Vy9xaXdNRDdDdnVIQW5rS2MyS01SMCtkZEFmZGcxamtqaEpZcwo3d2djUHpNTm42WDVuNVFEdGFoOVNlTTgva1VrT1ZPWUhkbXBnZnNFMTBzNHovdmVKTWpBUWdzSGtwZ3BrNzNUCjF4VW5abkY1RUcwakFONFFYYnhUSnhtVTBPWWduK0VWWnhXR0QrWndSRE56R0RraEZMQWhWemcwNEI5bUxUYTMKeVRXVUpqNXNpOU11bXliT3NFWVBaWU8rdHcvUFFETmNoMlBWV2FhKzRtNEY5OGVRNkd4RUFaenlneUMveG1MYQpBcjVzTnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      auth.openshift.io/certificate-issuer: kube-control-plane-signer
      auth.openshift.io/certificate-not-after: "2026-02-27T09:30:42Z"
      auth.openshift.io/certificate-not-before: "2026-01-28T09:30:41Z"
      certificates.openshift.io/auto-regenerate-after-offline-expiry: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1631,'[sig-apps]
        Deployment RollingUpdateDeployment should delete old pods and create new ones
        [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]'
      certificates.openshift.io/refresh-period: 360h0m0s
      openshift.io/description: Client certificate used by the kube-scheduler to authenticate
        to the kube-apiserver.
      openshift.io/owning-component: kube-apiserver
    creationTimestamp: "2026-01-28T09:30:44Z"
    labels:
      auth.openshift.io/managed-certificate-type: target
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:auth.openshift.io/certificate-issuer: {}
            f:auth.openshift.io/certificate-not-after: {}
            f:auth.openshift.io/certificate-not-before: {}
            f:certificates.openshift.io/auto-regenerate-after-offline-expiry: {}
            f:certificates.openshift.io/refresh-period: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
          f:labels:
            .: {}
            f:auth.openshift.io/managed-certificate-type: {}
        f:type: {}
      manager: cluster-kube-apiserver-operator
      operation: Update
      time: "2026-01-28T09:30:44Z"
    name: kube-scheduler-client-cert-key
    namespace: openshift-config-managed
    resourceVersion: "6810"
    uid: 0535c63f-8e28-4c81-8e7a-9922fa275df9
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    apps.ci-ln-vjb5l1t-76ef8.XXXXXXXXXXXXXXXXXXXXXX: NDEwNCBieXRlcyBsb25n
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:32:00Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:apps.ci-ln-vjb5l1t-76ef8.XXXXXXXXXXXXXXXXXXXXXX: {}
        f:type: {}
      manager: ingress-operator
      operation: Update
      time: "2026-01-28T09:32:00Z"
    name: router-certs
    namespace: openshift-config-managed
    resourceVersion: "10648"
    uid: 622be893-0b14-4ae7-8d84-e1da0043d7fd
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "34868"
