---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVhRENDQTFDZ0F3SUJBZ0lJQWdLSUtzeTJHalV3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpsYUZ3MHlPREF4TWpnd09UTXdOREJhTUZJeFVEQk9CZ05WQkFNVFIyTnNkWE4wClpYSXRjM1J2Y21GblpTMXZjR1Z5WVhSdmNpMXRaWFJ5YVdOekxtOXdaVzV6YUdsbWRDMWpiSFZ6ZEdWeUxYTjAKYjNKaFoyVXRiM0JsY21GMGIzSXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBeW5uNXZZWVBzbDE5TGlPV3ZnR0lRMlpHUVFxL3NkL1B4T3FOTzBFWkRUcGxsWjJ6c1R4V1NRZUJYZjVzCkNiSzVoN05aMHVOQjIwRElXVWhBb1dhajN5TFA2ckROUWwvMWhpSFN6cXJaOUVVVlo1aVE0cnVCYWo3anFEMnAKUGZyRTlXdEwzb29wb1I5RFlQelhIN0o4S3B0S2llQ1lSK3M4d0FGNzc4YTZUeUdyR2R0TjdYdmFKc2xVOWkySgozTEdQam5SVEcvc0M0MTVLQVZVQUxlZGxoWWRjOURsTHFoYndLLzgwNkJBTndja3lVeU9BZkl6WjZEU0RZZGR4CncvYU8rd0swU1d6d3cvUE5OM3JySWVqOEdqcXBkZ3JOUVhxMUJ3TnJPL2FzNjltMmlTaTFzc2s5bHV2UmJsOFAKeUlrTUpCOGx6cjBJNlI2dStiMTdOR2ZKYndJREFRQUJvNElCWERDQ0FWZ3dEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGR2JJCjh5eHVCdmI5dklHdHhPN1hpMWduVXJYd01COEdBMVVkSXdRWU1CYUFGSmpCZmxoVlcrS2hIM3o2T2ozYXBjQ3QKUFBYck1JR3JCZ05WSFJFRWdhTXdnYUNDUjJOc2RYTjBaWEl0YzNSdmNtRm5aUzF2Y0dWeVlYUnZjaTF0WlhSeQphV056TG05d1pXNXphR2xtZEMxamJIVnpkR1Z5TFhOMGIzSmhaMlV0YjNCbGNtRjBiM0l1YzNaamdsVmpiSFZ6CmRHVnlMWE4wYjNKaFoyVXRiM0JsY21GMGIzSXRiV1YwY21samN5NXZjR1Z1YzJocFpuUXRZMngxYzNSbGNpMXoKZEc5eVlXZGxMVzl3WlhKaGRHOXlMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNRFVHQ3lzR0FRUUJrZ2dSWkFJQgpCQ1lUSkRJek5ESXdOR1UyTFdSaE5tSXRORFEyWWkxaU9HWTNMVFppTXpOak5ERmtOMk15TnpBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFUcDU4YjRvdnpsbGxybHVXajgrTVk3N09oeHRtUTZtZEJQQnoxMjR2aDU0Rkw1Nk0KRGU0R2lVanByTlp0L3Q5b2RVQzBFTmxaNXBJdFVmM2h3cHBweTAyKzFFNy9xcDBvOGhsbHhEZDZNcnBkcW4vVwowTTlNaGJlYnNxTGZtNmVTcUJpOG1DMmZ4NzNya1pIWnNhOC9ST3M5Y24wTXM4K0NqSzFUZ2lidVBOZU5YQXBwCkNEK2lpTUtkSkczaHM0V01tYmkvY3lTZk56N29oOFVQdGlrNFgyTXJxR1JYcFhMZXQzdW5JV0NsSTFjUUkzY1cKTkg2bHNENis1aExLOE5sY2JHT3o1SmVEa1BUd0V3TVlteHlwYkJXbWtQcXJPM0VxYkpXNGIwVGJDZWJSemQ1Twp0MncvOEZpRWJXaG94RjRaWjRRc2RuL1FzQ3dJMUgwc1pBbzQ0UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/cluster-storage-operator-metrics
        with hostname cluster-storage-operator-metrics.openshift-cluster-storage-operator.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        cluster-storage-operator-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:40Z"
      service.alpha.openshift.io/originating-service-name: cluster-storage-operator-metrics
      service.alpha.openshift.io/originating-service-uid: 234204e6-da6b-446b-b8f7-6b33c41d7c27
      service.beta.openshift.io/expiry: "2028-01-28T09:30:40Z"
    creationTimestamp: "2026-01-28T09:30:40Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"234204e6-da6b-446b-b8f7-6b33c41d7c27"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:40Z"
    name: cluster-storage-operator-serving-cert
    namespace: openshift-cluster-storage-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: cluster-storage-operator-metrics
      uid: 234204e6-da6b-446b-b8f7-6b33c41d7c27
    resourceVersion: "6545"
    uid: 335bb95c-14ab-4d49-ac65-fa6bd968c8b9
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVnRENDQTJpZ0F3SUJBZ0lJSDFwb25lKzlhSUl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRCYUZ3MHlPREF4TWpnd09UTXdOREZhTUZveFdEQldCZ05WQkFNVFQyTnphUzF6CmJtRndjMmh2ZEMxamIyNTBjbTlzYkdWeUxXOXdaWEpoZEc5eUxXMWxkSEpwWTNNdWIzQmxibk5vYVdaMExXTnMKZFhOMFpYSXRjM1J2Y21GblpTMXZjR1Z5WVhSdmNpNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUUNzcS9iWThhUy9wbHRkTk9YbGsyZW9wSmp3d0VRcjhVSVpldTQwUlFtdGJ4UWZQYmdlCmtDV2N6N2ZpZUhsckRXMElYcDBiUURTSFB4RFFvMSs3bnFUTEhIOXBtNHBLT0FWbDdNUExaYUNhbDR1R0hSSksKdlRUclN4djZIZWN2WEp0MkVqa1JJZENyRFNIbGRKQlhLc3ZFVk02WUFXSlRtNWs1SVkzNndoM0piNCtiQnlKYwpRSVlUT1k5SVRkSTcvTkQvYlRaVmVmNlZSaTMyNjBMU3UrQ0JNRGJjS25IY0diTkxVVVdjWTUxMHgxY2RJS0JXCkllUXp0WmhLcGlxVGZvZDNwMTl6NS81M3hSMENUaml5cVJubWxJZ2xQcHlMdkcwbzdkQVlCOHhQc2JEazZLZ0UKcmNqcE5ES1hkMEVUYjJ1bnFITVN3NWkvSExKaDhOdTdmd2FiQWdNQkFBR2pnZ0ZzTUlJQmFEQU9CZ05WSFE4QgpBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVdnpZOWF5N2F6MExBczNlTXQwYWxra1NTalR3d0h3WURWUjBqQkJnd0ZvQVVtTUYrV0ZWYjRxRWYKZlBvNlBkcWx3SzA4OWVzd2dic0dBMVVkRVFTQnN6Q0JzSUpQWTNOcExYTnVZWEJ6YUc5MExXTnZiblJ5YjJ4cwpaWEl0YjNCbGNtRjBiM0l0YldWMGNtbGpjeTV2Y0dWdWMyaHBablF0WTJ4MWMzUmxjaTF6ZEc5eVlXZGxMVzl3ClpYSmhkRzl5TG5OMlk0SmRZM05wTFhOdVlYQnphRzkwTFdOdmJuUnliMnhzWlhJdGIzQmxjbUYwYjNJdGJXVjAKY21samN5NXZjR1Z1YzJocFpuUXRZMngxYzNSbGNpMXpkRzl5WVdkbExXOXdaWEpoZEc5eUxuTjJZeTVqYkhWegpkR1Z5TG14dlkyRnNNRFVHQ3lzR0FRUUJrZ2dSWkFJQkJDWVRKREJrWkRJMU56RTFMVE0zTkRRdE5EazBOQzFpCllqUTVMV1l3Wm1JNU0yUTVNV0V4T1RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXVkS1VLSHgzMkhWYm5mL0UKRkNBL1FlN3ZYL2Y0ZXNHdG55dlBicUtidnIvSjkzV1lnRlRhc29pUmM4UmxuREpiQXkyZjY0RTJDUVRXY3ZtRwpLVXkwL0hvTmdvazcxMEs1ZEVwZFdDUmluTVp5T0hVWVI2cVZVZGxMczRSdmJQVml6a1dKSTdOU1Z4cjNSZS9jCmwvWnhkOXFZYkp1UjB4aFUxM0x0eVJxNnJhRWtPNStiN1RIcDVJTmppZU9HQldjN0xBNTA1bzRUV3h0Y21zUysKWjVPSnQ3QXd2RUhoQWlNcjZBK01KeE9Na3E0VUpCMk1HME53anhVMXJERXZvSGxkUjNUSUJMdmMvbWhZRHY2NwpJRWh3M0dUU3pRZDhwSHhTVU1EekpuZ0VZUmw1NnVXWkdhelNsZXBFeXhLdHVUeER3U01TM0NWbEhWeDlORXRMCkpVaEhPUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/csi-snapshot-controller-operator-metrics
        with hostname csi-snapshot-controller-operator-metrics.openshift-cluster-storage-operator.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:41Z"
      service.alpha.openshift.io/originating-service-name: csi-snapshot-controller-operator-metrics
      service.alpha.openshift.io/originating-service-uid: 0dd25715-3744-4944-bb49-f0fb93d91a19
      service.beta.openshift.io/expiry: "2028-01-28T09:30:41Z"
    creationTimestamp: "2026-01-28T09:30:42Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"0dd25715-3744-4944-bb49-f0fb93d91a19"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:42Z"
    name: serving-cert
    namespace: openshift-cluster-storage-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: csi-snapshot-controller-operator-metrics
      uid: 0dd25715-3744-4944-bb49-f0fb93d91a19
    resourceVersion: "6641"
    uid: c66a053b-f0c3-4265-8d8c-1049b8ee00ec
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35033"
