---
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVVRENDQXppZ0F3SUJBZ0lJVnFIbXNISU8wb3N3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TkRCYUZ3MHlPREF4TWpnd09UTXdOREZhTUVveFNEQkdCZ05WQkFNVFAyTnNkWE4wClpYSXRiMnh0TFc5d1pYSmhkRzl5TFcxbGRISnBZM011YjNCbGJuTm9hV1owTFdOc2RYTjBaWEl0YjJ4dExXOXcKWlhKaGRHOXlMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHlIYXI4MQowam1hZEFLNFVQSFdvYnJDUGR2VmJrNCtsdW1Gd0pEUllCc0dQSnErRUwvcHg4bitlTEVNYmQrY0NPVWNIRTN4Cm5CVHFZL2NnQnhUd0xZVXNsVURLV05qY0tvNFBpbW93elR4ODNCK0lxMnRzYzhwT1NiZ012Z1VuWmxPbUlmWkcKdE5uYkxGTExBWmJlRnpUaEtTMVVDMUdMS2VWWkErdVQ2N2NKdkhmamdFaklmY0VmNTlaTjN2czErVEtsNUpzcQpYMUFMZXRid0x2dmljNTFOanZSTG0xNnM2UENudDJxRWhJZXR4Y0NYaXExR2pWWTZ5ZjdETi9yR0lyWERLRDFmCkkrZkxRL1BZNjlMUkJuRVBTbFhYYk0yMUdWL09VM3NrL3ozeFFibVJTZWpHQUdpSXpaLzNmekx2eWtsRmN6dnAKbEd1ZzRRUXpnQ3JVVG5zQ0F3RUFBYU9DQVV3d2dnRklNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRQpEREFLQmdnckJnRUZCUWNEQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlRYV3B1NzZ5dnlHSmNMClMzLzVhdys4dTM2SXB6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxNnpDQm13WUQKVlIwUkJJR1RNSUdRZ2o5amJIVnpkR1Z5TFc5c2JTMXZjR1Z5WVhSdmNpMXRaWFJ5YVdOekxtOXdaVzV6YUdsbQpkQzFqYkhWemRHVnlMVzlzYlMxdmNHVnlZWFJ2Y2k1emRtT0NUV05zZFhOMFpYSXRiMnh0TFc5d1pYSmhkRzl5CkxXMWxkSEpwWTNNdWIzQmxibk5vYVdaMExXTnNkWE4wWlhJdGIyeHRMVzl3WlhKaGRHOXlMbk4yWXk1amJIVnoKZEdWeUxteHZZMkZzTURVR0N5c0dBUVFCa2dnUlpBSUJCQ1lUSkRFd05HUXpOekZqTFRabVlUUXROR1E0TXkxaApNVFV4TFRrM1ptVm1ZemMyTWpObU5qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFFMlJJakxNemhqeEZxRGlGCjJGNDI2bzk5Y21CWGhBK1liSit6ejZ5VHNTb3VSTmQ1ejJhQ1BkNlErYWJuUWZTa2t5d1JMVkt4N2JQWjNuV2UKaW8wdE9qa3lnL0tMaTU3K0VlK0E5NDQ0WUZyK2hMUWRYYXRDMlpheklFZGZ2clpHM1NlYUtlWWJuNmt5RUZISwoxa2dNNXF2eEorTWhhWVpiYVViS0JPVDZPTDZsWHlQOEVSa0tGWUZDSXpKeitqZkVvRSs1dmZGNHpBbkxZTVhtCkZHc3NyNlV0L1ExamdhYTlqcnlEcXRKSzY2NS9GUTI3RHdFYkZnYjkrZnVvWDZlV1B2ajFPL1FzNWFjVCtzN2YKSjNPWEplakhSOU9GSDU5MmpiRVAzcUF0c0FjbSswdllwb2RMWVpDVnNmVEcvL0FDeHVRcmM5MC9kZDFXOGRlOAp2NU9tUFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEVVRDQ0FqbWdBd0lCQWdJSUV3ME8vaXBXSWFZd0RRWUpLb1pJaHZjTkFRRUxCUUF3TmpFME1ESUdBMVVFCkF3d3JiM0JsYm5Ob2FXWjBMWE5sY25acFkyVXRjMlZ5ZG1sdVp5MXphV2R1WlhKQU1UYzJPVFU1TWpZek5UQWUKRncweU5qQXhNamd3T1RNd016UmFGdzB5T0RBek1qZ3dPVE13TXpWYU1EWXhOREF5QmdOVkJBTU1LMjl3Wlc1egphR2xtZEMxelpYSjJhV05sTFhObGNuWnBibWN0YzJsbmJtVnlRREUzTmprMU9USTJNelV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUM2RGdJZTRYOHM0SmtCSkpyUlgzMzZQaVB4eXZMRjhrSzgKbFhNSEhmQmx0c0JXbFBKTGdLYTNCSWw3VFE1SmJLYm8xd09JcC9oSWhUUW05L0NWWjZ3VElIeVhTZkZBS0I2RQp2b3QyVnRscTk2WHA2TlZMTndwckhudHF5RG01djlXVmRucGNTajQxWGZoYmFLMTl5SUd5ckRsUEs4YlBVWEhwCnQ5VWxRdnN5eGxBbitnYzVSSUdoTzVLTWs3TVptM2ZVcjRCeE4ySnloWGVvc25aRFdRMkxWOHA2aEFaYWZ0U08KRkJOd2c5bzZLSTNPS1A3RUliRXBGTjVBR3E1WnBaalp0NDlJWUM0UnlnMmIwSTh0Y1dXOGpibHdGQUxZcXFSWgpNVStlWG9ldmZVbCtlUjAvWjRwazdGZ0E0SDJ1NVNTaGM0M3hxcG1xaFRTeTRYYlZUL1NSQWdNQkFBR2pZekJoCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWXdYNVkKVlZ2aW9SOTgram85MnFYQXJUejE2ekFmQmdOVkhTTUVHREFXZ0JTWXdYNVlWVnZpb1I5OCtqbzkycVhBclR6MQo2ekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUjZVWHdIMHJpWHo0QmtpczZDQkZ2T0YvYzVMS25xV3ZUd1BGCnpiamNWQVMvTW9LUXVYamVVSGV2dHRDMkdDUUkxMG5CcmFKWFJJTkhrVU81TGFVMlVsQTFYei82ZmhsRjJCSksKZUprZGhxd0JxQ3I5amtISlZNZGFucGduU01DVHIrQ2FTVDNHd2ovNE1NYUh3L0ZGOG00N1ZBZFpSZ2ozZWNIdApIRnlQYkdIMW9WYmZJSmtobmJhQnBGTFZ5ZTJ1Yys3a3hkdTAzeG5qNE9UUW5DNzVqbmcxK2NtS3NZZ1VneENkCkMwM3RUWThVOUE5ZE1Sa01IaXJUdVRqcUlySUIwaFphRDR4WVNNVkhZa2RIeDhzYldyaDhsLzRDOUlCMGpRUEUKV0oyb01NT2lNamR5SGZrSGdLb0w4dUFVenR6alRmd3ZYNEVJcHhQazVseUlnRjN5Nnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/cluster-olm-operator-metrics
        with hostname cluster-olm-operator-metrics.openshift-cluster-olm-operator.svc
        and is annotated to the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        cluster-olm-operator-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:41Z"
      service.alpha.openshift.io/originating-service-name: cluster-olm-operator-metrics
      service.alpha.openshift.io/originating-service-uid: 104d371c-6fa4-4d83-a151-97fefc7623f6
      service.beta.openshift.io/expiry: "2028-01-28T09:30:41Z"
    creationTimestamp: "2026-01-28T09:30:41Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"104d371c-6fa4-4d83-a151-97fefc7623f6"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:41Z"
    name: cluster-olm-operator-serving-cert
    namespace: openshift-cluster-olm-operator
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: cluster-olm-operator-metrics
      uid: 104d371c-6fa4-4d83-a151-97fefc7623f6
    resourceVersion: "6630"
    uid: 6dff4d02-16fc-474e-96d0-926bd008c377
  type: kubernetes.io/tls
kind: SecretList
metadata:
  resourceVersion: "35159"
