---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.0.9/23"],"mac_address":"0a:58:0a:80:00:09","gateway_ips":["10.128.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.128.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.128.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.0.1"}],"ip_address":"10.128.0.9/23","gateway_ip":"10.128.0.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.0.9"
          ],
          "mac": "0a:58:0a:80:00:09",
          "default": true,
          "dns": {}
      }]
    openshift.io/required-scc: restricted-v2
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    security.openshift.io/validated-scc-subject-type: user
  creationTimestamp: "2026-01-28T09:31:06Z"
  generateName: aws-ebs-csi-driver-operator-58fb94fb4b-
  generation: 1
  labels:
    name: aws-ebs-csi-driver-operator
    openshift.storage.network-policy.api-server: allow
    openshift.storage.network-policy.dns: allow
    openshift.storage.network-policy.operator-metrics-range: allow
    pod-template-hash: 58fb94fb4b
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.ovn.org/pod-networks: {}
    manager: ip-10-0-3-203
    operation: Update
    subresource: status
    time: "2026-01-28T09:31:06Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/required-scc: {}
          f:target.workload.openshift.io/management: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:name: {}
          f:openshift.storage.network-policy.api-server: {}
          f:openshift.storage.network-policy.dns: {}
          f:openshift.storage.network-policy.operator-metrics-range: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"2764303b-627b-4f37-b57c-b76d31d7d616"}: {}
      f:spec:
        f:containers:
          k:{"name":"aws-ebs-csi-driver-operator"}:
            .: {}
            f:args: {}
            f:env:
              .: {}
              k:{"name":"ATTACHER_IMAGE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"DRIVER_IMAGE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"KUBE_RBAC_PROXY_IMAGE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"LIVENESS_PROBE_IMAGE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"NODE_DRIVER_REGISTRAR_IMAGE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"OPERATOR_IMAGE_VERSION"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"PROVISIONER_IMAGE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"RESIZER_IMAGE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"SNAPSHOTTER_IMAGE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"TOOLS_IMAGE"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities:
                .: {}
                f:drop: {}
              f:readOnlyRootFilesystem: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/tmp"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:nodeSelector: {}
        f:priorityClassName: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:runAsNonRoot: {}
          f:seccompProfile:
            .: {}
            f:type: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"tmp"}:
            .: {}
            f:emptyDir:
              .: {}
              f:medium: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-01-28T09:31:06Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
    manager: multus-daemon
    operation: Update
    subresource: status
    time: "2026-01-28T09:31:07Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.128.0.9"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2026-01-28T09:31:11Z"
  name: aws-ebs-csi-driver-operator-58fb94fb4b-8qj5n
  namespace: openshift-cluster-csi-drivers
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: aws-ebs-csi-driver-operator-58fb94fb4b
    uid: 2764303b-627b-4f37-b57c-b76d31d7d616
  resourceVersion: "8428"
  uid: af228f62-ff16-4292-bc77-a10117a9a31f
spec:
  containers:
  - args:
    - start
    - -v=2
    env:
    - name: DRIVER_IMAGE
      value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:16eec5fa72b90a0210d17a4497e5f430e1461046890512fc480568fa54542a80
    - name: PROVISIONER_IMAGE
      value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:6dce12cdd98f375e8a7688f4938dd832e5f894c0ba816d4a5a8d6720ff975904
    - name: ATTACHER_IMAGE
      value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:fbec5c24870ed6cd27985bed8371a888e9322898e5ae4d9989e099f05a1c6a23
    - name: RESIZER_IMAGE
      value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:a3d4db4816440b5141aecead32da7cfa9eee4efb8a663c3f0d30a4e23d96d2bf
    - name: SNAPSHOTTER_IMAGE
      value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:deb4bbeb305282d6d6f762ef9e6988b2cd74c4a48c45bcc639f218f06e2da941
    - name: NODE_DRIVER_REGISTRAR_IMAGE
      value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:2049797466a1536cbe9a72805e650920b4847965b8d55585545e9736385f262c
    - name: LIVENESS_PROBE_IMAGE
      value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:688fb2404fabe8055015a5750740f8c43a61dc3f96d0242b15345a54da695af1
    - name: KUBE_RBAC_PROXY_IMAGE
      value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:a0de83cf18d336c19ea214987e67e382cffab05022e12fce60349cc89644374b
    - name: TOOLS_IMAGE
      value: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:d9de3f8e0f8eccb4a81258835fa96b11c41785642ac9da6b2592458071379adc
    - name: OPERATOR_IMAGE_VERSION
      value: 4.20.0-0-2026-01-28-090915-test-ci-ln-vjb5l1t-latest
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:a127655796264964b0aeb27fd0cf27157c6d4702554655aa35018829c98878cb
    imagePullPolicy: IfNotPresent
    name: aws-ebs-csi-driver-operator
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsUser: 1000220000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8mmbd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-3-203.us-west-1.compute.internal
  nodeSelector:
    node-role.kubernetes.io/master: ""
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000220000
    runAsNonRoot: true
    seLinuxOptions:
      level: s0:c15,c5
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: aws-ebs-csi-driver-operator
  serviceAccountName: aws-ebs-csi-driver-operator
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir:
      medium: Memory
    name: tmp
  - name: kube-api-access-8mmbd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:31:11Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:31:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:31:11Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:31:11Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:31:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 10m
      memory: 50Mi
    containerID: cri-o://1c98884521697e49ce9756b7ab425ad652a77664d0fa2589907dbfc70fb22744
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:a127655796264964b0aeb27fd0cf27157c6d4702554655aa35018829c98878cb
    imageID: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:a127655796264964b0aeb27fd0cf27157c6d4702554655aa35018829c98878cb
    lastState: {}
    name: aws-ebs-csi-driver-operator
    ready: true
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-01-28T09:31:10Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1000220000
        uid: 1000220000
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8mmbd
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.3.203
  hostIPs:
  - ip: 10.0.3.203
  phase: Running
  podIP: 10.128.0.9
  podIPs:
  - ip: 10.128.0.9
  qosClass: Burstable
  startTime: "2026-01-28T09:31:06Z"
