---
apiVersion: v1
items:
- apiVersion: v1
  data:
    errors.html: MTM4ODYyIGJ5dGVzIGxvbmc=
    login.html: MTcyOTExIGJ5dGVzIGxvbmc=
    providers.html: MTQ3NjYwIGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:30:51Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:errors.html: {}
          f:login.html: {}
          f:providers.html: {}
        f:type: {}
      manager: authentication-operator
      operation: Update
      time: "2026-01-28T09:30:51Z"
    name: v4-0-config-system-ocp-branding-template
    namespace: openshift-authentication
    resourceVersion: "7301"
    uid: 00843bcb-0a25-4aff-838a-19a691d540e1
  type: Opaque
- apiVersion: v1
  data:
    apps.ci-ln-vjb5l1t-76ef8.XXXXXXXXXXXXXXXXXXXXXX: NDEwNCBieXRlcyBsb25n
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:32:10Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:apps.ci-ln-vjb5l1t-76ef8.XXXXXXXXXXXXXXXXXXXXXX: {}
        f:type: {}
      manager: authentication-operator
      operation: Update
      time: "2026-01-28T09:32:10Z"
    name: v4-0-config-system-router-certs
    namespace: openshift-authentication
    resourceVersion: "11319"
    uid: 77495d18-68ab-4878-9a5a-adcb6cd350e9
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGRENDQXZ5Z0F3SUJBZ0lJV2phK2FYMXpFem93RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TlRoYUZ3MHlPREF4TWpnd09UTXdOVGxhTURjeE5UQXpCZ05WQkFNVExHOWhkWFJvCkxXOXdaVzV6YUdsbWRDNXZjR1Z1YzJocFpuUXRZWFYwYUdWdWRHbGpZWFJwYjI0dWMzWmpNSUlCSWpBTkJna3EKaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExWGd0dndWT09KeStXSlEveWVLdkp0bUdDZzk0U0hpdQpCZkUyaVJpYzlWQ1NRODBERDBDY2RsaFNZbGw1RktyQ0RSY1BpZXhId2pwcGlrdEVtNUN0L3hvSlpMZVFiTGRIClNJYTFuNTFVcURvbnlBRFpWOFNqQm9MQjh1N05Wak5ZMndnT2kzTHVjVzM5ckhFZHRtQmhrVGdtdEcxaW1DZEcKTSt2akdWQkxrZjFVRGlzVzg5eFpEdDdtOGptZEJRM01Hb0VWNk5MWFJaNld2enNtNE54ajVlS1o3L2xIZmxFZApObFdUNFF6VlNlZTkvU0N2NjBDa0VuNDBTN2laUFpqenlaOWJlRTNUWWZOYzkvL0lvdkQyNmRzQm1HcDJOdUpBCjVObTNFOGg2bnkvWC8wcm5hVk1aTGRPZFZsVGVrUm9GeTdSTnNmVWtseFJ1VzlUWWliYUQzUUlEQVFBQm80SUIKSXpDQ0FSOHdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQXdHQTFVZApFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGRnliWlpUT0NvYkxyamlCL1B4QnA3QUVYVmk0TUI4R0ExVWRJd1FZCk1CYUFGSmpCZmxoVlcrS2hIM3o2T2ozYXBjQ3RQUFhyTUhNR0ExVWRFUVJzTUdxQ0xHOWhkWFJvTFc5d1pXNXoKYUdsbWRDNXZjR1Z1YzJocFpuUXRZWFYwYUdWdWRHbGpZWFJwYjI0dWMzWmpnanB2WVhWMGFDMXZjR1Z1YzJocApablF1YjNCbGJuTm9hV1owTFdGMWRHaGxiblJwWTJGMGFXOXVMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNRFVHCkN5c0dBUVFCa2dnUlpBSUJCQ1lUSkdJMk1EQTVNamt4TFdJeE9XWXRORFF6TmkwNU5qSmtMV1ptT0dNd09XTTEKTnprMU9EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF0cmU3R3pIT2E4elpER2xjY2txUmltTVA5bWJ0dklDWQp0RTR1VDYxR3pVcDJKUy9FaVdHR3krVjBBNVJEc3dXbHhLZlpkM3I4YWJibGJ1WDZFSUdIMER0OGc0cG9wTnZsCnNxVDMzSHRyNlpLdWJCcEFnYi9KcmFTQ1FUb2hyVktSUXJhb3RzMXZSd3J6Q3RrblM2QjZoTm1LQ29EV2V5TFUKUlJPWUdndjUzQ1BEcGYzWmNhNmJmdlpqOVFoRjJYS2pjbS9YMk1NSlFxK0J6bmRmdkJqcC9maXgvR0lyeTZ6ZApTU3lCU0lBNU5YQmhhN0ZOalAvVEUxNmJJdzBpRDdtc21kLy9EMVZOVDRNS2tLakJjMStBY3Frc0IzVmhvaVd5ClI3RWFHekVFbGd1RXNod2JDZ2U0MWh6c0dTTlFtMGVXaVdibzV1S2VrOWhLVWh1Mno3bHF1dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJRXcwTy9pcFdJYVl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk9UVTVNall6TlRBZQpGdzB5TmpBeE1qZ3dPVE13TXpSYUZ3MHlPREF6TWpnd09UTXdNelZhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOamsxT1RJMk16VXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZEZ0llNFg4czRKa0JKSnJSWDMzNlBpUHh5dkxGOGtLOApsWE1ISGZCbHRzQldsUEpMZ0thM0JJbDdUUTVKYktibzF3T0lwL2hJaFRRbTkvQ1ZaNndUSUh5WFNmRkFLQjZFCnZvdDJWdGxxOTZYcDZOVkxOd3BySG50cXlEbTV2OVdWZG5wY1NqNDFYZmhiYUsxOXlJR3lyRGxQSzhiUFVYSHAKdDlVbFF2c3l4bEFuK2djNVJJR2hPNUtNazdNWm0zZlVyNEJ4TjJKeWhYZW9zblpEV1EyTFY4cDZoQVphZnRTTwpGQk53ZzlvNktJM09LUDdFSWJFcEZONUFHcTVacFpqWnQ0OUlZQzRSeWcyYjBJOHRjV1c4amJsd0ZBTFlxcVJaCk1VK2VYb2V2ZlVsK2VSMC9aNHBrN0ZnQTRIMnU1U1NoYzQzeHFwbXFoVFN5NFhiVlQvU1JBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNZd1g1WQpWVnZpb1I5OCtqbzkycVhBclR6MTZ6QWZCZ05WSFNNRUdEQVdnQlNZd1g1WVZWdmlvUjk4K2pvOTJxWEFyVHoxCjZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSNlVYd0gwcmlYejRCa2lzNkNCRnZPRi9jNUxLbnFXdlR3UEYKemJqY1ZBUy9Nb0tRdVhqZVVIZXZ0dEMyR0NRSTEwbkJyYUpYUklOSGtVTzVMYVUyVWxBMVh6LzZmaGxGMkJKSwplSmtkaHF3QnFDcjlqa0hKVk1kYW5wZ25TTUNUcitDYVNUM0d3ai80TU1hSHcvRkY4bTQ3VkFkWlJnajNlY0h0CkhGeVBiR0gxb1ZiZklKa2huYmFCcEZMVnllMnVjKzdreGR1MDN4bmo0T1RRbkM3NWpuZzErY21Lc1lnVWd4Q2QKQzAzdFRZOFU5QTlkTVJrTUhpclR1VGpxSXJJQjBoWmFENHhZU01WSFlrZEh4OHNiV3JoOGwvNEM5SUIwalFQRQpXSjJvTU1PaU1qZHlIZmtIZ0tvTDh1QVV6dHpqVGZ3dlg0RUlweFBrNWx5SWdGM3k2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3NSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/oauth-openshift with
        hostname oauth-openshift.openshift-authentication.svc and is annotated to
        the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        v4-0-config-system-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2028-01-28T09:30:59Z"
      service.alpha.openshift.io/originating-service-name: oauth-openshift
      service.alpha.openshift.io/originating-service-uid: b6009291-b19f-4436-962d-ff8c09c57958
      service.beta.openshift.io/expiry: "2028-01-28T09:30:59Z"
    creationTimestamp: "2026-01-28T09:30:59Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/description: {}
            f:openshift.io/owning-component: {}
            f:service.alpha.openshift.io/expiry: {}
            f:service.alpha.openshift.io/originating-service-name: {}
            f:service.alpha.openshift.io/originating-service-uid: {}
            f:service.beta.openshift.io/expiry: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"b6009291-b19f-4436-962d-ff8c09c57958"}: {}
        f:type: {}
      manager: service-ca-operator
      operation: Update
      time: "2026-01-28T09:30:59Z"
    name: v4-0-config-system-serving-cert
    namespace: openshift-authentication
    ownerReferences:
    - apiVersion: v1
      kind: Service
      name: oauth-openshift
      uid: b6009291-b19f-4436-962d-ff8c09c57958
    resourceVersion: "7643"
    uid: bc7acd88-123d-4ee4-8589-148793699bce
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    v4-0-config-system-session: MjAzIGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:40:14Z"
    labels:
      app: oauth-openshift
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:v4-0-config-system-session: {}
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:type: {}
      manager: authentication-operator
      operation: Update
      time: "2026-01-28T09:40:14Z"
    name: v4-0-config-system-session
    namespace: openshift-authentication
    resourceVersion: "18545"
    uid: fd107e2b-dd72-4528-b293-89e3f3a3a9cd
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "34879"
