---
apiVersion: v1
items:
- apiVersion: v1
  data:
    aws_access_key_id: MjAgYnl0ZXMgbG9uZw==
    aws_secret_access_key: NDAgYnl0ZXMgbG9uZw==
  kind: Secret
  metadata:
    annotations:
      cloudcredential.openshift.io/mode: mint
    creationTimestamp: "2026-01-28T09:25:00Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:aws_access_key_id: {}
          f:aws_secret_access_key: {}
        f:type: {}
      manager: cluster-bootstrap
      operation: Update
      time: "2026-01-28T09:25:00Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:cloudcredential.openshift.io/mode: {}
      manager: cloud-credential-operator
      operation: Update
      time: "2026-01-28T09:26:58Z"
    name: aws-creds
    namespace: kube-system
    resourceVersion: "2820"
    uid: 82615f90-308c-4828-898e-ef856d7c33f3
  type: Opaque
- apiVersion: v1
  data:
    config: MCBieXRlcyBsb25n
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:25:20Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:config: {}
        f:type: {}
      manager: cluster-bootstrap
      operation: Update
      time: "2026-01-28T09:25:20Z"
    name: kube-cloud-cfg
    namespace: kube-system
    resourceVersion: "618"
    uid: 2bf18617-444e-435e-8ec4-58993937d172
  type: Opaque
- apiVersion: v1
  data:
    kubeadmin: NjAgYnl0ZXMgbG9uZw==
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-28T09:25:00Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:kubeadmin: {}
        f:type: {}
      manager: cluster-bootstrap
      operation: Update
      time: "2026-01-28T09:25:00Z"
    name: kubeadmin
    namespace: kube-system
    resourceVersion: "473"
    uid: c96af35a-5706-4c3b-8b5e-9afc8fea3eb6
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "35098"
