---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:26:57Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: cloud-credential-operator
    operation: Update
    time: "2026-01-28T10:23:42Z"
  name: cloud-credential-operator-leader
  namespace: openshift-cloud-credential-operator
  resourceVersion: "34643"
  uid: af6fb3fa-88e2-4cd2-81c6-b440586b52c8
spec:
  acquireTime: "2026-01-28T09:40:12.051136Z"
  holderIdentity: 726ebf4f-7e97-4511-ac0d-77ec855c023a
  leaseDurationSeconds: 360
  leaseTransitions: 1
  renewTime: "2026-01-28T10:23:42.267186Z"
