---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2026-01-28T09:25:19Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  managedFields:
  - apiVersion: apiregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kube-aggregator.kubernetes.io/automanaged: {}
      f:spec:
        f:group: {}
        f:groupPriorityMinimum: {}
        f:version: {}
        f:versionPriority: {}
    manager: kube-apiserver
    operation: Update
    time: "2026-01-28T09:25:19Z"
  name: v1.apiserver.openshift.io
  resourceVersion: "615"
  uid: 57ac1542-6e74-4786-8a61-41f034fa9aad
spec:
  group: apiserver.openshift.io
  groupPriorityMinimum: 1000
  version: v1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2026-01-28T09:25:19Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
