---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:37:00Z"
    creationTimestamp: "2026-01-28T09:29:27Z"
    labels:
      app: network-check-source
      endpoints.kubernetes.io/managed-by: endpoint-controller
      service.kubernetes.io/headless: ""
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
            f:service.kubernetes.io/headless: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:37:00Z"
    name: network-check-source
    namespace: openshift-network-diagnostics
    resourceVersion: "15984"
    uid: 12e79f0e-92d6-42ce-88fb-d3aea72f8223
  subsets:
  - addresses:
    - ip: 10.131.0.13
      nodeName: ip-10-0-78-215.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: network-check-source-7577c494d6-pf4wt
        namespace: openshift-network-diagnostics
        uid: f634f946-5490-4dcf-903f-688fed838a3b
    ports:
    - name: check-endpoints
      port: 17698
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-01-28T09:43:34Z"
    creationTimestamp: "2026-01-28T09:29:28Z"
    labels:
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-01-28T09:43:34Z"
    name: network-check-target
    namespace: openshift-network-diagnostics
    resourceVersion: "23208"
    uid: b9f51851-8aa1-4e55-8629-f27d0e2afe4c
  subsets:
  - addresses:
    - ip: 10.128.0.5
      nodeName: ip-10-0-3-203.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: network-check-target-tx8wg
        namespace: openshift-network-diagnostics
        uid: ccfe5f08-f3e5-42b8-83aa-9ba8fe91f783
    - ip: 10.128.2.5
      nodeName: ip-10-0-101-165.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: network-check-target-kchx6
        namespace: openshift-network-diagnostics
        uid: 7a2be850-d5d0-4295-96d7-2c8aa0336d42
    - ip: 10.129.0.3
      nodeName: ip-10-0-102-200.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: network-check-target-74c8c
        namespace: openshift-network-diagnostics
        uid: 6fd59852-5750-4932-b078-8f1812103ec1
    - ip: 10.129.2.3
      nodeName: ip-10-0-22-208.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: network-check-target-z4mmq
        namespace: openshift-network-diagnostics
        uid: fb7ae593-56a1-4eef-86b7-560e5b9eee79
    - ip: 10.130.0.6
      nodeName: ip-10-0-108-54.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: network-check-target-dprgj
        namespace: openshift-network-diagnostics
        uid: e8af8a9a-0577-4cbd-8dcb-51d466ef08c8
    - ip: 10.131.0.4
      nodeName: ip-10-0-78-215.us-west-1.compute.internal
      targetRef:
        kind: Pod
        name: network-check-target-gsfwx
        namespace: openshift-network-diagnostics
        uid: bc7daccc-c9db-4278-94c0-a7fc78109155
    ports:
    - port: 8080
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "35151"
