---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c24,c9
    openshift.io/sa.scc.supplemental-groups: 1000570000/10000
    openshift.io/sa.scc.uid-range: 1000570000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2026-01-28T09:29:26Z"
  labels:
    kubernetes.io/metadata.name: openshift-network-diagnostics
    olm.operatorgroup.uid/a826e922-9cff-46d9-ae7e-960dcbdbfd1b: ""
    openshift.io/cluster-monitoring: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/node-selector: {}
          f:workload.openshift.io/allowed: {}
        f:labels:
          f:openshift.io/cluster-monitoring: {}
        f:ownerReferences:
          k:{"uid":"7763cebb-f1d7-4359-81b8-b55ef9916383"}: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2026-01-28T09:29:26Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2026-01-28T09:29:26Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:olm.operatorgroup.uid/a826e922-9cff-46d9-ae7e-960dcbdbfd1b: {}
    manager: olm
    operation: Update
    time: "2026-01-28T09:31:57Z"
  name: openshift-network-diagnostics
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 7763cebb-f1d7-4359-81b8-b55ef9916383
  resourceVersion: "10233"
  uid: 3d081796-1713-44f5-ac0b-b499954b825f
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
