---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:38:05Z"
  labels:
    apiserver.kubernetes.io/identity: kube-apiserver
    kubernetes.io/hostname: ip-10-0-108-54
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:apiserver.kubernetes.io/identity: {}
          f:kubernetes.io/hostname: {}
      f:spec:
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:renewTime: {}
    manager: kube-apiserver
    operation: Update
    time: "2026-01-28T10:24:24Z"
  name: apiserver-x6jo6pf67orbqfuygxdhlajsnm
  namespace: kube-system
  resourceVersion: "34796"
  uid: a3b60942-76e0-400b-9694-6137cd21bf61
spec:
  holderIdentity: apiserver-x6jo6pf67orbqfuygxdhlajsnm_9abb4104-b227-448e-ab7b-ff0b788a472e
  leaseDurationSeconds: 3600
  renewTime: "2026-01-28T10:24:24.035259Z"
