---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:24:15Z"
  labels:
    apiserver.kubernetes.io/identity: kube-apiserver
    kubernetes.io/hostname: ip-10-0-161-159
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:apiserver.kubernetes.io/identity: {}
          f:kubernetes.io/hostname: {}
      f:spec:
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:renewTime: {}
    manager: kube-apiserver
    operation: Update
    time: "2026-01-28T09:40:56Z"
  name: apiserver-wigxusblk3vdcshliojskpsbse
  namespace: kube-system
  resourceVersion: "19200"
  uid: bda87e3f-75af-4356-8cc0-0a8f1a5ad347
spec:
  holderIdentity: apiserver-wigxusblk3vdcshliojskpsbse_cbb58863-5848-49b1-b5e3-1c4de63cae53
  leaseDurationSeconds: 3600
  renewTime: "2026-01-28T09:40:56.370702Z"
