---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:39:35Z"
  labels:
    apiserver.kubernetes.io/identity: kube-apiserver
    kubernetes.io/hostname: ip-10-0-3-203
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:apiserver.kubernetes.io/identity: {}
          f:kubernetes.io/hostname: {}
      f:spec:
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:renewTime: {}
    manager: kube-apiserver
    operation: Update
    time: "2026-01-28T10:24:25Z"
  name: apiserver-sfnhmwqdqhujfk4it72qf43hb4
  namespace: kube-system
  resourceVersion: "34822"
  uid: fb0022a0-a6f7-441a-9254-805d4e9c8e66
spec:
  holderIdentity: apiserver-sfnhmwqdqhujfk4it72qf43hb4_40a4a613-d7b2-42b8-b5e4-b1c44c740a3a
  leaseDurationSeconds: 3600
  renewTime: "2026-01-28T10:24:25.176985Z"
