---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:24:20Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-01-28T10:24:30Z"
  name: kube-controller-manager
  namespace: kube-system
  resourceVersion: "34847"
  uid: 949212ad-1c5a-420f-b1ea-61c9234f5142
spec:
  acquireTime: "2026-01-28T09:47:23.009069Z"
  holderIdentity: ip-10-0-102-200_05243a79-35e9-4587-9786-31f798ae35f9
  leaseDurationSeconds: 15
  leaseTransitions: 4
  renewTime: "2026-01-28T10:24:30.640544Z"
