---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:24:15Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: kube-scheduler
    operation: Update
    time: "2026-01-28T09:39:36Z"
  name: kube-scheduler
  namespace: kube-system
  resourceVersion: "17727"
  uid: ae9b2e1c-75cc-4ee8-998c-5e8be3a815a1
spec:
  acquireTime: "2026-01-28T09:39:36.317153Z"
  holderIdentity: ""
  leaseDurationSeconds: 1
  leaseTransitions: 0
  renewTime: "2026-01-28T09:39:36.317153Z"
