---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.130.0.56/23"],"mac_address":"0a:58:0a:82:00:38","gateway_ips":["10.130.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.130.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.130.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.130.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.130.0.1"}],"ip_address":"10.130.0.56/23","gateway_ip":"10.130.0.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.130.0.56"
          ],
          "mac": "0a:58:0a:82:00:38",
          "default": true,
          "dns": {}
      }]
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
  creationTimestamp: "2026-01-28T09:34:35Z"
  generation: 1
  labels:
    app: guard
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:k8s.ovn.org/pod-networks: {}
    manager: ip-10-0-108-54
    operation: Update
    subresource: status
    time: "2026-01-28T09:34:35Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
    manager: multus-daemon
    operation: Update
    subresource: status
    time: "2026-01-28T09:34:36Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:target.workload.openshift.io/management: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:containers:
          k:{"name":"guard"}:
            .: {}
            f:args: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:host: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostname: {}
        f:nodeName: {}
        f:priorityClassName: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
    manager: cluster-kube-scheduler-operator
    operation: Update
    time: "2026-01-28T09:34:42Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodScheduled"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.130.0.56"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2026-01-28T09:42:39Z"
  name: openshift-kube-scheduler-guard-ip-10-0-108-54.us-west-1.compute.internal
  namespace: openshift-kube-scheduler
  resourceVersion: "21557"
  uid: 45f2d533-1395-42e9-9f81-c0d848552379
spec:
  containers:
  - args:
    - -c
    - |
      # properly handle TERM and exit as soon as it is signaled
      set -euo pipefail
      trap 'jobs -p | xargs -r kill; exit 0' TERM
      sleep infinity & wait
    command:
    - /bin/bash
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:8da3ae0c230867d7c67107ad8fcd99839b6058f4e9ba9c94c5fc3a865bd20b9f
    imagePullPolicy: IfNotPresent
    name: guard
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: 10.0.108.54
        path: healthz
        port: 10259
        scheme: HTTPS
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 10m
        memory: 5Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fb6vw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: guard-6ea46aabda3d5862845f033a9f097810dc49118e-end
  nodeName: ip-10-0-108-54.us-west-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 3
  tolerations:
  - operator: Exists
  volumes:
  - name: kube-api-access-fb6vw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:34:38Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:34:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:42:39Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:42:39Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-01-28T09:34:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 10m
      memory: 5Mi
    containerID: cri-o://1838717ba96174de36f814c98cf429f99cc724e37b9ceaf6d23cabdafb78fdc9
    image: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:8da3ae0c230867d7c67107ad8fcd99839b6058f4e9ba9c94c5fc3a865bd20b9f
    imageID: registry.build11.ci.openshift.org/ci-ln-vjb5l1t/stable@sha256:8da3ae0c230867d7c67107ad8fcd99839b6058f4e9ba9c94c5fc3a865bd20b9f
    lastState: {}
    name: guard
    ready: true
    resources:
      requests:
        cpu: 10m
        memory: 5Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-01-28T09:34:38Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fb6vw
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.108.54
  hostIPs:
  - ip: 10.0.108.54
  phase: Running
  podIP: 10.130.0.56
  podIPs:
  - ip: 10.130.0.56
  qosClass: Burstable
  startTime: "2026-01-28T09:34:35Z"
