---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:29:44Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: ip-10-0-102-200
    operation: Update
    time: "2026-01-28T10:24:21Z"
  name: ovn-kubernetes-master
  namespace: openshift-ovn-kubernetes
  resourceVersion: "34784"
  uid: b66f4d74-35a9-42bd-bbe5-93c3c9766643
spec:
  acquireTime: "2026-01-28T09:29:44.949926Z"
  holderIdentity: ovnkube-control-plane-74c65dbd9b-gbdrw
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:21.812498Z"
