---
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: "2026-01-28T09:29:25Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"7763cebb-f1d7-4359-81b8-b55ef9916383"}: {}
      f:spec:
        f:hard:
          f:count/daemonsets.apps: {}
          f:count/deployments.apps: {}
          f:limits.cpu: {}
          f:limits.memory: {}
          f:pods: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2026-01-28T09:29:25Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hard:
          .: {}
          f:count/daemonsets.apps: {}
          f:count/deployments.apps: {}
          f:limits.cpu: {}
          f:limits.memory: {}
          f:pods: {}
        f:used:
          .: {}
          f:count/daemonsets.apps: {}
          f:count/deployments.apps: {}
          f:limits.cpu: {}
          f:limits.memory: {}
          f:pods: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2026-01-28T09:29:25Z"
  name: host-network-namespace-quotas
  namespace: openshift-host-network
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 7763cebb-f1d7-4359-81b8-b55ef9916383
  resourceVersion: "4447"
  uid: a820be10-f526-4dbd-93aa-a4841833f514
spec:
  hard:
    count/daemonsets.apps: "0"
    count/deployments.apps: "0"
    limits.cpu: "0"
    limits.memory: "0"
    pods: "0"
status:
  hard:
    count/daemonsets.apps: "0"
    count/deployments.apps: "0"
    limits.cpu: "0"
    limits.memory: "0"
    pods: "0"
  used:
    count/daemonsets.apps: "0"
    count/deployments.apps: "0"
    limits.cpu: "0"
    limits.memory: "0"
    pods: "0"
