---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2026-01-28T09:31:14Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: operator-controller
    operation: Update
    time: "2026-01-28T10:24:12Z"
  name: 9c4404e7.operatorframework.io
  namespace: openshift-operator-controller
  resourceVersion: "34751"
  uid: 055822c0-d427-428f-b3cb-aa32be5dda22
spec:
  acquireTime: "2026-01-28T09:31:14.896928Z"
  holderIdentity: operator-controller-controller-manager-66b6b87dc7-msqnr_4b95a3ba-ab63-4ea1-97c2-4097a2bae652
  leaseDurationSeconds: 137
  leaseTransitions: 0
  renewTime: "2026-01-28T10:24:12.906870Z"
