---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: "2026-01-28T09:29:25Z"
  generation: 1
  managedFields:
  - apiVersion: admissionregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"7763cebb-f1d7-4359-81b8-b55ef9916383"}: {}
      f:spec:
        f:matchResources: {}
        f:policyName: {}
        f:validationActions:
          v:"Deny": {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2026-01-28T09:29:25Z"
  name: user-defined-networks-namespace-label-binding
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: 7763cebb-f1d7-4359-81b8-b55ef9916383
  resourceVersion: "4528"
  uid: a997f234-4cfd-430c-a414-53f76a468d4d
spec:
  matchResources:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    resourceRules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - UPDATE
      resources:
      - namespaces
      scope: '*'
  policyName: user-defined-networks-namespace-label
  validationActions:
  - Deny
